TMXExternalSource
std::string TMXExternalSource::m_filePath
std::ifstream TMXExternalSource::m_file
G4ThreeVector TMXExternalSource::m_translation
std::string TMXExternalSource::m_currentLine
bool TMXExternalSource::m_isInitialised
G4ThreeVector TMXExternalSource::m_position
G4ThreeVector TMXExternalSource::m_direction
double TMXExternalSource::m_energy
std::string TMXExternalSource::m_stringParticleID
int TMXExternalSource::m_numberOfEvents
int TMXExternalSource::m_numberOfSourceParticlesInFile
int TMXExternalSource::m_numberOfSourceParticlesRequested
std::map< int, std::string > TMXExternalSource::m_particleIdToString
TMXExternalSource::TMXExternalSource()
TMXExternalSource::TMXExternalSource.
TMXExternalSource::~TMXExternalSource()
TMXExternalSource::~TMXExternalSource.
References endOfCalculation.
void TMXExternalSource::next()
TMXExternalSource::next.
void TMXExternalSource::initialize(std::string, int)
TMXExternalSource::initialize.
path n
References setFilePath, setNumberOfParticleToSample.
void TMXExternalSource::endOfCalculation()
TMXExternalSource::endOfCalculation.
Referenced by ~TMXExternalSource.
G4ThreeVector TMXExternalSource::getPosition()
TMXExternalSource::getPosition.
G4ThreeVector TMXExternalSource::getDirection()
TMXExternalSource::getDirection.
double TMXExternalSource::getEnergy()
TMXExternalSource::getEnergy.
int TMXExternalSource::getNumberOfEvents()
TMXExternalSource::setFilePath.
path
std::string TMXExternalSource::getParticleID()
TMXExternalSource::getPrimary.
void TMXExternalSource::setFilePath(std::string)
TMXExternalSource::setFilePath.
path
Referenced by initialize.
void TMXExternalSource::setTargetTranslation(G4ThreeVector)
TMXExternalSource::setTargetTranslation.
v
void TMXExternalSource::setNumberOfParticleToSample(int)
TMXExternalSource::setNumberOfParticleToSample.
x
Referenced by initialize.
TMXExternalSource::TMXExternalSource()
TMXExternalSource::~TMXExternalSource()
void TMXExternalSource::next()
void TMXExternalSource::initialize(std::string, int)
void TMXExternalSource::endOfCalculation()
G4ThreeVector TMXExternalSource::getPosition()
G4ThreeVector TMXExternalSource::getDirection()
double TMXExternalSource::getEnergy()
int TMXExternalSource::getNumberOfEvents()
std::string TMXExternalSource::getParticleID()
void TMXExternalSource::setFilePath(std::string)
void TMXExternalSource::setTargetTranslation(G4ThreeVector)
void TMXExternalSource::setNumberOfParticleToSample(int)
TMXExternalSource::TMXExternalSource()
TMXExternalSource::~TMXExternalSource()
void TMXExternalSource::next()
void TMXExternalSource::initialize(std::string, int)
void TMXExternalSource::endOfCalculation()
G4ThreeVector TMXExternalSource::getPosition()
G4ThreeVector TMXExternalSource::getDirection()
double TMXExternalSource::getEnergy()
int TMXExternalSource::getNumberOfEvents()
std::string TMXExternalSource::getParticleID()
void TMXExternalSource::setFilePath(std::string)
void TMXExternalSource::setTargetTranslation(G4ThreeVector)
void TMXExternalSource::setNumberOfParticleToSample(int)
TMXExternalSource::TMXExternalSource()
TMXExternalSource::~TMXExternalSource()
void TMXExternalSource::next()
void TMXExternalSource::initialize(std::string, int)
void TMXExternalSource::endOfCalculation()
G4ThreeVector TMXExternalSource::getPosition()
G4ThreeVector TMXExternalSource::getDirection()
double TMXExternalSource::getEnergy()
int TMXExternalSource::getNumberOfEvents()
std::string TMXExternalSource::getParticleID()
void TMXExternalSource::setFilePath(std::string)
void TMXExternalSource::setTargetTranslation(G4ThreeVector)
void TMXExternalSource::setNumberOfParticleToSample(int)
TMXExternalSource::TMXExternalSource()
TMXExternalSource::~TMXExternalSource()
void TMXExternalSource::next()
void TMXExternalSource::initialize(std::string, int)
void TMXExternalSource::endOfCalculation()
G4ThreeVector TMXExternalSource::getPosition()
G4ThreeVector TMXExternalSource::getDirection()
double TMXExternalSource::getEnergy()
int TMXExternalSource::getNumberOfEvents()
std::string TMXExternalSource::getParticleID()
void TMXExternalSource::setFilePath(std::string)
void TMXExternalSource::setTargetTranslation(G4ThreeVector)
void TMXExternalSource::setNumberOfParticleToSample(int)
void TMXExternalSource::defineMapParticleConverter()
TMXExternalSource::defineMapParticleConverter.
void TMXExternalSource::buildSourceParameters()
TMXExternalSource::buildSourceParameters.
void TMXExternalSource::initializeFile()
TMXExternalSource::readFile.
void TMXExternalSource::countNumberOfSourceParticlesInFile()
TMXExternalSource::countNumberOfSourceParticlesInFile.
void TMXExternalSource::pursueCalculation()
TMXExternalSource::pursueCalculation.
void TMXExternalSource::defineMapParticleConverter()
void TMXExternalSource::buildSourceParameters()
void TMXExternalSource::initializeFile()
void TMXExternalSource::countNumberOfSourceParticlesInFile()
void TMXExternalSource::pursueCalculation()
void TMXExternalSource::defineMapParticleConverter()
void TMXExternalSource::buildSourceParameters()
void TMXExternalSource::initializeFile()
void TMXExternalSource::countNumberOfSourceParticlesInFile()
void TMXExternalSource::pursueCalculation()
void TMXExternalSource::defineMapParticleConverter()
void TMXExternalSource::buildSourceParameters()
void TMXExternalSource::initializeFile()
void TMXExternalSource::countNumberOfSourceParticlesInFile()
void TMXExternalSource::pursueCalculation()
void TMXExternalSource::defineMapParticleConverter()
void TMXExternalSource::buildSourceParameters()
void TMXExternalSource::initializeFile()
void TMXExternalSource::countNumberOfSourceParticlesInFile()
void TMXExternalSource::pursueCalculation()