TMXFissionSourceBank
std::vector< FissionSite > TMXFissionSourceBank::m_currentCycleBank
std::vector< FissionSite > TMXFissionSourceBank::m_previousCycleBank
std::vector< G4ThreeVector > TMXFissionSourceBank::m_currentCycleBankLoc
std::vector< G4ThreeVector > TMXFissionSourceBank::m_previousCycleBankLoc
std::vector< G4double > TMXFissionSourceBank::m_currentCycleBankEner
std::vector< G4double > TMXFissionSourceBank::m_previousCycleBankEner
TMXFissionSourceBank::TMXFissionSourceBank()
TMXFissionSourceBank::TMXFissionSourceBank.
void TMXFissionSourceBank::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
TMXFissionSourceBank::addFissionSource.
location momentum energy
Referenced by TMXkeff::addFissionSite.
void TMXFissionSourceBank::addLocationSite(G4ThreeVector)
void TMXFissionSourceBank::addEnergySite(G4double)
FissionSite TMXFissionSourceBank::getFissionSite(int)
TMXFissionSourceBank::getFissionSource.
num
Referenced by TMXkeff::getFissionSite.
G4ThreeVector TMXFissionSourceBank::getFissionSiteLoc(double)
G4double TMXFissionSourceBank::getFissionSiteE(double)
int TMXFissionSourceBank::getNumberOfFissionSites()
TMXFissionSourceBank::getNumberOfFissionSources.
Referenced by TMXkeff::computeKeffCycle, TMXkeff::getNumberOfFissionSites.
void TMXFissionSourceBank::nextCycle()
TMXFissionSourceBank::nextCycle.
Referenced by TMXkeff::computeKeffCycle.
TMXFissionSourceBank::TMXFissionSourceBank()
void TMXFissionSourceBank::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXFissionSourceBank::addLocationSite(G4ThreeVector)
void TMXFissionSourceBank::addEnergySite(G4double)
FissionSite TMXFissionSourceBank::getFissionSite(int)
G4ThreeVector TMXFissionSourceBank::getFissionSiteLoc(double)
G4double TMXFissionSourceBank::getFissionSiteE(double)
int TMXFissionSourceBank::getNumberOfFissionSites()
void TMXFissionSourceBank::nextCycle()
TMXFissionSourceBank::TMXFissionSourceBank()
void TMXFissionSourceBank::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXFissionSourceBank::addLocationSite(G4ThreeVector)
void TMXFissionSourceBank::addEnergySite(G4double)
FissionSite TMXFissionSourceBank::getFissionSite(int)
G4ThreeVector TMXFissionSourceBank::getFissionSiteLoc(double)
G4double TMXFissionSourceBank::getFissionSiteE(double)
int TMXFissionSourceBank::getNumberOfFissionSites()
void TMXFissionSourceBank::nextCycle()
TMXFissionSourceBank::TMXFissionSourceBank()
void TMXFissionSourceBank::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXFissionSourceBank::addLocationSite(G4ThreeVector)
void TMXFissionSourceBank::addEnergySite(G4double)
FissionSite TMXFissionSourceBank::getFissionSite(int)
G4ThreeVector TMXFissionSourceBank::getFissionSiteLoc(double)
G4double TMXFissionSourceBank::getFissionSiteE(double)
int TMXFissionSourceBank::getNumberOfFissionSites()
void TMXFissionSourceBank::nextCycle()
TMXFissionSourceBank::TMXFissionSourceBank()
void TMXFissionSourceBank::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXFissionSourceBank::addLocationSite(G4ThreeVector)
void TMXFissionSourceBank::addEnergySite(G4double)
FissionSite TMXFissionSourceBank::getFissionSite(int)
G4ThreeVector TMXFissionSourceBank::getFissionSiteLoc(double)
G4double TMXFissionSourceBank::getFissionSiteE(double)
int TMXFissionSourceBank::getNumberOfFissionSites()
void TMXFissionSourceBank::nextCycle()
TMXFissionSourceBank::TMXFissionSourceBank()
void TMXFissionSourceBank::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
FissionSite TMXFissionSourceBank::getFissionSite(int)
int TMXFissionSourceBank::getNumberOfFissionSites()
void TMXFissionSourceBank::nextCycle()