TMXkeff
std::vector< double > TMXkeff::m_kcolPerCycle
std::vector< double > TMXkeff::m_kgenPerCycle
std::vector< double > TMXkeff::m_ktrkPerCycle
std::vector< double > TMXkeff::m_kabsPerCycle
std::vector< int > TMXkeff::m_nbFissionPerCycle
std::vector< double > TMXkeff::m_nbAbsorptionPerCycle
std::vector< double > TMXkeff::m_nbCollisionsPerCycle
std::vector< double > TMXkeff::m_nbTrckLengthPerCycle
int TMXkeff::m_nbTotCycle
int TMXkeff::m_currentCycle
int TMXkeff::m_nbCycleToDiscard
int TMXkeff::m_nbParticlePerCycle
std::string TMXkeff::m_kFilename
std::ofstream TMXkeff::m_File
TMXFissionSourceBank TMXkeff::m_fissionSourceBank
double TMXkeff::m_nbFission
std::vector< double > TMXkeff::m_energyFromFission
std::vector< double > TMXkeff::m_vecEPerFission
double TMXkeff::m_eperfiss
int TMXkeff::m_samplingSourceNumber
std::vector< double > TMXkeff::m_countCapture
std::vector< double > TMXkeff::m_countFission
std::vector< double > TMXkeff::m_fissionEnergy
std::vector< double > TMXkeff::m_nu
G4FPYSamplingOps * TMXkeff::m_sampler
std::vector< G4ThreeVector > TMXkeff::m_originPositions
int TMXkeff::m_countTransportation
int TMXkeff::m_countCapture
int TMXkeff::m_countFission
int TMXkeff::m_countElastic
int TMXkeff::m_countInelastic
double TMXkeff::m_fissionEnergy
TMXkeff * TMXkeff::getInstance()
TMXkeff::getInstance.
static TMXkeff * TMXkeff::getInstance()
static TMXkeff * TMXkeff::getInstance()
static TMXkeff * TMXkeff::getInstance()
static TMXkeff * TMXkeff::getInstance()
static TMXkeff * TMXkeff::getInstance()
void TMXkeff::run(G4MTRunManager *)
void TMXkeff::inUserSteppingAction(const G4Step *)
TMXkeff::scoring.
TMXkeff::inUserSteppingAction. theStep
References addAbsorption, addCollision, addFission, addFissionSite, addTrackLength.
void TMXkeff::inGeneratePrimaries(G4ParticleGun *, G4Event *)
TMXkeff::inGeneratePrimaries.
particleGun anEvent
References getNumberOfFissionSites.
void TMXkeff::reinitialize()
TMXkeff::reinitialize.
References setNbParticlePerCycle.
void TMXkeff::computeKeffCycle()
TMXkeff::computeKeffCycle.
nbFissions
References TMXFissionSourceBank::getNumberOfFissionSites, TMXFissionSourceBank::nextCycle, printAll.
void TMXkeff::addFission(double)
TMXkeff::addFission.
Referenced by inUserSteppingAction.
void TMXkeff::addCollision(double)
TMXkeff::addCollision.
col
Referenced by inUserSteppingAction.
void TMXkeff::addAbsorption(double)
TMXkeff::addAbsorption.
absor
Referenced by inUserSteppingAction.
void TMXkeff::addTrackLength(double)
TMXkeff::addTrackLength.
trc
Referenced by inUserSteppingAction.
void TMXkeff::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
TMXkeff::addFissionSite.
location direction energy
References TMXFissionSourceBank::addFissionSite.
Referenced by inUserSteppingAction.
void TMXkeff::addOriginPosition(G4ThreeVector position)
TMXkeff::addOriginPosition.
position
int TMXkeff::getCurrentCycle()
TMXkeff::getCurrentCycle.
int TMXkeff::getNumberOfFissionSites()
TMXkeff::getFissionSiteNumber.
int
References TMXFissionSourceBank::getNumberOfFissionSites.
Referenced by inGeneratePrimaries.
FissionSite TMXkeff::getFissionSite(int)
TMXkeff::getFissionSite.
num
References TMXFissionSourceBank::getFissionSite.
int TMXkeff::getNbNeutronPerCycle()
TMXkeff::getNbNeutronPerCycle.
int TMXkeff::getNbCycleToDiscard()
TMXkeff::getNbCycleToDiscard.
int TMXkeff::getNbTotCycle()
TMXkeff::getNbTotCycle.
void TMXkeff::setNbParticlePerCycle(int)
TMXkeff::setNbNeutronPerCycle.
nbNeutronPerCycle
Referenced by reinitialize.
void TMXkeff::setNbCycleToDiscard(int)
TMXkeff::setNbCycleToDiscard.
nbCycleToDiscard
void TMXkeff::setNbTotCycle(int)
TMXkeff::setNbTotCycle.
nbTotCycle
void TMXkeff::setOutputFileName(std::string)
TMXkeff::setOutputFileName.
output
void TMXkeff::printAll()
TMXkeff::printAll.
Referenced by computeKeffCycle.
void TMXkeff::writeKResults()
TMXkeff::writeKResults.
double TMXkeff::getNu()
TMXkeff::getNu.
double TMXkeff::getEnergyPerFission()
TMXkeff & TMXkeff::operator=(const TMXkeff &b)
void TMXkeff::run(G4MTRunManager *)
void TMXkeff::inUserSteppingAction(const G4Step *)
void TMXkeff::inGeneratePrimaries(G4ParticleGun *, G4Event *)
void TMXkeff::reinitialize()
void TMXkeff::computeKeffCycle()
void TMXkeff::addFission(double)
void TMXkeff::addCollision(double)
void TMXkeff::addAbsorption(double)
void TMXkeff::addTrackLength(double)
void TMXkeff::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXkeff::addOriginPosition(G4ThreeVector position)
int TMXkeff::getCurrentCycle()
int TMXkeff::getNumberOfFissionSites()
FissionSite TMXkeff::getFissionSite(int)
int TMXkeff::getNbNeutronPerCycle()
int TMXkeff::getNbCycleToDiscard()
int TMXkeff::getNbTotCycle()
void TMXkeff::setNbParticlePerCycle(int)
void TMXkeff::setNbCycleToDiscard(int)
void TMXkeff::setNbTotCycle(int)
void TMXkeff::setOutputFileName(std::string)
void TMXkeff::printAll()
void TMXkeff::writeKResults()
double TMXkeff::getNu()
double TMXkeff::getEnergyPerFission()
TMXkeff & TMXkeff::operator=(const TMXkeff &b)
void TMXkeff::run(G4MTRunManager *)
void TMXkeff::inUserSteppingAction(const G4Step *)
void TMXkeff::inGeneratePrimaries(G4ParticleGun *, G4Event *)
void TMXkeff::reinitialize()
void TMXkeff::computeKeffCycle()
void TMXkeff::addFission(double)
void TMXkeff::addCollision(double)
void TMXkeff::addAbsorption(double)
void TMXkeff::addTrackLength(double)
void TMXkeff::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXkeff::addOriginPosition(G4ThreeVector position)
int TMXkeff::getCurrentCycle()
int TMXkeff::getNumberOfFissionSites()
FissionSite TMXkeff::getFissionSite(int)
int TMXkeff::getNbNeutronPerCycle()
int TMXkeff::getNbCycleToDiscard()
int TMXkeff::getNbTotCycle()
void TMXkeff::setNbParticlePerCycle(int)
void TMXkeff::setNbCycleToDiscard(int)
void TMXkeff::setNbTotCycle(int)
void TMXkeff::setOutputFileName(std::string)
void TMXkeff::printAll()
void TMXkeff::writeKResults()
double TMXkeff::getNu()
double TMXkeff::getEnergyPerFission()
TMXkeff & TMXkeff::operator=(const TMXkeff &b)
void TMXkeff::run(G4MTRunManager *)
void TMXkeff::inUserSteppingAction(const G4Step *)
void TMXkeff::inGeneratePrimaries(G4ParticleGun *, G4Event *)
void TMXkeff::reinitialize()
void TMXkeff::computeKeffCycle()
void TMXkeff::addFission(double)
void TMXkeff::addCollision(double)
void TMXkeff::addAbsorption(double)
void TMXkeff::addTrackLength(double)
void TMXkeff::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXkeff::addOriginPosition(G4ThreeVector position)
int TMXkeff::getCurrentCycle()
int TMXkeff::getNumberOfFissionSites()
FissionSite TMXkeff::getFissionSite(int)
int TMXkeff::getNbNeutronPerCycle()
int TMXkeff::getNbCycleToDiscard()
int TMXkeff::getNbTotCycle()
void TMXkeff::setNbParticlePerCycle(int)
void TMXkeff::setNbCycleToDiscard(int)
void TMXkeff::setNbTotCycle(int)
void TMXkeff::setOutputFileName(std::string)
void TMXkeff::printAll()
void TMXkeff::writeKResults()
double TMXkeff::getNu()
double TMXkeff::getEnergyPerFission()
TMXkeff & TMXkeff::operator=(const TMXkeff &b)
void TMXkeff::run(G4MTRunManager *)
void TMXkeff::inUserSteppingAction(const G4Step *)
void TMXkeff::inGeneratePrimaries(G4ParticleGun *, G4Event *)
void TMXkeff::reinitialize()
void TMXkeff::computeKeffCycle()
void TMXkeff::addFission(double)
void TMXkeff::addCollision(double)
void TMXkeff::addAbsorption(double)
void TMXkeff::addTrackLength(double)
void TMXkeff::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
void TMXkeff::addOriginPosition(G4ThreeVector position)
int TMXkeff::getCurrentCycle()
int TMXkeff::getNumberOfFissionSites()
FissionSite TMXkeff::getFissionSite(int)
int TMXkeff::getNbNeutronPerCycle()
int TMXkeff::getNbCycleToDiscard()
int TMXkeff::getNbTotCycle()
void TMXkeff::setNbParticlePerCycle(int)
void TMXkeff::setNbCycleToDiscard(int)
void TMXkeff::setNbTotCycle(int)
void TMXkeff::setOutputFileName(std::string)
void TMXkeff::printAll()
void TMXkeff::writeKResults()
double TMXkeff::getNu()
double TMXkeff::getEnergyPerFission()
TMXkeff & TMXkeff::operator=(const TMXkeff &b)
void TMXkeff::run(G4MTRunManager *)
void TMXkeff::inUserSteppingAction(const G4Step *)
void TMXkeff::inGeneratePrimaries(G4ParticleGun *, G4Event *)
void TMXkeff::computeKeffCycle()
void TMXkeff::addFission(double)
void TMXkeff::addCollision(double)
void TMXkeff::addAbsorption(double)
void TMXkeff::addTrackLength(double)
void TMXkeff::addFissionSite(G4ThreeVector, G4ThreeVector, double, G4ThreeVector)
int TMXkeff::getCurrentCycle()
int TMXkeff::getNumberOfFissionSites()
FissionSite TMXkeff::getFissionSite(int)
int TMXkeff::getNbNeutronPerCycle()
int TMXkeff::getNbCycleToDiscard()
int TMXkeff::getNbTotCycle()
void TMXkeff::setNbParticlePerCycle(int)
void TMXkeff::setNbCycleToDiscard(int)
void TMXkeff::setNbTotCycle(int)
void TMXkeff::setOutputFileName(std::string)
void TMXkeff::printAll()
void TMXkeff::writeKResults()
TMXkeff & TMXkeff::operator=(const TMXkeff &b)
TMXkeff::TMXkeff()
TMXkeff::TMXkeff.
TMXkeff::~TMXkeff()
TMXkeff::~TMXkeff.
double TMXkeff::computeMean(std::vector< double >)
TMXkeff::computeAverage.
TMXkeff::computeMean. k
double TMXkeff::computeMeanStdev(std::vector< double >)
TMXkeff::computeSampleVariance.
TMXkeff::computeMeanStdev.
std::vector< double > TMXkeff::multiplyVectors(std::vector< double >, std::vector< double >)
std::vector< double > TMXkeff::divideVectors(std::vector< double >, std::vector< double >)
void TMXkeff::nextCycle()
TMXkeff::nextCycle.
void TMXkeff::printCycleKeff()
TMXkeff::printKeffResult.
G4double TMXkeff::GetMaterialXS(const G4Step *, std::string)
TMXkeff::GetMaterialXS.
theStep XSreaction
TMXkeff::TMXkeff()
TMXkeff::~TMXkeff()
double TMXkeff::computeMean(std::vector< double >)
double TMXkeff::computeMeanStdev(std::vector< double >)
std::vector< double > TMXkeff::multiplyVectors(std::vector< double >, std::vector< double >)
std::vector< double > TMXkeff::divideVectors(std::vector< double >, std::vector< double >)
void TMXkeff::nextCycle()
void TMXkeff::printCycleKeff()
G4double TMXkeff::GetMaterialXS(const G4Step *, std::string)
TMXkeff::TMXkeff()
TMXkeff::~TMXkeff()
double TMXkeff::computeMean(std::vector< double >)
double TMXkeff::computeMeanStdev(std::vector< double >)
std::vector< double > TMXkeff::multiplyVectors(std::vector< double >, std::vector< double >)
std::vector< double > TMXkeff::divideVectors(std::vector< double >, std::vector< double >)
void TMXkeff::nextCycle()
void TMXkeff::printCycleKeff()
G4double TMXkeff::GetMaterialXS(const G4Step *, std::string)
TMXkeff::TMXkeff()
TMXkeff::~TMXkeff()
double TMXkeff::computeMean(std::vector< double >)
double TMXkeff::computeMeanStdev(std::vector< double >)
std::vector< double > TMXkeff::multiplyVectors(std::vector< double >, std::vector< double >)
std::vector< double > TMXkeff::divideVectors(std::vector< double >, std::vector< double >)
void TMXkeff::nextCycle()
void TMXkeff::printCycleKeff()
G4double TMXkeff::GetMaterialXS(const G4Step *, std::string)
TMXkeff::TMXkeff()
TMXkeff::~TMXkeff()
double TMXkeff::computeMean(std::vector< double >)
double TMXkeff::computeMeanStdev(std::vector< double >)
std::vector< double > TMXkeff::multiplyVectors(std::vector< double >, std::vector< double >)
std::vector< double > TMXkeff::divideVectors(std::vector< double >, std::vector< double >)
void TMXkeff::nextCycle()
void TMXkeff::printCycleKeff()
G4double TMXkeff::GetMaterialXS(const G4Step *, std::string)
TMXkeff::TMXkeff()
TMXkeff::~TMXkeff()
double TMXkeff::computeMean(std::vector< double >)
double TMXkeff::computeMeanStdev(std::vector< double >)
void TMXkeff::nextCycle()
void TMXkeff::printCycleKeff()
G4double TMXkeff::GetMaterialXS(const G4Step *, std::string)
std::map< std::string, G4double > TMXkeff::GetMicroXS(const G4Step *, std::string)