.TH "B1ActionInitialization" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1ActionInitialization \- Action initialization class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <B1ActionInitialization\&.hh>\fP
.PP
Inherits G4VUserActionInitialization\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBBuildForMaster\fP () const"
.br
.ti -1c
.RI "virtual void \fBBuild\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Action initialization class\&. 
.PP
Definition at line \fB37\fP of file \fBB1ActionInitialization\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "B1ActionInitialization::B1ActionInitialization ()"

.PP
Definition at line \fB38\fP of file \fBB1ActionInitialization\&.cc\fP\&.
.SS "B1ActionInitialization::~B1ActionInitialization ()\fC [virtual]\fP"

.PP
Definition at line \fB44\fP of file \fBB1ActionInitialization\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void B1ActionInitialization::Build () const\fC [virtual]\fP"

.PP
Definition at line \fB57\fP of file \fBB1ActionInitialization\&.cc\fP\&.
.SS "void B1ActionInitialization::BuildForMaster () const\fC [virtual]\fP"

.PP
Definition at line \fB49\fP of file \fBB1ActionInitialization\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
