.TH "B1DetectorConstruction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1DetectorConstruction \- Detector construction class to define materials and geometry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <B1DetectorConstruction\&.hh>\fP
.PP
Inherits G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4Element * \fBDefineElement\fP (int IZA, std::string name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Detector construction class to define materials and geometry\&. 
.PP
Definition at line \fB42\fP of file \fBB1DetectorConstruction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "B1DetectorConstruction::B1DetectorConstruction ()"

.PP
Definition at line \fB47\fP of file \fBB1DetectorConstruction\&.cc\fP\&.
.SS "B1DetectorConstruction::~B1DetectorConstruction ()\fC [virtual]\fP"

.PP
Definition at line \fB53\fP of file \fBB1DetectorConstruction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * B1DetectorConstruction::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB58\fP of file \fBB1DetectorConstruction\&.cc\fP\&.
.SS "G4Element * B1DetectorConstruction::DefineElement (int IZA, std::string name)"

.PP
Definition at line \fB324\fP of file \fBB1DetectorConstruction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
