.TH "/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/src/B1DetectorConstruction.cc" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/src/B1DetectorConstruction.cc \- Implementation of the \fBB1DetectorConstruction\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'B1DetectorConstruction\&.hh'\fP
.br
\fC#include 'G4RunManager\&.hh'\fP
.br
\fC#include 'G4NistManager\&.hh'\fP
.br
\fC#include 'G4Box\&.hh'\fP
.br
\fC#include 'G4Cons\&.hh'\fP
.br
\fC#include 'G4Orb\&.hh'\fP
.br
\fC#include 'G4Sphere\&.hh'\fP
.br
\fC#include 'G4Trd\&.hh'\fP
.br
\fC#include 'G4LogicalVolume\&.hh'\fP
.br
\fC#include 'G4PVPlacement\&.hh'\fP
.br
\fC#include 'G4SystemOfUnits\&.hh'\fP
.br
\fC#include 'TMXElements\&.hh'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBB1DetectorConstruction\fP class\&. 


.PP
Definition in file \fBB1DetectorConstruction\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
