.TH "B1EventAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1EventAction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <B1EventAction\&.hh>\fP
.PP
Inherits G4UserEventAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBB1EventAction\fP (\fBB1RunAction\fP *runAction)"
.br
.ti -1c
.RI "virtual void \fBBeginOfEventAction\fP (const G4Event *event)"
.br
.ti -1c
.RI "virtual void \fBEndOfEventAction\fP (const G4Event *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event action class 
.PP
Definition at line \fB41\fP of file \fBB1EventAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "B1EventAction::B1EventAction (\fBB1RunAction\fP * runAction)"

.PP
Definition at line \fB38\fP of file \fBB1EventAction\&.cc\fP\&.
.SS "B1EventAction::~B1EventAction ()\fC [virtual]\fP"

.PP
Definition at line \fB45\fP of file \fBB1EventAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void B1EventAction::BeginOfEventAction (const G4Event * event)\fC [virtual]\fP"

.PP
Definition at line \fB50\fP of file \fBB1EventAction\&.cc\fP\&.
.SS "void B1EventAction::EndOfEventAction (const G4Event * event)\fC [virtual]\fP"

.PP
Definition at line \fB56\fP of file \fBB1EventAction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
