.TH "/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/src/B1PrimaryGeneratorAction.cc" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/src/B1PrimaryGeneratorAction.cc \- Implementation of the \fBB1PrimaryGeneratorAction\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'B1PrimaryGeneratorAction\&.hh'\fP
.br
\fC#include 'G4LogicalVolumeStore\&.hh'\fP
.br
\fC#include 'G4LogicalVolume\&.hh'\fP
.br
\fC#include 'G4Box\&.hh'\fP
.br
\fC#include 'G4RunManager\&.hh'\fP
.br
\fC#include 'G4ParticleGun\&.hh'\fP
.br
\fC#include 'G4ParticleTable\&.hh'\fP
.br
\fC#include 'G4ParticleDefinition\&.hh'\fP
.br
\fC#include 'G4SystemOfUnits\&.hh'\fP
.br
\fC#include 'Randomize\&.hh'\fP
.br
\fC#include 'TMXkeff\&.hh'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBB1PrimaryGeneratorAction\fP class\&. 


.PP
Definition in file \fBB1PrimaryGeneratorAction\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
