.TH "B1PrimaryGeneratorAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1PrimaryGeneratorAction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <B1PrimaryGeneratorAction\&.hh>\fP
.PP
Inherits G4VUserPrimaryGeneratorAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBGeneratePrimaries\fP (G4Event *)"
.br
.ti -1c
.RI "const G4ParticleGun * \fBGetParticleGun\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The primary generator action class with particle gun\&.
.PP
The default kinematic is a 6 MeV gamma, randomly distribued in front of the phantom across 80% of the (X,Y) phantom size\&. 
.PP
Definition at line \fB47\fP of file \fBB1PrimaryGeneratorAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "B1PrimaryGeneratorAction::B1PrimaryGeneratorAction ()"

.PP
Definition at line \fB45\fP of file \fBB1PrimaryGeneratorAction\&.cc\fP\&.
.SS "B1PrimaryGeneratorAction::~B1PrimaryGeneratorAction ()\fC [virtual]\fP"

.PP
Definition at line \fB69\fP of file \fBB1PrimaryGeneratorAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void B1PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent)\fC [virtual]\fP"

.PP
Definition at line \fB76\fP of file \fBB1PrimaryGeneratorAction\&.cc\fP\&.
.SS "const G4ParticleGun * B1PrimaryGeneratorAction::GetParticleGun () const\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBB1PrimaryGeneratorAction\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
