.TH "B1RunAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1RunAction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <B1RunAction\&.hh>\fP
.PP
Inherits G4UserRunAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBBeginOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "virtual void \fBEndOfRunAction\fP (const G4Run *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRun\fP action class
.PP
In EndOfRunAction(), it calculates the dose in the selected volume from the energy deposit accumulated via stepping and event actions\&. The computed dose is then printed on the screen\&. 
.PP
Definition at line \fB45\fP of file \fBB1RunAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "B1RunAction::B1RunAction ()"

.PP
Definition at line \fB46\fP of file \fBB1RunAction\&.cc\fP\&.
.SS "B1RunAction::~B1RunAction ()\fC [virtual]\fP"

.PP
Definition at line \fB55\fP of file \fBB1RunAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void B1RunAction::BeginOfRunAction (const G4Run * aRun)\fC [virtual]\fP"

.PP
Definition at line \fB61\fP of file \fBB1RunAction\&.cc\fP\&.
.SS "void B1RunAction::EndOfRunAction (const G4Run * run)\fC [virtual]\fP"

.PP
Definition at line \fB70\fP of file \fBB1RunAction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
