.TH "/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/src/B1RunAction.cc" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/src/B1RunAction.cc \- Implementation of the \fBB1RunAction\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'B1RunAction\&.hh'\fP
.br
\fC#include 'B1PrimaryGeneratorAction\&.hh'\fP
.br
\fC#include 'B1DetectorConstruction\&.hh'\fP
.br
\fC#include 'G4RunManager\&.hh'\fP
.br
\fC#include 'G4Run\&.hh'\fP
.br
\fC#include 'G4AccumulableManager\&.hh'\fP
.br
\fC#include 'G4LogicalVolumeStore\&.hh'\fP
.br
\fC#include 'G4LogicalVolume\&.hh'\fP
.br
\fC#include 'G4UnitsTable\&.hh'\fP
.br
\fC#include 'G4SystemOfUnits\&.hh'\fP
.br
\fC#include 'TMXkeff\&.hh'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBB1RunAction\fP class\&. 


.PP
Definition in file \fBB1RunAction\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
