.TH "/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/include/B1SteppingAction.hh" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/include/B1SteppingAction.hh \- Definition of the \fBB1SteppingAction\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'G4UserSteppingAction\&.hh'\fP
.br
\fC#include 'globals\&.hh'\fP
.br
\fC#include 'G4Material\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBB1SteppingAction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBB1SteppingAction\fP class\&. 


.PP
Definition in file \fBB1SteppingAction\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
