.TH "B1SteppingAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1SteppingAction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <B1SteppingAction\&.hh>\fP
.PP
Inherits G4UserSteppingAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBB1SteppingAction\fP (\fBB1EventAction\fP *eventAction)"
.br
.ti -1c
.RI "virtual void \fBUserSteppingAction\fP (const G4Step *)"
.br
.ti -1c
.RI "G4double \fBGetMaterialXS\fP (const G4Step *, std::string)"
.br
.ti -1c
.RI "G4double \fBGetMaterialFissionCrossSection\fP (const G4Step *)"
.br
.ti -1c
.RI "G4double \fBGetMaterialElasticCrossSection\fP (const G4Step *)"
.br
.ti -1c
.RI "G4double \fBGetMaterialInelastCrossSection\fP (const G4Step *)"
.br
.ti -1c
.RI "G4double \fBGetMaterialCaptureCrossSection\fP (const G4Step *)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP (G4double) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stepping action class 
.PP
Definition at line \fB45\fP of file \fBB1SteppingAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "B1SteppingAction::B1SteppingAction (\fBB1EventAction\fP * eventAction)"

.PP
Definition at line \fB45\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "B1SteppingAction::~B1SteppingAction ()\fC [virtual]\fP"

.PP
Definition at line \fB53\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4double B1SteppingAction::GetMaterialCaptureCrossSection (const G4Step * theStep)"

.PP
Definition at line \fB393\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "G4double B1SteppingAction::GetMaterialElasticCrossSection (const G4Step * theStep)"

.PP
Definition at line \fB260\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "G4double B1SteppingAction::GetMaterialFissionCrossSection (const G4Step * theStep)"

.PP
Definition at line \fB193\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "G4double B1SteppingAction::GetMaterialInelastCrossSection (const G4Step * theStep)"

.PP
Definition at line \fB325\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "G4double B1SteppingAction::GetMaterialXS (const G4Step * theStep, std::string XSreaction)"

.PP
Definition at line \fB178\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "G4double B1SteppingAction::GetNu (G4double en) const"

.PP
Definition at line \fB126\fP of file \fBB1SteppingAction\&.cc\fP\&.
.SS "void B1SteppingAction::UserSteppingAction (const G4Step * theStep)\fC [virtual]\fP"

.PP
Definition at line \fB60\fP of file \fBB1SteppingAction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
