.TH "Burnup" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Burnup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBurnup\fP (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > >, \fBTMXInputParameters\fP *, int, double, double injE=0\&.)"
.br
.RI "\fBBurnup::Burnup\fP\&. "
.ti -1c
.RI "\fB~Burnup\fP ()"
.br
.RI "\fBBurnup::~Burnup\fP\&. "
.ti -1c
.RI "void \fBprintMaterial\fP (\fBTMXMaterial\fP *)"
.br
.RI "\fBBurnup::printMaterial\fP\&. "
.ti -1c
.RI "void \fBwriteMaterials\fP ()"
.br
.RI "\fBBurnup::writeMaterials\fP\&. "
.ti -1c
.RI "double \fBgetTimePassed\fP ()"
.br
.RI "\fBBurnup::getTimePassed\fP\&. "
.ti -1c
.RI "\fBBurnup\fP (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > >, \fBTMXInputParameters\fP *, int, double, double injE=0\&.)"
.br
.ti -1c
.RI "void \fBprintMaterial\fP (\fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "void \fBwriteMaterials\fP ()"
.br
.ti -1c
.RI "double \fBgetTimePassed\fP ()"
.br
.ti -1c
.RI "\fBBurnup\fP (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > >, \fBTMXInputParameters\fP *, int, double, double injE=0\&.)"
.br
.ti -1c
.RI "void \fBprintMaterial\fP (\fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "void \fBwriteMaterials\fP ()"
.br
.ti -1c
.RI "double \fBgetTimePassed\fP ()"
.br
.ti -1c
.RI "\fBBurnup\fP (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > >, \fBTMXInputParameters\fP *, int, double, double injE=0\&.)"
.br
.ti -1c
.RI "void \fBprintMaterial\fP (\fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "void \fBwriteMaterials\fP ()"
.br
.ti -1c
.RI "double \fBgetTimePassed\fP ()"
.br
.ti -1c
.RI "\fBBurnup\fP (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > >, \fBTMXInputParameters\fP *, int, double, double Edep, double injE=0\&., std::vector< double >=std::vector< double >())"
.br
.RI "\fBBurnup::Burnup\fP\&. "
.ti -1c
.RI "void \fBprintMaterial\fP (\fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "void \fBwriteMaterials\fP ()"
.br
.ti -1c
.RI "double \fBgetTimePassed\fP ()"
.br
.ti -1c
.RI "double \fBgetNewBeamIntensity\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBBurnup\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Burnup::Burnup (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > sourceTerm, \fBTMXInputParameters\fP * p, int stepNumber, double timePassed, double injE = \fC0\&.\fP)"

.PP
\fBBurnup::Burnup\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIsourceTerm\fP 
.br
\fInStep\fP 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBBurnup\&.cc\fP\&.
.SS "Burnup::~Burnup ()"

.PP
\fBBurnup::~Burnup\fP\&. 
.PP
Definition at line \fB101\fP of file \fBBurnup\&.cc\fP\&.
.SS "Burnup::Burnup (std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > sourceTerm, \fBTMXInputParameters\fP * p, int stepNumber, double timePassed, double Edep, double injE = \fC0\&.\fP, std::vector< double > beamIntensity = \fCstd::vector<double>()\fP)"

.PP
\fBBurnup::Burnup\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIsourceTerm\fP 
.br
\fInStep\fP 
.br
\fIEdep\fP : Total energy deposited in the system for the whole run 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBBurnup\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double Burnup::getNewBeamIntensity () const"

.PP
Definition at line \fB189\fP of file \fBBurnup\&.cc\fP\&.
.SS "double Burnup::getTimePassed ()"

.PP
\fBBurnup::getTimePassed\fP\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB93\fP of file \fBBurnup\&.cc\fP\&.
.SS "void Burnup::printMaterial (\fBTMXMaterial\fP * mat)"

.PP
\fBBurnup::printMaterial\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fImat\fP 
.RE
.PP

.PP
Definition at line \fB505\fP of file \fBBurnup\&.cc\fP\&.
.SS "void Burnup::writeMaterials ()"

.PP
\fBBurnup::writeMaterials\fP\&. 
.PP
Definition at line \fB421\fP of file \fBBurnup\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
