.TH "CriticalThermalPower" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CriticalThermalPower \- Description of the \fBCriticalThermalPower\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CriticalThermalPower\&.hh>\fP
.PP
Inherits \fBTMXAbstractScoringAccumulable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCriticalThermalPower\fP (\fBTMXInputParameters\fP *parameter, std::string name)"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBDefinet0\fP (const G4Step *theStep, int NeutronGeneration)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Description of the \fBCriticalThermalPower\fP class\&. 
.PP
Definition at line \fB18\fP of file \fBCriticalThermalPower\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CriticalThermalPower::CriticalThermalPower (\fBTMXInputParameters\fP * parameter, std::string name)"

.PP
Definition at line \fB5\fP of file \fBCriticalThermalPower\&.cc\fP\&.
.SS "CriticalThermalPower::~CriticalThermalPower ()"

.PP
Definition at line \fB11\fP of file \fBCriticalThermalPower\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CriticalThermalPower::Definet0 (const G4Step * theStep, int NeutronGeneration)"

.PP
Definition at line \fB32\fP of file \fBCriticalThermalPower\&.cc\fP\&.
.SS "void CriticalThermalPower::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.PP
Definition at line \fB69\fP of file \fBCriticalThermalPower\&.cc\fP\&.
.SS "void CriticalThermalPower::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.PP
Definition at line \fB39\fP of file \fBCriticalThermalPower\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
