.TH "DefineMaterials" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefineMaterials \- Implementation of the \fBDefineMaterials\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DefineMaterials\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefineMaterials\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.RI "Implementation of the \fBDefineMaterials\fP class\&. "
.ti -1c
.RI "std::vector< std::vector< \fBTMXMaterial\fP * > > * \fBGetFuelBurnupMWd_kgU\fP (double)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetUniverseMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAirMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetConcreteMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluTempFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldLeadMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldBiMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAlF3Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladSsMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAlMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAlAlloyMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAbsorMaterial\fP ()"
.br
.ti -1c
.RI "std::vector< \fBTMXMaterial\fP * > \fBGetFuelReflMaterial4\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetLeadRigMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetReactorMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetVacuum\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThO2_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm242_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm243_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu238_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetMixCm_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThPuO2_Material\fP ()"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< std::vector< \fBTMXMaterial\fP * > > > * \fBGetMapFuelBurnupMWd_kgU_material\fP ()"
.br
.ti -1c
.RI "\fBDefineMaterials\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "std::vector< std::vector< \fBTMXMaterial\fP * > > * \fBGetFuelBurnupMWd_kgU\fP (double)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetUniverseMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAirMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetConcreteMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluTempFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldLeadMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldBiMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAlF3Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladSsMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAlMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAlAlloyMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAbsorMaterial\fP ()"
.br
.ti -1c
.RI "std::vector< \fBTMXMaterial\fP * > \fBGetFuelReflMaterial4\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetLeadRigMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetReactorMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetVacuum\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThO2_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm242_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm243_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu238_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetMixCm_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThPuO2_Material\fP ()"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< std::vector< \fBTMXMaterial\fP * > > > * \fBGetMapFuelBurnupMWd_kgU_material\fP ()"
.br
.ti -1c
.RI "\fBDefineMaterials\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "std::vector< std::vector< \fBTMXMaterial\fP * > > * \fBGetFuelBurnupMWd_kgU\fP (double)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetUniverseMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAirMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetConcreteMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluTempFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldLeadMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldBiMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAlF3Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladSsMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAlMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAlAlloyMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAbsorMaterial\fP ()"
.br
.ti -1c
.RI "std::vector< \fBTMXMaterial\fP * > \fBGetFuelReflMaterial4\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetLeadRigMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetReactorMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetVacuum\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThO2_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm242_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm243_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu238_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetMixCm_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThPuO2_Material\fP ()"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< std::vector< \fBTMXMaterial\fP * > > > * \fBGetMapFuelBurnupMWd_kgU_material\fP ()"
.br
.ti -1c
.RI "\fBDefineMaterials\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "std::vector< std::vector< \fBTMXMaterial\fP * > > * \fBGetFuelBurnupMWd_kgU\fP (double)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetUniverseMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAirMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetConcreteMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluTempFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldLeadMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldBiMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAlF3Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladSsMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAlMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAlAlloyMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAbsorMaterial\fP ()"
.br
.ti -1c
.RI "std::vector< \fBTMXMaterial\fP * > \fBGetFuelReflMaterial4\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetLeadRigMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetReactorMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetVacuum\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThO2_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm242_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm243_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu238_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetMixCm_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThPuO2_Material\fP ()"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< std::vector< \fBTMXMaterial\fP * > > > * \fBGetMapFuelBurnupMWd_kgU_material\fP ()"
.br
.ti -1c
.RI "\fBDefineMaterials\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "std::vector< std::vector< \fBTMXMaterial\fP * > > * \fBGetFuelBurnupMWd_kgU\fP (double)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetUniverseMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAirMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetConcreteMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluTempFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAluMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldLeadMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldBiMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetWorldAlF3Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetCladSsMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAlMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAlAlloyMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetFuelAbsorMaterial\fP ()"
.br
.ti -1c
.RI "std::vector< \fBTMXMaterial\fP * > \fBGetFuelReflMaterial4\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetLeadRigMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetReactorMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetVacuum\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThO2_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm242_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetAm243_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu238_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetPu241_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetMixCm_Material\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBGetThPuO2_Material\fP ()"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< std::vector< \fBTMXMaterial\fP * > > > * \fBGetMapFuelBurnupMWd_kgU_material\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the \fBDefineMaterials\fP class\&. 
.PP
Definition at line \fB50\fP of file \fBDefineMaterials\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DefineMaterials::DefineMaterials (G4int, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBDefineMaterials\fP class\&. 
.PP
Definition at line \fB53\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "DefineMaterials::~DefineMaterials ()\fC [virtual]\fP"

.PP
Definition at line \fB58\fP of file \fBDefineMaterials\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTMXMaterial\fP * DefineMaterials::GetAirMaterial ()"

.PP
Definition at line \fB1011\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetAlAlloyMaterial ()"

.PP
Definition at line \fB1059\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetAm241_Material ()"

.PP
Definition at line \fB1095\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetAm242_Material ()"

.PP
Definition at line \fB1099\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetAm243_Material ()"

.PP
Definition at line \fB1103\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetCladAluMaterial ()"

.PP
Definition at line \fB1027\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetCladSsMaterial ()"

.PP
Definition at line \fB1047\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetConcreteMaterial ()"

.PP
Definition at line \fB1015\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetFuelAbsorMaterial ()"

.PP
Definition at line \fB1063\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetFuelAlMaterial ()"

.PP
Definition at line \fB1055\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "std::vector< std::vector< \fBTMXMaterial\fP * > > * DefineMaterials::GetFuelBurnupMWd_kgU (double burnup_MWd_kgU)"

.PP
Definition at line \fB135\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetFuelCladAluMaterial ()"

.PP
Definition at line \fB1023\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetFuelCladAluTempFuelMaterial ()"

.PP
Definition at line \fB1019\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "std::vector< \fBTMXMaterial\fP * > DefineMaterials::GetFuelReflMaterial4 ()"

.PP
Definition at line \fB1067\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetFuelWaterMaterial ()"

.PP
Definition at line \fB1051\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetLeadRigMaterial ()"

.PP
Definition at line \fB1071\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "std::unordered_map< std::string, std::vector< std::vector< \fBTMXMaterial\fP * > > > * DefineMaterials::GetMapFuelBurnupMWd_kgU_material ()"

.PP
Definition at line \fB1115\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetMixCm_Material ()"

.PP
Definition at line \fB1087\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetPu238_Material ()"

.PP
Definition at line \fB1107\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetPu241_Material ()"

.PP
Definition at line \fB1111\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetReactorMaterial ()"

.PP
Definition at line \fB1075\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetThO2_Material ()"

.PP
Definition at line \fB1083\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetThPuO2_Material ()"

.PP
Definition at line \fB1091\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetUniverseMaterial ()"

.PP
Definition at line \fB1003\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetVacuum ()"

.PP
Definition at line \fB1079\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetWorldAlF3Material ()"

.PP
Definition at line \fB1043\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetWorldAluMaterial ()"

.PP
Definition at line \fB1031\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetWorldBiMaterial ()"

.PP
Definition at line \fB1039\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetWorldLeadMaterial ()"

.PP
Definition at line \fB1035\fP of file \fBDefineMaterials\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * DefineMaterials::GetWorldWaterMaterial ()"

.PP
Definition at line \fB1007\fP of file \fBDefineMaterials\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
