.TH "DetectorConstruction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetectorConstruction
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, and G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetectorConstruction\fP (G4int int_Option, \fBTMXInputParameters\fP &parameter, G4double &AssemblyLength)"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4Material * \fBGetTargetMaterial\fP ()"
.br
.ti -1c
.RI "void \fBSetWorldMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetRadius\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetDiffusorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetBreederGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetReflectorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetShieldGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetWorldGap\fP (G4double val)"
.br
.ti -1c
.RI "G4VSolid * \fBGetTargetTubeSolid\fP () const"
.br
.ti -1c
.RI "G4double \fBGeth0\fP () const"
.br
.ti -1c
.RI "G4ThreeVector \fBGetTargetPosition\fP () const"
.br
.ti -1c
.RI "G4double \fBGetTargetZdistanceToBottom\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelInnerRadius\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelOuterRadius\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNreplicate\fP () const"
.br
.ti -1c
.RI "G4Material * \fBGetFuelDriverMaterial\fP () const"
.br
.ti -1c
.RI "G4double \fBRod_radius\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4double \fBRod_theta\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4int \fBRod_subLayer\fP (G4double subAssembly_r) const"
.br
.ti -1c
.RI "G4int \fBGetTotalCopyNumberFuelRods\fP () const"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP * \fBgetGeomSVBR\fP () const"
.br
.ti -1c
.RI "\fBDetectorConstruction\fP (G4int int_Option, \fBTMXInputParameters\fP &parameter, G4double &AssemblyLength)"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4Material * \fBGetTargetMaterial\fP ()"
.br
.ti -1c
.RI "void \fBSetWorldMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetRadius\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetDiffusorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetBreederGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetReflectorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetShieldGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetWorldGap\fP (G4double val)"
.br
.ti -1c
.RI "G4VSolid * \fBGetTargetTubeSolid\fP () const"
.br
.ti -1c
.RI "G4double \fBGeth0\fP () const"
.br
.ti -1c
.RI "G4ThreeVector \fBGetTargetPosition\fP () const"
.br
.ti -1c
.RI "G4double \fBGetTargetZdistanceToBottom\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelInnerRadius\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelOuterRadius\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNreplicate\fP () const"
.br
.ti -1c
.RI "G4Material * \fBGetFuelDriverMaterial\fP () const"
.br
.ti -1c
.RI "G4double \fBRod_radius\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4double \fBRod_theta\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4int \fBRod_subLayer\fP (G4double subAssembly_r) const"
.br
.ti -1c
.RI "G4int \fBGetTotalCopyNumberFuelRods\fP () const"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP * \fBgetGeomSVBR\fP () const"
.br
.ti -1c
.RI "\fBDetectorConstruction\fP (G4int int_Option, \fBTMXInputParameters\fP &parameter, G4double &AssemblyLength)"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4Material * \fBGetTargetMaterial\fP ()"
.br
.ti -1c
.RI "void \fBSetWorldMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetRadius\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetDiffusorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetBreederGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetReflectorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetShieldGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetWorldGap\fP (G4double val)"
.br
.ti -1c
.RI "G4VSolid * \fBGetTargetTubeSolid\fP () const"
.br
.ti -1c
.RI "G4double \fBGeth0\fP () const"
.br
.ti -1c
.RI "G4ThreeVector \fBGetTargetPosition\fP () const"
.br
.ti -1c
.RI "G4double \fBGetTargetZdistanceToBottom\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelInnerRadius\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelOuterRadius\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNreplicate\fP () const"
.br
.ti -1c
.RI "G4Material * \fBGetFuelDriverMaterial\fP () const"
.br
.ti -1c
.RI "G4double \fBRod_radius\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4double \fBRod_theta\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4int \fBRod_subLayer\fP (G4double subAssembly_r) const"
.br
.ti -1c
.RI "G4int \fBGetTotalCopyNumberFuelRods\fP () const"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP * \fBgetGeomSVBR\fP () const"
.br
.ti -1c
.RI "\fBDetectorConstruction\fP (G4int int_Option, \fBTMXInputParameters\fP &parameter, G4double &AssemblyLength)"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4Material * \fBGetTargetMaterial\fP ()"
.br
.ti -1c
.RI "void \fBSetWorldMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetRadius\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetDiffusorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetBreederGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetReflectorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetShieldGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetWorldGap\fP (G4double val)"
.br
.ti -1c
.RI "G4VSolid * \fBGetTargetTubeSolid\fP () const"
.br
.ti -1c
.RI "G4double \fBGeth0\fP () const"
.br
.ti -1c
.RI "G4ThreeVector \fBGetTargetPosition\fP () const"
.br
.ti -1c
.RI "G4double \fBGetTargetZdistanceToBottom\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelInnerRadius\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelOuterRadius\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNreplicate\fP () const"
.br
.ti -1c
.RI "G4Material * \fBGetFuelDriverMaterial\fP () const"
.br
.ti -1c
.RI "G4double \fBRod_radius\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4double \fBRod_theta\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4int \fBRod_subLayer\fP (G4double subAssembly_r) const"
.br
.ti -1c
.RI "G4int \fBGetTotalCopyNumberFuelRods\fP () const"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP * \fBgetGeomSVBR\fP () const"
.br
.ti -1c
.RI "\fBDetectorConstruction\fP (G4int int_Option, \fBTMXInputParameters\fP &parameter, G4double &AssemblyLength)"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4Material * \fBGetTargetMaterial\fP ()"
.br
.ti -1c
.RI "void \fBSetWorldMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetMaterial\fP (const G4String &)"
.br
.ti -1c
.RI "void \fBSetTargetRadius\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetDiffusorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetBreederGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetReflectorGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetShieldGap\fP (G4double val)"
.br
.ti -1c
.RI "void \fBSetWorldGap\fP (G4double val)"
.br
.ti -1c
.RI "G4VSolid * \fBGetTargetTubeSolid\fP () const"
.br
.ti -1c
.RI "G4double \fBGeth0\fP () const"
.br
.ti -1c
.RI "G4ThreeVector \fBGetTargetPosition\fP () const"
.br
.ti -1c
.RI "G4double \fBGetTargetZdistanceToBottom\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelInnerRadius\fP () const"
.br
.ti -1c
.RI "G4double \fBGetFuelOuterRadius\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNreplicate\fP () const"
.br
.ti -1c
.RI "G4Material * \fBGetFuelDriverMaterial\fP () const"
.br
.ti -1c
.RI "G4double \fBRod_radius\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4double \fBRod_theta\fP (G4int copyNo) const"
.br
.ti -1c
.RI "G4int \fBRod_subLayer\fP (G4double subAssembly_r) const"
.br
.ti -1c
.RI "G4int \fBGetTotalCopyNumberFuelRods\fP () const"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP * \fBgetGeomSVBR\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DetectorConstruction::DetectorConstruction (G4int int_Option, \fBTMXInputParameters\fP & parameter, G4double & AssemblyLength)"

.PP
Definition at line \fB95\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SS "DetectorConstruction::~DetectorConstruction ()\fC [virtual]\fP"

.PP
Definition at line \fB272\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * DetectorConstruction::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB281\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SS "G4Material * DetectorConstruction::GetFuelDriverMaterial () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetFuelDriverMaterial () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetFuelDriverMaterial () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetFuelDriverMaterial () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetFuelDriverMaterial () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelInnerRadius () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelInnerRadius () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelInnerRadius () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelInnerRadius () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelInnerRadius () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelOuterRadius () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelOuterRadius () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelOuterRadius () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelOuterRadius () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetFuelOuterRadius () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "\fBGeomEAP80Simplified\fP * DetectorConstruction::getGeomSVBR () const"

.PP
Definition at line \fB521\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SS "G4double DetectorConstruction::Geth0 () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::Geth0 () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::Geth0 () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::Geth0 () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::Geth0 () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4int DetectorConstruction::GetNreplicate () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4int DetectorConstruction::GetNreplicate () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4int DetectorConstruction::GetNreplicate () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4int DetectorConstruction::GetNreplicate () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4int DetectorConstruction::GetNreplicate () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetTargetMaterial ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetTargetMaterial ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetTargetMaterial ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetTargetMaterial ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4Material * DetectorConstruction::GetTargetMaterial ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4ThreeVector DetectorConstruction::GetTargetPosition () const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4ThreeVector DetectorConstruction::GetTargetPosition () const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4ThreeVector DetectorConstruction::GetTargetPosition () const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4ThreeVector DetectorConstruction::GetTargetPosition () const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4ThreeVector DetectorConstruction::GetTargetPosition () const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4VSolid * DetectorConstruction::GetTargetTubeSolid () const\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4VSolid * DetectorConstruction::GetTargetTubeSolid () const\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4VSolid * DetectorConstruction::GetTargetTubeSolid () const\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4VSolid * DetectorConstruction::GetTargetTubeSolid () const\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4VSolid * DetectorConstruction::GetTargetTubeSolid () const\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetTargetZdistanceToBottom () const\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetTargetZdistanceToBottom () const\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetTargetZdistanceToBottom () const\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetTargetZdistanceToBottom () const\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4double DetectorConstruction::GetTargetZdistanceToBottom () const\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBDetectorConstruction\&.hh\fP\&.
.SS "G4int DetectorConstruction::GetTotalCopyNumberFuelRods () const"

.PP
Definition at line \fB4215\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SS "G4double DetectorConstruction::Rod_radius (G4int copyNo) const"

.PP
Definition at line \fB4186\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SS "G4int DetectorConstruction::Rod_subLayer (G4double subAssembly_r) const"

.PP
Definition at line \fB4201\fP of file \fBDetectorConstruction\&.cc\fP\&.
.SS "G4double DetectorConstruction::Rod_theta (G4int copyNo) const"

.PP
Definition at line \fB4194\fP of file \fBDetectorConstruction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
