.TH "EventAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4UserEventAction, G4UserEventAction, G4UserEventAction, G4UserEventAction, and G4UserEventAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventAction\fP (\fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "virtual void \fBBeginOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "virtual void \fBEndOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "G4long \fBGetNevt\fP ()"
.br
.ti -1c
.RI "void \fBSetNf\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetN0Abs\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddN0fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddInelasticN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetFissionN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNbNeutronPerGeneration\fP (G4int generation, G4long val)"
.br
.ti -1c
.RI "void \fBSetnu\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsU5\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNcapU8\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsTot\fP (G4double val)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP ()"
.br
.ti -1c
.RI "void \fBAddFission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddEdep\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEperfission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddTransmuteElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAddSourceElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAdd_keff_collision\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_analogAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_implicitAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_trackLength\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_NsourceNeutronPerEvent\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP () const"
.br
.ti -1c
.RI "void \fBAddEdep_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEkin_sec_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNtot_fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNprimaryEscape\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP (double en) const"
.br
.ti -1c
.RI "void \fBAddWeight\fP (G4double X=0, G4double Y=0, G4double Z=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "\fBEventAction\fP (\fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "virtual void \fBBeginOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "virtual void \fBEndOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "G4long \fBGetNevt\fP ()"
.br
.ti -1c
.RI "void \fBSetNf\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetN0Abs\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddN0fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddInelasticN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetFissionN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNbNeutronPerGeneration\fP (G4int generation, G4long val)"
.br
.ti -1c
.RI "void \fBSetnu\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsU5\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNcapU8\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsTot\fP (G4double val)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP ()"
.br
.ti -1c
.RI "void \fBAddFission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddEdep\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEperfission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddTransmuteElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAddSourceElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAdd_keff_collision\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_analogAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_implicitAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_trackLength\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_NsourceNeutronPerEvent\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP () const"
.br
.ti -1c
.RI "void \fBAddEdep_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEkin_sec_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNtot_fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNprimaryEscape\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP (double en) const"
.br
.ti -1c
.RI "void \fBAddWeight\fP (G4double X=0, G4double Y=0, G4double Z=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "\fBEventAction\fP (\fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "virtual void \fBBeginOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "virtual void \fBEndOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "G4long \fBGetNevt\fP ()"
.br
.ti -1c
.RI "void \fBSetNf\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetN0Abs\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddN0fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddInelasticN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetFissionN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNbNeutronPerGeneration\fP (G4int generation, G4long val)"
.br
.ti -1c
.RI "void \fBSetnu\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsU5\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNcapU8\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsTot\fP (G4double val)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP ()"
.br
.ti -1c
.RI "void \fBAddFission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddEdep\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEperfission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddTransmuteElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAddSourceElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAdd_keff_collision\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_analogAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_implicitAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_trackLength\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_NsourceNeutronPerEvent\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP () const"
.br
.ti -1c
.RI "void \fBAddEdep_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEkin_sec_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNtot_fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNprimaryEscape\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP (double en) const"
.br
.ti -1c
.RI "void \fBAddWeight\fP (G4double X=0, G4double Y=0, G4double Z=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "\fBEventAction\fP (\fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "virtual void \fBBeginOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "virtual void \fBEndOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "G4long \fBGetNevt\fP ()"
.br
.ti -1c
.RI "void \fBSetNf\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetN0Abs\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddN0fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddInelasticN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetFissionN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNbNeutronPerGeneration\fP (G4int generation, G4long val)"
.br
.ti -1c
.RI "void \fBSetnu\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsU5\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNcapU8\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsTot\fP (G4double val)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP ()"
.br
.ti -1c
.RI "void \fBAddFission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddEdep\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEperfission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddTransmuteElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAddSourceElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAdd_keff_collision\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_analogAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_implicitAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_trackLength\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_NsourceNeutronPerEvent\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP () const"
.br
.ti -1c
.RI "void \fBAddEdep_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEkin_sec_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNtot_fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNprimaryEscape\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP (double en) const"
.br
.ti -1c
.RI "void \fBAddWeight\fP (G4double X=0, G4double Y=0, G4double Z=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "\fBEventAction\fP (\fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "virtual void \fBBeginOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "virtual void \fBEndOfEventAction\fP (const G4Event *)"
.br
.ti -1c
.RI "G4long \fBGetNevt\fP ()"
.br
.ti -1c
.RI "\fBTMXNeutronicParam\fP * \fBGetNeutronicParameters\fP ()"
.br
.ti -1c
.RI "void \fBSetNf\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetN0Abs\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddN0fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddInelasticN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBSetFissionN\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNbNeutronPerGeneration\fP (G4int generation, G4long val)"
.br
.ti -1c
.RI "void \fBSetnu\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsU5\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNcapU8\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNabsTot\fP (G4double val)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP ()"
.br
.ti -1c
.RI "void \fBAddFission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddEdep\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEperfission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddTransmuteElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAddSourceElement\fP (\fBTMXBatemanDecay::TransmutedElement\fP el)"
.br
.ti -1c
.RI "void \fBAdd_keff_collision\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_analogAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_implicitAbs\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_keff_trackLength\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAdd_NsourceNeutronPerEvent\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP () const"
.br
.ti -1c
.RI "void \fBAddEdep_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddEkin_sec_fission\fP (G4double val)"
.br
.ti -1c
.RI "void \fBAddNtot_fission\fP (G4long val)"
.br
.ti -1c
.RI "void \fBAddNprimaryEscape\fP (G4long val)"
.br
.ti -1c
.RI "G4double \fBGetNu\fP (double en) const"
.br
.ti -1c
.RI "void \fBAddWeight\fP (G4double X=0, G4double Y=0, G4double Z=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP *parameter, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP &mergedOutput, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBEventAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EventAction::EventAction (\fBTMXInputParameters\fP * parameter, \fBTMXRandomDistribution3D\fP & RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP & mergedOutput, \fBTMXBatemanDecay\fP & batemanDecay)"

.PP
Definition at line \fB71\fP of file \fBEventAction\&.cc\fP\&.
.SS "EventAction::~EventAction ()\fC [virtual]\fP"

.PP
Definition at line \fB77\fP of file \fBEventAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void EventAction::Add_keff_analogAbs (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB172\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::Add_keff_collision (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB171\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::Add_keff_implicitAbs (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB173\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::Add_keff_trackLength (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB174\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::Add_NsourceNeutronPerEvent (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB175\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddEdep (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB166\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddEdep_fission (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB177\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddEkin_sec_fission (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB178\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddEperfission (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB167\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddFission (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB165\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddInelasticN (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB152\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddN0fission (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB150\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddNabsTot (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB163\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddNabsU5 (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB161\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddNbNeutronPerGeneration (G4int generation, G4long val)\fC [inline]\fP"

.PP
Definition at line \fB153\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddNcapU8 (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB162\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddNprimaryEscape (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB181\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddNtot_fission (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB179\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddSourceElement (\fBTMXBatemanDecay::TransmutedElement\fP el)\fC [inline]\fP"

.PP
Definition at line \fB169\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddTransmuteElement (\fBTMXBatemanDecay::TransmutedElement\fP el)\fC [inline]\fP"

.PP
Definition at line \fB168\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::AddWeight (G4double X = \fC0\fP, G4double Y = \fC0\fP, G4double Z = \fC0\fP)"

.PP
Definition at line \fB166\fP of file \fBEventAction\&.cc\fP\&.
.SS "void EventAction::BeginOfEventAction (const G4Event *)\fC [virtual]\fP"

.PP
Definition at line \fB87\fP of file \fBEventAction\&.cc\fP\&.
.SS "void EventAction::EndOfEventAction (const G4Event *)\fC [virtual]\fP"

.PP
Definition at line \fB130\fP of file \fBEventAction\&.cc\fP\&.
.SS "\fBTMXNeutronicParam\fP * EventAction::GetNeutronicParameters ()\fC [inline]\fP"

.PP
Definition at line \fB46\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4long EventAction::GetNevt ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4long EventAction::GetNevt ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4long EventAction::GetNevt ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4long EventAction::GetNevt ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4long EventAction::GetNevt ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4double EventAction::GetNu () const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4double EventAction::GetNu () const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4double EventAction::GetNu () const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4double EventAction::GetNu () const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4double EventAction::GetNu () const\fC [inline]\fP"

.PP
Definition at line \fB70\fP of file \fBEventAction\&.hh\fP\&.
.SS "G4int EventAction::GetRunNumber ()\fC [inline]\fP"

.PP
Definition at line \fB164\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::Initialize (G4int RunNumber, \fBTMXInputParameters\fP * parameter, \fBTMXRandomDistribution3D\fP & RadiusAnglesHeight, \fBTMXMergeThreadsResults\fP & mergedOutput, \fBTMXBatemanDecay\fP & batemanDecay)"

.PP
Definition at line \fB177\fP of file \fBEventAction\&.cc\fP\&.
.SS "void EventAction::SetFissionN (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB151\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::SetN0Abs (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB149\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::SetNf (G4long val)\fC [inline]\fP"

.PP
Definition at line \fB148\fP of file \fBEventAction\&.hh\fP\&.
.SS "void EventAction::Setnu (G4double val)\fC [inline]\fP"

.PP
Definition at line \fB160\fP of file \fBEventAction\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
