.TH "/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/exampleB1.cc" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Transmutex/Simulation/ADS_SimulationCode/testKeff_v0.1/exampleB1.cc \- Main program of the B1 example\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'B1DetectorConstruction\&.hh'\fP
.br
\fC#include 'B1ActionInitialization\&.hh'\fP
.br
\fC#include 'G4RunManager\&.hh'\fP
.br
\fC#include 'G4UImanager\&.hh'\fP
.br
\fC#include 'QBBC\&.hh'\fP
.br
\fC#include 'QGSP_BIC_HP\&.hh'\fP
.br
\fC#include 'G4VisExecutive\&.hh'\fP
.br
\fC#include 'G4UIExecutive\&.hh'\fP
.br
\fC#include 'Randomize\&.hh'\fP
.br
\fC#include 'G4ThermalNeutrons\&.hh'\fP
.br
\fC#include 'G4PhysListFactory\&.hh'\fP
.br
\fC#include 'TMXkeff\&.hh'\fP
.br
\fC#include 'PhysicsList\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main program of the B1 example\&. 


.PP
Definition in file \fBexampleB1\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB56\fP of file \fBexampleB1\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
