.TH "FFyield" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFyield
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fByield\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFFyield\fP (int iza, double awr, int le)"
.br
.ti -1c
.RI "int \fBGetIZA\fP () const"
.br
.ti -1c
.RI "double \fBGetAWR\fP () const"
.br
.ti -1c
.RI "void \fBSetIZA\fP (int iza)"
.br
.ti -1c
.RI "void \fBSetAWR\fP (double awr)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBfAWR\fP"
.br
.ti -1c
.RI "int \fBfIZA\fP"
.br
.ti -1c
.RI "int \fBfLE\fP"
.br
.ti -1c
.RI "vector< int > \fBfInt\fP"
.br
.ti -1c
.RI "vector< vector< \fByield\fP > > \fBfYI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBxendfb\&.C\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FFyield::FFyield ()\fC [inline]\fP"

.PP
Definition at line \fB50\fP of file \fBxendfb\&.C\fP\&.
.SS "FFyield::FFyield (int iza, double awr, int le)\fC [inline]\fP"

.PP
Definition at line \fB52\fP of file \fBxendfb\&.C\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double FFyield::GetAWR () const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBxendfb\&.C\fP\&.
.SS "int FFyield::GetIZA () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBxendfb\&.C\fP\&.
.SS "void FFyield::SetAWR (double awr)\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBxendfb\&.C\fP\&.
.SS "void FFyield::SetIZA (int iza)\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBxendfb\&.C\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FFyield::fAWR\fC [protected]\fP"

.PP
Definition at line \fB66\fP of file \fBxendfb\&.C\fP\&.
.SS "vector<int> FFyield::fInt\fC [protected]\fP"

.PP
Definition at line \fB69\fP of file \fBxendfb\&.C\fP\&.
.SS "int FFyield::fIZA\fC [protected]\fP"

.PP
Definition at line \fB67\fP of file \fBxendfb\&.C\fP\&.
.SS "int FFyield::fLE\fC [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBxendfb\&.C\fP\&.
.SS "vector<vector<\fByield\fP> > FFyield::fYI\fC [protected]\fP"

.PP
Definition at line \fB70\fP of file \fBxendfb\&.C\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
