.TH "FFyield::yield" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFyield::yield
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfIZA\fP"
.br
.ti -1c
.RI "double \fBfY\fP"
.br
.ti -1c
.RI "double \fBfDY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB61\fP of file \fBxendfb\&.C\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FFyield::yield::fDY"

.PP
Definition at line \fB64\fP of file \fBxendfb\&.C\fP\&.
.SS "int FFyield::yield::fIZA"

.PP
Definition at line \fB62\fP of file \fBxendfb\&.C\fP\&.
.SS "double FFyield::yield::fY"

.PP
Definition at line \fB63\fP of file \fBxendfb\&.C\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
