.TH "FissionSite" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FissionSite
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "G4ThreeVector \fBposition\fP"
.br
.ti -1c
.RI "G4ThreeVector \fBdirection\fP"
.br
.ti -1c
.RI "double \fBenergy\fP"
.br
.ti -1c
.RI "G4ThreeVector \fBmomentum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBTMXFissionSourceBank\&.hh\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "G4ThreeVector FissionSite::direction"

.PP
Definition at line \fB45\fP of file \fBTMXFissionSourceBank\&.hh\fP\&.
.SS "double FissionSite::energy"

.PP
Definition at line \fB46\fP of file \fBTMXFissionSourceBank\&.hh\fP\&.
.SS "G4ThreeVector FissionSite::momentum"

.PP
Definition at line \fB47\fP of file \fBTMXFissionSourceBank\&.hh\fP\&.
.SS "G4ThreeVector FissionSite::position"

.PP
Definition at line \fB44\fP of file \fBTMXFissionSourceBank\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
