.TH "/Users/Transmutex/Simulation/ADS_SimulationCode/G4-NeutronTransport/include/GammaNuclearPhysics.hh" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Transmutex/Simulation/ADS_SimulationCode/G4-NeutronTransport/include/GammaNuclearPhysics.hh \- Definition of the \fBGammaNuclearPhysics\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'globals\&.hh'\fP
.br
\fC#include 'G4VPhysicsConstructor\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGammaNuclearPhysics\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBGammaNuclearPhysics\fP class\&. 


.PP
Definition in file \fBGammaNuclearPhysics\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
