.TH "GeomEAP80Simplified" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeomEAP80Simplified
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, and G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeomEAP80Simplified\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.RI "Implementation of the Geometry of the Simplified EAP80 (SVBR) "
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomEAP80Simplified\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBGeomEAP80Simplified\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeomEAP80Simplified::GeomEAP80Simplified (G4int int_Option, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the Geometry of the Simplified EAP80 (SVBR) 
.PP
Definition at line \fB55\fP of file \fBGeomEAP80Simplified\&.cc\fP\&.
.SS "GeomEAP80Simplified::~GeomEAP80Simplified ()\fC [virtual]\fP"

.PP
Definition at line \fB123\fP of file \fBGeomEAP80Simplified\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * GeomEAP80Simplified::Construct ()\fC [virtual]\fP"
Build of the SVBR Geometry
.PP
Definition at line \fB131\fP of file \fBGeomEAP80Simplified\&.cc\fP\&.
.SS "G4int GeomEAP80Simplified::getNumberOfCopies (G4LogicalVolume * lvol)"

.PP
Definition at line \fB1233\fP of file \fBGeomEAP80Simplified\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomEAP80Simplified::getWorldVolume ()"

.PP
Definition at line \fB1247\fP of file \fBGeomEAP80Simplified\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
