.TH "GeomRez" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeomRez
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, and G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeomRez\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.RI "Implementation of the \fBDetectorConstruction\fP class\&. "
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomRez\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomRez\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomRez\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomRez\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBGeomRez\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeomRez::GeomRez (G4int int_Option, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBDetectorConstruction\fP class\&. 
.PP
Definition at line \fB78\fP of file \fBGeomRez\&.cc\fP\&.
.SS "GeomRez::~GeomRez ()\fC [virtual]\fP"

.PP
Definition at line \fB132\fP of file \fBGeomRez\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * GeomRez::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB140\fP of file \fBGeomRez\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomRez::getWorldVolume ()"

.PP
Definition at line \fB252\fP of file \fBGeomRez\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
