.TH "GeomSVBR100" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeomSVBR100
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, and G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeomSVBR100\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildVessel\fP ()"
.br
.ti -1c
.RI "void \fBbuildTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper)"
.br
.ti -1c
.RI "void \fBbuildMultipleExternalTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildCore\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildHeatExchangers\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBgetContainerLogicalVolume\fP (std::string name, G4double fullHeight, G4double radius, double ellipsoidFactor)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBGeomSVBR100\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildVessel\fP ()"
.br
.ti -1c
.RI "void \fBbuildTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper)"
.br
.ti -1c
.RI "void \fBbuildMultipleExternalTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildCore\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildHeatExchangers\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBgetContainerLogicalVolume\fP (std::string name, G4double fullHeight, G4double radius, double ellipsoidFactor)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBGeomSVBR100\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildVessel\fP ()"
.br
.ti -1c
.RI "void \fBbuildTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper)"
.br
.ti -1c
.RI "void \fBbuildMultipleExternalTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildCore\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildHeatExchangers\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBgetContainerLogicalVolume\fP (std::string name, G4double fullHeight, G4double radius, double ellipsoidFactor)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBGeomSVBR100\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildVessel\fP ()"
.br
.ti -1c
.RI "void \fBbuildTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper)"
.br
.ti -1c
.RI "void \fBbuildMultipleExternalTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildCore\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildHeatExchangers\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBgetContainerLogicalVolume\fP (std::string name, G4double fullHeight, G4double radius, double ellipsoidFactor)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBGeomSVBR100\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildVessel\fP ()"
.br
.ti -1c
.RI "void \fBbuildTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper)"
.br
.ti -1c
.RI "void \fBbuildMultipleExternalTarget\fP (G4LogicalVolume *motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildCore\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation, G4double offsetAngle_Target)"
.br
.ti -1c
.RI "void \fBbuildHeatExchangers\fP (G4LogicalVolume *motherVolume, \fBTMXMaterial\fP *motherMaterial, G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBgetContainerLogicalVolume\fP (std::string name, G4double fullHeight, G4double radius, double ellipsoidFactor)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBGeomSVBR100\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeomSVBR100::GeomSVBR100 (\fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB41\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "GeomSVBR100::~GeomSVBR100 ()\fC [virtual]\fP"

.PP
Definition at line \fB59\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GeomSVBR100::buildCore (G4LogicalVolume * motherVolume, \fBTMXMaterial\fP * motherMaterial, G4ThreeVector translation, G4double offsetAngle_Target)"

.PP
Definition at line \fB334\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::buildHeatExchangers (G4LogicalVolume * motherVolume, \fBTMXMaterial\fP * motherMaterial, G4ThreeVector translation)"

.PP
Definition at line \fB347\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::buildMultipleExternalTarget (G4LogicalVolume * motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper, G4double offsetAngle_Target)"

.PP
Definition at line \fB310\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::buildTarget (G4LogicalVolume * motherVolume, G4ThreeVector translation, G4double extraLength_lower, G4double extraLength_upper)"

.PP
Definition at line \fB301\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::buildVessel ()"

.PP
Definition at line \fB206\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomSVBR100::Construct ()"

.PP
Definition at line \fB62\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::createGeometry ()"
? !!! Based on similarity of images
.PP
m_lPrimaryCoolant ? G4ThreeVector() : G4ThreeVector(0\&., 0\&., zPosition_heatExchanger)
.PP
Definition at line \fB71\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::createMaterial ()"

.PP
Definition at line \fB374\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "G4VSolid * GeomSVBR100::getContainerLogicalVolume (std::string name, G4double fullHeight, G4double radius, double ellipsoidFactor)"

.PP
Definition at line \fB457\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomSVBR100::getWorldVolume ()"

.PP
Definition at line \fB453\fP of file \fBGeomSVBR100\&.cc\fP\&.
.SS "void GeomSVBR100::VisualisationConfig ()"

.PP
Definition at line \fB469\fP of file \fBGeomSVBR100\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
