.TH "GeomKIPT" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeomKIPT
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, and G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeomKIPT\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.RI "Implementation of the \fBDetectorConstruction\fP class\&. "
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomKIPT\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomKIPT\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomKIPT\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "\fBGeomKIPT\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBGeomKIPT\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeomKIPT::GeomKIPT (G4int, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBDetectorConstruction\fP class\&. 
.PP
Definition at line \fB83\fP of file \fBGeomKIPT\&.cc\fP\&.
.SS "GeomKIPT::~GeomKIPT ()\fC [virtual]\fP"

.PP
Definition at line \fB93\fP of file \fBGeomKIPT\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * GeomKIPT::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB101\fP of file \fBGeomKIPT\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomKIPT::getWorldVolume ()"

.PP
Definition at line \fB164\fP of file \fBGeomKIPT\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
