.TH "GeomRezSubcritic" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeomRezSubcritic
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeomRezSubcritic\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.RI "Implementation of the \fBDetectorConstruction\fP class\&. "
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBGeomRezSubcritic\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeomRezSubcritic::GeomRezSubcritic (G4int int_Option, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBDetectorConstruction\fP class\&. 
.PP
Definition at line \fB79\fP of file \fBGeomRezSubcritic\&.cc\fP\&.
.SS "GeomRezSubcritic::~GeomRezSubcritic ()\fC [virtual]\fP"

.PP
Definition at line \fB134\fP of file \fBGeomRezSubcritic\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * GeomRezSubcritic::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB142\fP of file \fBGeomRezSubcritic\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomRezSubcritic::getWorldVolume ()"

.PP
Definition at line \fB251\fP of file \fBGeomRezSubcritic\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
