.TH "GeomSVBR_AKME" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeomSVBR_AKME
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, G4VUserDetectorConstruction, and G4VUserDetectorConstruction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeomSVBR_AKME\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomSVBR_AKME\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomSVBR_AKME\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomSVBR_AKME\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBGeomSVBR_AKME\fP (G4int, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBgetWorldVolume\fP ()"
.br
.ti -1c
.RI "virtual G4VPhysicalVolume * \fBConstruct\fP ()"
.br
.ti -1c
.RI "G4int \fBgetNumberOfCopies\fP (G4LogicalVolume *)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantCoreName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetSecondaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetFuelName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorOuterVesselName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorInnerVesselName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantCoreName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetSecondaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetFuelName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorOuterVesselName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorInnerVesselName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantCoreName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetSecondaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetFuelName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorOuterVesselName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorInnerVesselName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantCoreName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetSecondaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetFuelName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorOuterVesselName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorInnerVesselName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetPrimaryCoolantCoreName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetSecondaryCoolantName\fP ()"
.br
.ti -1c
.RI "static const std::vector< std::string > * \fBgetFuelName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorOuterVesselName\fP ()"
.br
.ti -1c
.RI "static const std::string \fBgetReactorInnerVesselName\fP ()"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static std::vector< std::string > \fBm_vectPrimaryCoolantName\fP"
.br
.RI "Implementation of the Geometry of the EAP80\&. "
.ti -1c
.RI "static std::vector< std::string > \fBm_vectPrimaryCoolantCoreName\fP"
.br
.ti -1c
.RI "static std::vector< std::string > \fBm_vectSecondaryCoolantName\fP"
.br
.ti -1c
.RI "static std::vector< std::string > \fBm_vectFuelName\fP"
.br
.ti -1c
.RI "static std::string \fBm_reactorOuterVesselName\fP"
.br
.ti -1c
.RI "static std::string \fBm_reactorInnerVesselName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeomSVBR_AKME::GeomSVBR_AKME (G4int int_Option, \fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB89\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "GeomSVBR_AKME::~GeomSVBR_AKME ()\fC [virtual]\fP"

.PP
Definition at line \fB105\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4VPhysicalVolume * GeomSVBR_AKME::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB113\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "const std::vector< std::string > * GeomSVBR_AKME::getFuelName ()\fC [static]\fP"

.PP
Definition at line \fB3203\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "G4int GeomSVBR_AKME::getNumberOfCopies (G4LogicalVolume * lvol)"

.PP
Definition at line \fB1827\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "const std::vector< std::string > * GeomSVBR_AKME::getPrimaryCoolantCoreName ()\fC [static]\fP"

.PP
Definition at line \fB3195\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "const std::vector< std::string > * GeomSVBR_AKME::getPrimaryCoolantName ()\fC [static]\fP"

.PP
Definition at line \fB3191\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "const std::string GeomSVBR_AKME::getReactorInnerVesselName ()\fC [static]\fP"

.PP
Definition at line \fB3215\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "const std::string GeomSVBR_AKME::getReactorOuterVesselName ()\fC [static]\fP"

.PP
Definition at line \fB3211\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "const std::vector< std::string > * GeomSVBR_AKME::getSecondaryCoolantName ()\fC [static]\fP"

.PP
Definition at line \fB3199\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SS "G4VPhysicalVolume * GeomSVBR_AKME::getWorldVolume ()"

.PP
Definition at line \fB1841\fP of file \fBGeomSVBR_AKME\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string GeomSVBR_AKME::m_reactorInnerVesselName\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB84\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.
.SS "std::string GeomSVBR_AKME::m_reactorOuterVesselName\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB83\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.
.SS "std::vector< std::string > GeomSVBR_AKME::m_vectFuelName\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB81\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.
.SS "std::vector< std::string > GeomSVBR_AKME::m_vectPrimaryCoolantCoreName\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB79\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.
.SS "std::vector< std::string > GeomSVBR_AKME::m_vectPrimaryCoolantName\fC [static]\fP, \fC [protected]\fP"

.PP
Implementation of the Geometry of the EAP80\&. 
.PP
Definition at line \fB78\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.
.SS "std::vector< std::string > GeomSVBR_AKME::m_vectSecondaryCoolantName\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB80\fP of file \fBGeomSVBR_AKME\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
