.TH "PhysicsList" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysicsList
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, and G4VModularPhysicsList\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBConstructParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructProcess\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetCuts\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructGeneral\fP ()"
.br
.ti -1c
.RI "void \fBSetCutForGamma\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForElectron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForPositron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForProton\fP (G4double)"
.br
.ti -1c
.RI "void \fBAddPhysicsList\fP (const G4String &name)"
.br
.ti -1c
.RI "void \fBList\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructProcess\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetCuts\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructGeneral\fP ()"
.br
.ti -1c
.RI "void \fBSetCutForGamma\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForElectron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForPositron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForProton\fP (G4double)"
.br
.ti -1c
.RI "void \fBAddPhysicsList\fP (const G4String &name)"
.br
.ti -1c
.RI "void \fBList\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructProcess\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetCuts\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructGeneral\fP ()"
.br
.ti -1c
.RI "void \fBSetCutForGamma\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForElectron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForPositron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForProton\fP (G4double)"
.br
.ti -1c
.RI "void \fBAddPhysicsList\fP (const G4String &name)"
.br
.ti -1c
.RI "void \fBList\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructProcess\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetCuts\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructGeneral\fP ()"
.br
.ti -1c
.RI "void \fBSetCutForGamma\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForElectron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForPositron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForProton\fP (G4double)"
.br
.ti -1c
.RI "void \fBAddPhysicsList\fP (const G4String &name)"
.br
.ti -1c
.RI "void \fBList\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructProcess\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetCuts\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructGeneral\fP ()"
.br
.ti -1c
.RI "void \fBSetCutForGamma\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForElectron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForPositron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForProton\fP (G4double)"
.br
.ti -1c
.RI "void \fBAddPhysicsList\fP (const G4String &name)"
.br
.ti -1c
.RI "void \fBList\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructProcess\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetCuts\fP ()"
.br
.ti -1c
.RI "virtual void \fBConstructGeneral\fP ()"
.br
.ti -1c
.RI "void \fBSetCutForGamma\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForElectron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForPositron\fP (G4double)"
.br
.ti -1c
.RI "void \fBSetCutForProton\fP (G4double)"
.br
.ti -1c
.RI "void \fBAddPhysicsList\fP (const G4String &name)"
.br
.ti -1c
.RI "void \fBList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB57\fP of file \fBPhysicsList\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhysicsList::PhysicsList ()"

.PP
Definition at line \fB103\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "PhysicsList::~PhysicsList ()\fC [virtual]\fP"

.PP
Definition at line \fB131\fP of file \fBPhysicsList\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PhysicsList::AddPhysicsList (const G4String & name)"

.PP
Definition at line \fB195\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::ConstructGeneral ()\fC [virtual]\fP"

.PP
Definition at line \fB173\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::ConstructParticle ()\fC [virtual]\fP"

.PP
Definition at line \fB145\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::ConstructProcess ()\fC [virtual]\fP"

.PP
Definition at line \fB152\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::List ()"

.PP
Definition at line \fB499\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::SetCutForElectron (G4double cut)"

.PP
Definition at line \fB477\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::SetCutForGamma (G4double cut)"

.PP
Definition at line \fB469\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::SetCutForPositron (G4double cut)"

.PP
Definition at line \fB485\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::SetCutForProton (G4double cut)"

.PP
Definition at line \fB493\fP of file \fBPhysicsList\&.cc\fP\&.
.SS "void PhysicsList::SetCuts ()\fC [virtual]\fP"

.PP
Definition at line \fB447\fP of file \fBPhysicsList\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
