.TH "Point" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP (double ix, double iy)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB85\fP of file \fBExtractFromLisFluka\&.C\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Point::Point (double ix, double iy)\fC [inline]\fP"

.PP
Definition at line \fB93\fP of file \fBExtractFromLisFluka\&.C\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double Point::x"

.PP
Definition at line \fB89\fP of file \fBExtractFromLisFluka\&.C\fP\&.
.SS "double Point::y"

.PP
Definition at line \fB90\fP of file \fBExtractFromLisFluka\&.C\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
