.TH "PrimaryGeneratorAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrimaryGeneratorAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, and G4VUserPrimaryGeneratorAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrimaryGeneratorAction\fP (G4int Nsource, \fBTMXInputParameters\fP *parameters, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXExternalSource\fP &sourcecExt)"
.br
.ti -1c
.RI "virtual void \fBGeneratePrimaries\fP (G4Event *)"
.br
.ti -1c
.RI "G4int \fBGetNumberInitialParticles\fP () const"
.br
.ti -1c
.RI "G4double \fBGetBeamEnergy\fP () const"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int Nsource, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight)"
.br
.ti -1c
.RI "\fBPrimaryGeneratorAction\fP (G4int Nsource, \fBTMXInputParameters\fP *parameters, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXExternalSource\fP &sourcecExt)"
.br
.ti -1c
.RI "virtual void \fBGeneratePrimaries\fP (G4Event *)"
.br
.ti -1c
.RI "G4int \fBGetNumberInitialParticles\fP () const"
.br
.ti -1c
.RI "G4double \fBGetBeamEnergy\fP () const"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int Nsource, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight)"
.br
.ti -1c
.RI "\fBPrimaryGeneratorAction\fP (G4int Nsource, \fBTMXInputParameters\fP *parameters, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXExternalSource\fP &sourcecExt)"
.br
.ti -1c
.RI "virtual void \fBGeneratePrimaries\fP (G4Event *)"
.br
.ti -1c
.RI "G4int \fBGetNumberInitialParticles\fP () const"
.br
.ti -1c
.RI "G4double \fBGetBeamEnergy\fP () const"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int Nsource, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight)"
.br
.ti -1c
.RI "\fBPrimaryGeneratorAction\fP (G4int Nsource, \fBTMXInputParameters\fP *parameters, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXExternalSource\fP &sourcecExt)"
.br
.ti -1c
.RI "virtual void \fBGeneratePrimaries\fP (G4Event *)"
.br
.ti -1c
.RI "G4int \fBGetNumberInitialParticles\fP () const"
.br
.ti -1c
.RI "G4double \fBGetBeamEnergy\fP () const"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int Nsource, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight)"
.br
.ti -1c
.RI "\fBPrimaryGeneratorAction\fP (G4int Nsource, \fBTMXInputParameters\fP *parameters, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, \fBTMXExternalSource\fP &sourcecExt)"
.br
.ti -1c
.RI "virtual void \fBGeneratePrimaries\fP (G4Event *)"
.br
.ti -1c
.RI "G4int \fBGetNumberInitialParticles\fP () const"
.br
.ti -1c
.RI "G4double \fBGetBeamEnergy\fP () const"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int Nsource, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBPrimaryGeneratorAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PrimaryGeneratorAction::PrimaryGeneratorAction (G4int Nsource, \fBTMXInputParameters\fP * parameters, \fBTMXRandomDistribution3D\fP & RadiusAnglesHeight, \fBTMXExternalSource\fP & sourcecExt)"

.PP
Definition at line \fB49\fP of file \fBPrimaryGeneratorAction\&.cc\fP\&.
.SS "PrimaryGeneratorAction::~PrimaryGeneratorAction ()\fC [virtual]\fP"

.PP
Definition at line \fB81\fP of file \fBPrimaryGeneratorAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent)\fC [virtual]\fP"

.PP
Definition at line \fB146\fP of file \fBPrimaryGeneratorAction\&.cc\fP\&.
.SS "G4double PrimaryGeneratorAction::GetBeamEnergy () const"

.PP
Definition at line \fB648\fP of file \fBPrimaryGeneratorAction\&.cc\fP\&.
.SS "G4int PrimaryGeneratorAction::GetNumberInitialParticles () const"

.PP
Definition at line \fB645\fP of file \fBPrimaryGeneratorAction\&.cc\fP\&.
.SS "void PrimaryGeneratorAction::Initialize (G4int Nsource, \fBTMXRandomDistribution3D\fP & RadiusAnglesHeight)"

.PP
Definition at line \fB652\fP of file \fBPrimaryGeneratorAction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
