.TH "Run" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Run
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4Run, G4Run, G4Run, G4Run, and G4Run\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRun\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.RI "Implementation of the \fBRun\fP class\&. "
.ti -1c
.RI "virtual void \fBRecordEvent\fP (const G4Event *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "void \fBCountProcesses\fP (const G4VProcess *process)"
.br
.RI "\fBRun::CountProcesses\fP\&. "
.ti -1c
.RI "void \fBParticleCount\fP (G4int, G4int, \fBTMXMaterial\fP *)"
.br
.RI "\fBRun::ParticleCount\fP\&. "
.ti -1c
.RI "virtual void \fBMerge\fP (const G4Run *)"
.br
.RI "\fBRun::Merge\fP\&. "
.ti -1c
.RI "void \fBEndOfRun\fP ()"
.br
.RI "\fBRun::EndOfRun\fP\&. "
.ti -1c
.RI "std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > \fBgetSourceTerm\fP ()"
.br
.RI "\fBRun::getSourceTerm\fP\&. "
.ti -1c
.RI "G4THitsMap< G4double > \fBGetFullMap\fP (const G4int j) const"
.br
.ti -1c
.RI "void \fBSetRunNumber\fP (G4int RunNumber)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNumberOfSD\fP () const"
.br
.ti -1c
.RI "\fBRun\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "virtual void \fBRecordEvent\fP (const G4Event *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "void \fBCountProcesses\fP (const G4VProcess *process)"
.br
.ti -1c
.RI "void \fBParticleCount\fP (G4int, G4int, \fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "virtual void \fBMerge\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBEndOfRun\fP ()"
.br
.ti -1c
.RI "std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > \fBgetSourceTerm\fP ()"
.br
.ti -1c
.RI "G4THitsMap< G4double > \fBGetFullMap\fP (const G4int j) const"
.br
.ti -1c
.RI "void \fBSetRunNumber\fP (G4int RunNumber)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNumberOfSD\fP () const"
.br
.ti -1c
.RI "\fBRun\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "virtual void \fBRecordEvent\fP (const G4Event *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "void \fBCountProcesses\fP (const G4VProcess *process)"
.br
.ti -1c
.RI "void \fBParticleCount\fP (G4int, G4int, \fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "virtual void \fBMerge\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBEndOfRun\fP ()"
.br
.ti -1c
.RI "std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > \fBgetSourceTerm\fP ()"
.br
.ti -1c
.RI "G4THitsMap< G4double > \fBGetFullMap\fP (const G4int j) const"
.br
.ti -1c
.RI "void \fBSetRunNumber\fP (G4int RunNumber)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNumberOfSD\fP () const"
.br
.ti -1c
.RI "\fBRun\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "virtual void \fBRecordEvent\fP (const G4Event *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "void \fBCountProcesses\fP (const G4VProcess *process)"
.br
.ti -1c
.RI "void \fBParticleCount\fP (G4int, G4int, \fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "virtual void \fBMerge\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBEndOfRun\fP ()"
.br
.ti -1c
.RI "std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > \fBgetSourceTerm\fP ()"
.br
.ti -1c
.RI "G4THitsMap< G4double > \fBGetFullMap\fP (const G4int j) const"
.br
.ti -1c
.RI "void \fBSetRunNumber\fP (G4int RunNumber)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNumberOfSD\fP () const"
.br
.ti -1c
.RI "\fBRun\fP (G4int RunNumber, \fBTMXInputParameters\fP *p)"
.br
.RI "Implementation of the \fBRun\fP class\&. "
.ti -1c
.RI "virtual void \fBRecordEvent\fP (const G4Event *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, std::string ScoringMeshType)"
.br
.ti -1c
.RI "void \fBBuildHistograms\fP (std::unordered_map< std::string, double > map_LV_volume)"
.br
.ti -1c
.RI "void \fBCreateOutputFile\fP ()"
.br
.ti -1c
.RI "void \fBCountProcesses\fP (const G4VProcess *process)"
.br
.ti -1c
.RI "void \fBParticleCount\fP (G4int, G4int, \fBTMXMaterial\fP *)"
.br
.ti -1c
.RI "void \fBAddEtotDeposit\fP (G4double Edep)"
.br
.RI "\fBRun::AddEtotDeposit\fP\&. "
.ti -1c
.RI "G4double \fBGetEtotDeposit\fP () const"
.br
.RI "\fBRun::GetEtotDeposit\fP\&. "
.ti -1c
.RI "virtual void \fBMerge\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBEndOfRun\fP ()"
.br
.ti -1c
.RI "std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > \fBgetSourceTerm\fP ()"
.br
.ti -1c
.RI "void \fBMergeRootFiles\fP ()"
.br
.ti -1c
.RI "void \fBScoreSurfaceCurrentSpectrum\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBScoreSurfaceFluenceSpectrum\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBScoreVolumeFluenceSpectrum\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBScoreFluenceMap\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBScorePowerDensityMap\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "template<class T > void \fBWrite\fP (T histo)"
.br
.ti -1c
.RI "void \fBWriteResultsInOutputRootFile\fP ()"
.br
.ti -1c
.RI "G4THitsMap< G4double > \fBGetFullMap\fP (const G4int j) const"
.br
.ti -1c
.RI "void \fBSetRunNumber\fP (G4int RunNumber)"
.br
.ti -1c
.RI "G4int \fBGetRunNumber\fP () const"
.br
.ti -1c
.RI "G4int \fBGetNumberOfSD\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TH1D * \fBm_MappingVol_Edep\fP"
.br
.ti -1c
.RI "TH1D * \fBm_MappingEdep\fP"
.br
.ti -1c
.RI "TH1D * \fBm_NeutronGenerationsHisto\fP"
.br
.ti -1c
.RI "TH1D * \fBm_dN_dlogE_N0\fP"
.br
.ti -1c
.RI "TH1D * \fBm_dN_dlogE_N0count\fP"
.br
.ti -1c
.RI "TH1D * \fBm_MappingEdep_square\fP"
.br
.ti -1c
.RI "TH1D * \fBm_MappingEdep_N\fP"
.br
.ti -1c
.RI "TH1D * \fBm_MappingRadial_FluxN\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_Edeposit\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_FluxN\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_FluxG\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_Edep_p\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_Edep_g\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_Ede_ppSrc\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXZ_FluxN\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_Edep_targ\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingYZ_pSrc\fP"
.br
.ti -1c
.RI "TH2D * \fBm_LogEvsLogTime\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXZ_Edep\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXZ_FluxG\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_n\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_g\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_FFe\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_others\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_fission\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_tot\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_FFn\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_FFg\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_FFothers\fP"
.br
.ti -1c
.RI "TH2D * \fBm_d2N_dlogElogTime_FFantiNu\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_N0count\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXZ_N0count\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_N0\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXZ_N0\fP"
.br
.ti -1c
.RI "TH2D * \fBm_N0_DIRvsLogE\fP"
.br
.ti -1c
.RI "TH2D * \fBm_N0_ThetavsLogE\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXY_DeathN0\fP"
.br
.ti -1c
.RI "TH2D * \fBm_MappingXZ_DeathN0\fP"
.br
.ti -1c
.RI "\fBTMXScoringEverythingNNtuple\fP * \fBm_scoringNtupleEverythingN\fP"
.br
.ti -1c
.RI "TNtuple * \fBm_scoringNtupleTransmutationInfo\fP"
.br
.ti -1c
.RI "TNtuple * \fBm_scoringNtupleDepositedPower\fP"
.br
.ti -1c
.RI "TNtuple * \fBm_scoringNtupleTMXNeutronSource\fP"
.br
.ti -1c
.RI "TNtuple * \fBm_scoringNtupleProton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB51\fP of file \fBRun\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Run::Run (G4int RunNumber, std::string ScoringMeshType)"

.PP
Implementation of the \fBRun\fP class\&. 
.PP
Definition at line \fB48\fP of file \fBRun\&.cc\fP\&.
.SS "Run::~Run ()\fC [virtual]\fP"

.PP
Definition at line \fB52\fP of file \fBRun\&.cc\fP\&.
.SS "Run::Run (G4int RunNumber, \fBTMXInputParameters\fP * p)"

.PP
Implementation of the \fBRun\fP class\&. 
.PP
Definition at line \fB63\fP of file \fBRun\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Run::AddEtotDeposit (G4double Edep)"

.PP
\fBRun::AddEtotDeposit\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIEdep\fP 
.RE
.PP

.PP
Definition at line \fB429\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::BuildHistograms (std::unordered_map< std::string, double > map_LV_volume)"

.PP
Definition at line \fB193\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::CountProcesses (const G4VProcess * process)"

.PP
\fBRun::CountProcesses\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIprocess\fP 
.RE
.PP

.PP
Definition at line \fB163\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::CreateOutputFile ()"

.PP
Definition at line \fB319\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::EndOfRun ()"

.PP
\fBRun::EndOfRun\fP\&. 
.PP
Definition at line \fB200\fP of file \fBRun\&.cc\fP\&.
.SS "G4double Run::GetEtotDeposit () const"

.PP
\fBRun::GetEtotDeposit\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIEdep\fP 
.RE
.PP

.PP
Definition at line \fB438\fP of file \fBRun\&.cc\fP\&.
.SS "G4THitsMap< G4double > Run::GetFullMap (const G4int j) const\fC [inline]\fP"

.PP
Definition at line \fB94\fP of file \fBRun\&.hh\fP\&.
.SS "G4THitsMap< G4double > Run::GetFullMap (const G4int j) const\fC [inline]\fP"

.PP
Definition at line \fB94\fP of file \fBRun\&.hh\fP\&.
.SS "G4THitsMap< G4double > Run::GetFullMap (const G4int j) const\fC [inline]\fP"

.PP
Definition at line \fB94\fP of file \fBRun\&.hh\fP\&.
.SS "G4THitsMap< G4double > Run::GetFullMap (const G4int j) const\fC [inline]\fP"

.PP
Definition at line \fB94\fP of file \fBRun\&.hh\fP\&.
.SS "G4THitsMap< G4double > Run::GetFullMap (const G4int j) const\fC [inline]\fP"

.PP
Definition at line \fB195\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetNumberOfSD () const\fC [inline]\fP"

.PP
Definition at line \fB101\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetNumberOfSD () const\fC [inline]\fP"

.PP
Definition at line \fB101\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetNumberOfSD () const\fC [inline]\fP"

.PP
Definition at line \fB101\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetNumberOfSD () const\fC [inline]\fP"

.PP
Definition at line \fB101\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetNumberOfSD () const\fC [inline]\fP"

.PP
Definition at line \fB202\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetRunNumber () const\fC [inline]\fP"

.PP
Definition at line \fB100\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetRunNumber () const\fC [inline]\fP"

.PP
Definition at line \fB100\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetRunNumber () const\fC [inline]\fP"

.PP
Definition at line \fB100\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetRunNumber () const\fC [inline]\fP"

.PP
Definition at line \fB100\fP of file \fBRun\&.hh\fP\&.
.SS "G4int Run::GetRunNumber () const\fC [inline]\fP"

.PP
Definition at line \fB201\fP of file \fBRun\&.hh\fP\&.
.SS "std::map< \fBTMXMaterial\fP *, std::map< G4int, G4int > > Run::getSourceTerm ()"

.PP
\fBRun::getSourceTerm\fP\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB245\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::Initialize (G4int RunNumber, std::string ScoringMeshType)"

.PP
Definition at line \fB89\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::Merge (const G4Run * run)\fC [virtual]\fP"

.PP
\fBRun::Merge\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIrun\fP 
.RE
.PP

.PP
Definition at line \fB137\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::MergeRootFiles ()"

.PP
Definition at line \fB501\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::ParticleCount (G4int partName, G4int count, \fBTMXMaterial\fP * mat)"

.PP
\fBRun::ParticleCount\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpartName\fP 
.br
\fIcount\fP 
.br
\fImat\fP 
.RE
.PP

.PP
Definition at line \fB179\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::RecordEvent (const G4Event * evt)\fC [virtual]\fP"

.PP
Definition at line \fB58\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::ScoreFluenceMap (const G4Step * theStep)"

.PP
Definition at line \fB578\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::ScorePowerDensityMap (const G4Step * theStep)"

.PP
Definition at line \fB584\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::ScoreSurfaceCurrentSpectrum (const G4Step * theStep)"

.PP
Definition at line \fB560\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::ScoreSurfaceFluenceSpectrum (const G4Step * theStep)"

.PP
Definition at line \fB566\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::ScoreVolumeFluenceSpectrum (const G4Step * theStep)"

.PP
Definition at line \fB572\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::SetRunNumber (G4int RunNumber)\fC [inline]\fP"

.PP
Definition at line \fB97\fP of file \fBRun\&.hh\fP\&.
.SS "void Run::SetRunNumber (G4int RunNumber)\fC [inline]\fP"

.PP
Definition at line \fB97\fP of file \fBRun\&.hh\fP\&.
.SS "void Run::SetRunNumber (G4int RunNumber)\fC [inline]\fP"

.PP
Definition at line \fB97\fP of file \fBRun\&.hh\fP\&.
.SS "void Run::SetRunNumber (G4int RunNumber)\fC [inline]\fP"

.PP
Definition at line \fB97\fP of file \fBRun\&.hh\fP\&.
.SS "void Run::SetRunNumber (G4int RunNumber)\fC [inline]\fP"

.PP
Definition at line \fB198\fP of file \fBRun\&.hh\fP\&.
.SS "template<class T > void Run::Write (T histo)"

.PP
Definition at line \fB594\fP of file \fBRun\&.cc\fP\&.
.SS "void Run::WriteResultsInOutputRootFile ()"

.PP
Definition at line \fB605\fP of file \fBRun\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "TH2D* Run::m_d2N_dlogElogTime_FFantiNu"

.PP
Definition at line \fB177\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_FFe"

.PP
Definition at line \fB170\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_FFg"

.PP
Definition at line \fB175\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_FFn"

.PP
Definition at line \fB174\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_FFothers"

.PP
Definition at line \fB176\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_fission"

.PP
Definition at line \fB172\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_g"

.PP
Definition at line \fB169\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_n"

.PP
Definition at line \fB168\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_others"

.PP
Definition at line \fB171\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_d2N_dlogElogTime_tot"

.PP
Definition at line \fB173\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_dN_dlogE_N0"

.PP
Definition at line \fB150\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_dN_dlogE_N0count"

.PP
Definition at line \fB151\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_LogEvsLogTime"

.PP
Definition at line \fB165\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_MappingEdep"

.PP
Definition at line \fB148\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_MappingEdep_N"

.PP
Definition at line \fB153\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_MappingEdep_square"

.PP
Definition at line \fB152\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_MappingRadial_FluxN"

.PP
Definition at line \fB154\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_MappingVol_Edep"

.PP
Definition at line \fB147\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_DeathN0"

.PP
Definition at line \fB184\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_Ede_ppSrc"

.PP
Definition at line \fB161\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_Edep_g"

.PP
Definition at line \fB160\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_Edep_p"

.PP
Definition at line \fB159\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_Edep_targ"

.PP
Definition at line \fB163\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_Edeposit"

.PP
Definition at line \fB156\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_FluxG"

.PP
Definition at line \fB158\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_FluxN"

.PP
Definition at line \fB157\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_N0"

.PP
Definition at line \fB180\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXY_N0count"

.PP
Definition at line \fB178\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXZ_DeathN0"

.PP
Definition at line \fB185\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXZ_Edep"

.PP
Definition at line \fB166\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXZ_FluxG"

.PP
Definition at line \fB167\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXZ_FluxN"

.PP
Definition at line \fB162\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXZ_N0"

.PP
Definition at line \fB181\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingXZ_N0count"

.PP
Definition at line \fB179\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_MappingYZ_pSrc"

.PP
Definition at line \fB164\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_N0_DIRvsLogE"

.PP
Definition at line \fB182\fP of file \fBRun\&.hh\fP\&.
.SS "TH2D* Run::m_N0_ThetavsLogE"

.PP
Definition at line \fB183\fP of file \fBRun\&.hh\fP\&.
.SS "TH1D* Run::m_NeutronGenerationsHisto"

.PP
Definition at line \fB149\fP of file \fBRun\&.hh\fP\&.
.SS "TNtuple* Run::m_scoringNtupleDepositedPower"

.PP
Definition at line \fB190\fP of file \fBRun\&.hh\fP\&.
.SS "\fBTMXScoringEverythingNNtuple\fP* Run::m_scoringNtupleEverythingN"

.PP
Definition at line \fB188\fP of file \fBRun\&.hh\fP\&.
.SS "TNtuple* Run::m_scoringNtupleProton"

.PP
Definition at line \fB192\fP of file \fBRun\&.hh\fP\&.
.SS "TNtuple* Run::m_scoringNtupleTMXNeutronSource"

.PP
Definition at line \fB191\fP of file \fBRun\&.hh\fP\&.
.SS "TNtuple* Run::m_scoringNtupleTransmutationInfo"

.PP
Definition at line \fB189\fP of file \fBRun\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
