.TH "RunAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RunAction \- Definition of the \fBRunAction\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RunAction\&.hh>\fP
.PP
Inherits G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, and G4UserRunAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRunAction\fP (\fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "G4Run * \fBGenerateRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "virtual void \fBEndOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "void \fBBuildHistogramsAndNtuple\fP ()"
.br
.ti -1c
.RI "\fBRunAction\fP (\fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "G4Run * \fBGenerateRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "virtual void \fBEndOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "void \fBBuildHistogramsAndNtuple\fP ()"
.br
.ti -1c
.RI "\fBRunAction\fP (\fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "G4Run * \fBGenerateRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "virtual void \fBEndOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "void \fBBuildHistogramsAndNtuple\fP ()"
.br
.ti -1c
.RI "\fBRunAction\fP (\fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "G4Run * \fBGenerateRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "virtual void \fBEndOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "void \fBBuildHistogramsAndNtuple\fP ()"
.br
.ti -1c
.RI "\fBRunAction\fP (\fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "G4Run * \fBGenerateRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBBeginOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "virtual void \fBEndOfRunAction\fP (const G4Run *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int RunNumber, \fBTMXInputParameters\fP &parameter, \fBTMXMergeThreadsResults\fP *mergedResultsinTextFile)"
.br
.ti -1c
.RI "void \fBBuildHistogramsAndNtuple\fP ()"
.br
.ti -1c
.RI "void \fBSetMapLVCubicVolume\fP (std::unordered_map< std::string, double > mapLVCubicVolume)"
.br
.ti -1c
.RI "void \fBScoreDPA\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBScoreEnergyDeposited\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBScoreDetectionChamber\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBAddEtotDeposit\fP (G4double Edep)"
.br
.ti -1c
.RI "void \fBScoreDepositedPower\fP (const G4Step *theStep, int NeutronGenerations)"
.br
.ti -1c
.RI "\fBRun\fP * \fBGetRun\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRunAction\fP * \fBInstance\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "clock_t \fBfTimerPublic\fP"
.br
.ti -1c
.RI "double \fBm_timePassed\fP"
.br
.ti -1c
.RI "\fBTMXScoringPowerDensityMap\fP * \fBm_scoringPowerDensityMap\fP"
.br
.ti -1c
.RI "\fBTMXScoringSurfaceCurrentSpectrum\fP * \fBm_scoringSurfaceCurrentSpectrum\fP"
.br
.ti -1c
.RI "\fBTMXScoringSurfaceFluenceSpectrum\fP * \fBm_scoringSurfaceFluenceSpectrum\fP"
.br
.ti -1c
.RI "\fBTMXScoringVolumeFluenceSpectrum\fP * \fBm_scoringVolumeFluenceSpectrum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBRunAction\fP class\&. 
.PP
Definition at line \fB37\fP of file \fBRunAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RunAction::RunAction (\fBTMXInputParameters\fP & parameter, \fBTMXMergeThreadsResults\fP * mergedResultsinTextFile)"

.PP
Definition at line \fB54\fP of file \fBRunAction\&.cc\fP\&.
.SS "RunAction::~RunAction ()\fC [virtual]\fP"

.PP
Definition at line \fB71\fP of file \fBRunAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RunAction::AddEtotDeposit (G4double Edep)"

.PP
Definition at line \fB667\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::BeginOfRunAction (const G4Run * aRun)\fC [virtual]\fP"

.PP
Definition at line \fB88\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::BuildHistogramsAndNtuple ()"

.PP
Definition at line \fB323\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::EndOfRunAction (const G4Run * run)\fC [virtual]\fP"

.PP
Definition at line \fB140\fP of file \fBRunAction\&.cc\fP\&.
.SS "G4Run * RunAction::GenerateRun ()"

.PP
Definition at line \fB79\fP of file \fBRunAction\&.cc\fP\&.
.SS "\fBRun\fP * RunAction::GetRun () const"

.PP
Definition at line \fB704\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::Initialize (G4int RunNumber, \fBTMXInputParameters\fP & parameter, \fBTMXMergeThreadsResults\fP * mergedResultsinTextFile)"

.PP
Definition at line \fB304\fP of file \fBRunAction\&.cc\fP\&.
.SS "\fBRunAction\fP * RunAction::Instance ()\fC [static]\fP"

.PP
Definition at line \fB157\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::ScoreDepositedPower (const G4Step * theStep, int NeutronGenerations)"

.PP
Definition at line \fB694\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::ScoreDetectionChamber (const G4Step * theStep)"

.PP
Definition at line \fB688\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::ScoreDPA (const G4Step * theStep)"

.PP
Definition at line \fB676\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::ScoreEnergyDeposited (const G4Step * theStep)"

.PP
Definition at line \fB682\fP of file \fBRunAction\&.cc\fP\&.
.SS "void RunAction::SetMapLVCubicVolume (std::unordered_map< std::string, double > mapLVCubicVolume)"

.PP
Definition at line \fB660\fP of file \fBRunAction\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "clock_t RunAction::fTimerPublic"

.PP
Definition at line \fB45\fP of file \fBRunAction\&.hh\fP\&.
.SS "\fBTMXScoringPowerDensityMap\fP * RunAction::m_scoringPowerDensityMap"

.PP
Definition at line \fB47\fP of file \fBRunAction\&.hh\fP\&.
.SS "\fBTMXScoringSurfaceCurrentSpectrum\fP * RunAction::m_scoringSurfaceCurrentSpectrum"

.PP
Definition at line \fB48\fP of file \fBRunAction\&.hh\fP\&.
.SS "\fBTMXScoringSurfaceFluenceSpectrum\fP * RunAction::m_scoringSurfaceFluenceSpectrum"

.PP
Definition at line \fB49\fP of file \fBRunAction\&.hh\fP\&.
.SS "\fBTMXScoringVolumeFluenceSpectrum\fP * RunAction::m_scoringVolumeFluenceSpectrum"

.PP
Definition at line \fB50\fP of file \fBRunAction\&.hh\fP\&.
.SS "double RunAction::m_timePassed"

.PP
Definition at line \fB46\fP of file \fBRunAction\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
