.TH "ScoringParallelWorld_hexagonal" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoringParallelWorld_hexagonal
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserParallelWorld, G4VUserParallelWorld, G4VUserParallelWorld, G4VUserParallelWorld, and G4VUserParallelWorld\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoringParallelWorld_hexagonal\fP (G4String worldName, \fBTMXInputParameters\fP *parameter)"
.br
.RI "Implementation of the \fBScoringParallelWorld_hexagonal\fP class\&. "
.ti -1c
.RI "virtual void \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int pitch, G4double minBinX, G4double maxBinX, G4double minBinY, G4double maxBinY, G4int nbinsZ, G4double minZ, G4double maxZ)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBGiveWorld\fP ()"
.br
.ti -1c
.RI "\fBScoringParallelWorld_hexagonal\fP (G4String worldName, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "virtual void \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int pitch, G4double minBinX, G4double maxBinX, G4double minBinY, G4double maxBinY, G4int nbinsZ, G4double minZ, G4double maxZ)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBGiveWorld\fP ()"
.br
.ti -1c
.RI "\fBScoringParallelWorld_hexagonal\fP (G4String worldName, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "virtual void \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int pitch, G4double minBinX, G4double maxBinX, G4double minBinY, G4double maxBinY, G4int nbinsZ, G4double minZ, G4double maxZ)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBGiveWorld\fP ()"
.br
.ti -1c
.RI "\fBScoringParallelWorld_hexagonal\fP (G4String worldName, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "virtual void \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int pitch, G4double minBinX, G4double maxBinX, G4double minBinY, G4double maxBinY, G4int nbinsZ, G4double minZ, G4double maxZ)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBGiveWorld\fP ()"
.br
.ti -1c
.RI "\fBScoringParallelWorld_hexagonal\fP (G4String worldName, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "virtual void \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (G4int pitch, G4double minBinX, G4double maxBinX, G4double minBinY, G4double maxBinY, G4int nbinsZ, G4double minZ, G4double maxZ)"
.br
.ti -1c
.RI "G4VPhysicalVolume * \fBGiveWorld\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB54\fP of file \fBScoringParallelWorld_hexagonal\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ScoringParallelWorld_hexagonal::ScoringParallelWorld_hexagonal (G4String worldName, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBScoringParallelWorld_hexagonal\fP class\&. 
.PP
Definition at line \fB61\fP of file \fBScoringParallelWorld_hexagonal\&.cc\fP\&.
.SS "ScoringParallelWorld_hexagonal::~ScoringParallelWorld_hexagonal ()\fC [virtual]\fP"

.PP
Definition at line \fB66\fP of file \fBScoringParallelWorld_hexagonal\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ScoringParallelWorld_hexagonal::Construct ()\fC [virtual]\fP"

.PP
Definition at line \fB85\fP of file \fBScoringParallelWorld_hexagonal\&.cc\fP\&.
.SS "G4VPhysicalVolume * ScoringParallelWorld_hexagonal::GiveWorld ()"

.PP
Definition at line \fB219\fP of file \fBScoringParallelWorld_hexagonal\&.cc\fP\&.
.SS "void ScoringParallelWorld_hexagonal::Initialize (G4int pitch, G4double minBinX, G4double maxBinX, G4double minBinY, G4double maxBinY, G4int nbinsZ, G4double minZ, G4double maxZ)"

.PP
Definition at line \fB69\fP of file \fBScoringParallelWorld_hexagonal\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
