.TH "StackingAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StackingAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4UserStackingAction, G4UserStackingAction, G4UserStackingAction, G4UserStackingAction, and G4UserStackingAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStackingAction\fP ()"
.br
.RI "Implementation of the \fBStackingAction\fP class\&. "
.ti -1c
.RI "void \fBSetKillStatus\fP (G4bool value)"
.br
.ti -1c
.RI "void \fBSetKill\fP (const G4String &name)"
.br
.ti -1c
.RI "virtual G4ClassificationOfNewTrack \fBClassifyNewTrack\fP (const G4Track *)"
.br
.ti -1c
.RI "virtual void \fBNewStage\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrepareNewEvent\fP ()"
.br
.ti -1c
.RI "void \fBSetKillStatus\fP (G4bool value)"
.br
.ti -1c
.RI "void \fBSetKill\fP (const G4String &name)"
.br
.ti -1c
.RI "virtual G4ClassificationOfNewTrack \fBClassifyNewTrack\fP (const G4Track *)"
.br
.ti -1c
.RI "virtual void \fBNewStage\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrepareNewEvent\fP ()"
.br
.ti -1c
.RI "void \fBSetKillStatus\fP (G4bool value)"
.br
.ti -1c
.RI "void \fBSetKill\fP (const G4String &name)"
.br
.ti -1c
.RI "virtual G4ClassificationOfNewTrack \fBClassifyNewTrack\fP (const G4Track *)"
.br
.ti -1c
.RI "virtual void \fBNewStage\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrepareNewEvent\fP ()"
.br
.ti -1c
.RI "void \fBSetKillStatus\fP (G4bool value)"
.br
.ti -1c
.RI "void \fBSetKill\fP (const G4String &name)"
.br
.ti -1c
.RI "virtual G4ClassificationOfNewTrack \fBClassifyNewTrack\fP (const G4Track *)"
.br
.ti -1c
.RI "virtual void \fBNewStage\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrepareNewEvent\fP ()"
.br
.ti -1c
.RI "void \fBSetKillStatus\fP (G4bool value)"
.br
.ti -1c
.RI "void \fBSetKill\fP (const G4String &name)"
.br
.ti -1c
.RI "virtual G4ClassificationOfNewTrack \fBClassifyNewTrack\fP (const G4Track *)"
.br
.ti -1c
.RI "virtual void \fBNewStage\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrepareNewEvent\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB51\fP of file \fBStackingAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StackingAction::StackingAction ()"

.PP
Implementation of the \fBStackingAction\fP class\&. 
.PP
Definition at line \fB51\fP of file \fBStackingAction\&.cc\fP\&.
.SS "StackingAction::~StackingAction ()\fC [virtual]\fP"

.PP
Definition at line \fB61\fP of file \fBStackingAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track * aTrack)\fC [virtual]\fP"

.PP
Definition at line \fB69\fP of file \fBStackingAction\&.cc\fP\&.
.SS "void StackingAction::NewStage ()\fC [virtual]\fP"

.PP
Definition at line \fB88\fP of file \fBStackingAction\&.cc\fP\&.
.SS "void StackingAction::PrepareNewEvent ()\fC [virtual]\fP"

.PP
Definition at line \fB97\fP of file \fBStackingAction\&.cc\fP\&.
.SS "void StackingAction::SetKill (const G4String & name)"

.PP
Definition at line \fB110\fP of file \fBStackingAction\&.cc\fP\&.
.SS "void StackingAction::SetKillStatus (G4bool value)"

.PP
Definition at line \fB103\fP of file \fBStackingAction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
