.TH "SteppingAction" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SteppingAction \- Definition of the \fBSteppingAction\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SteppingAction\&.hh>\fP
.PP
Inherits G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, and G4UserSteppingAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteppingAction\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "virtual void \fBUserSteppingAction\fP (const G4Step *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "\fBSteppingAction\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "virtual void \fBUserSteppingAction\fP (const G4Step *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "\fBSteppingAction\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "virtual void \fBUserSteppingAction\fP (const G4Step *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "\fBSteppingAction\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "virtual void \fBUserSteppingAction\fP (const G4Step *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "\fBSteppingAction\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.ti -1c
.RI "virtual void \fBUserSteppingAction\fP (const G4Step *)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBEventAction\fP *eventAction, \fBRunAction\fP *runAction, \fBTMXInputParameters\fP &parameter)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBSteppingAction\fP class\&. 
.PP
Definition at line \fB35\fP of file \fBSteppingAction\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SteppingAction::SteppingAction (\fBEventAction\fP * eventAction, \fBRunAction\fP * runAction, \fBTMXInputParameters\fP & parameter)"

.PP
Definition at line \fB91\fP of file \fBSteppingAction\&.cc\fP\&.
.SS "SteppingAction::~SteppingAction ()\fC [virtual]\fP"

.PP
Definition at line \fB96\fP of file \fBSteppingAction\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SteppingAction::Initialize (\fBEventAction\fP * eventAction, \fBRunAction\fP * runAction, \fBTMXInputParameters\fP & parameter)"

.PP
Definition at line \fB1469\fP of file \fBSteppingAction\&.cc\fP\&.
.SS "void SteppingAction::UserSteppingAction (const G4Step * theStep)\fC [virtual]\fP"

.PP
Definition at line \fB101\fP of file \fBSteppingAction\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
