.TH "SVBR100_FuelAssembly" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVBR100_FuelAssembly
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, and \fBTMXAbstractFuelAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVBR100_FuelAssembly\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBbuildFuelPinLattice\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceControlRod\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetHalfHeightFuelPin\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbFuelPinSections\fP (int nbFuelPinSections)"
.br
.ti -1c
.RI "void \fBsetIndex\fP (std::string index)"
.br
.ti -1c
.RI "void \fBsetZRodInsertion\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelAssembly\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBbuildFuelPinLattice\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceControlRod\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetHalfHeightFuelPin\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbFuelPinSections\fP (int nbFuelPinSections)"
.br
.ti -1c
.RI "void \fBsetIndex\fP (std::string index)"
.br
.ti -1c
.RI "void \fBsetZRodInsertion\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelAssembly\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBbuildFuelPinLattice\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceControlRod\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetHalfHeightFuelPin\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbFuelPinSections\fP (int nbFuelPinSections)"
.br
.ti -1c
.RI "void \fBsetIndex\fP (std::string index)"
.br
.ti -1c
.RI "void \fBsetZRodInsertion\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelAssembly\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBbuildFuelPinLattice\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceControlRod\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetHalfHeightFuelPin\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbFuelPinSections\fP (int nbFuelPinSections)"
.br
.ti -1c
.RI "void \fBsetIndex\fP (std::string index)"
.br
.ti -1c
.RI "void \fBsetZRodInsertion\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelAssembly\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBbuildFuelPinLattice\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceControlRod\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetHalfHeightFuelPin\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbFuelPinSections\fP (int nbFuelPinSections)"
.br
.ti -1c
.RI "void \fBsetIndex\fP (std::string index)"
.br
.ti -1c
.RI "void \fBsetZRodInsertion\fP (G4double zRodInsertion)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBSVBR100_FuelAssembly\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SVBR100_FuelAssembly::SVBR100_FuelAssembly (std::string name, \fBTMXInputParameters\fP * p)"

.PP
Definition at line \fB29\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SVBR100_FuelAssembly::buildFuelPinLattice (G4ThreeVector translation)"

.PP
Definition at line \fB54\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB71\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB195\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void SVBR100_FuelAssembly::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "G4LogicalVolume * SVBR100_FuelAssembly::getMasterVolume ()"

.PP
Definition at line \fB260\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::placeGeometry ()"

.PP
Definition at line \fB215\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::placeGeometry (G4ThreeVector translation)"

.PP
Definition at line \fB209\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::setHalfHeightFuelPin (G4double halfHeight)"

.PP
Definition at line \fB241\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::setIndex (std::string index)"

.PP
Definition at line \fB249\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::setMetalicStructureMaterial (\fBTMXMaterial\fP * metalicStructureMaterial)"

.PP
Definition at line \fB237\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::setNbFuelPinSections (int nbFuelPinSections)"

.PP
Definition at line \fB245\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::setPrimaryCoolantMaterial (\fBTMXMaterial\fP * primaryCoolantMaterial)"

.PP
Definition at line \fB233\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.
.SS "void SVBR100_FuelAssembly::setZRodInsertion (G4double zRodInsertion)"

.PP
Definition at line \fB253\fP of file \fBSVBR100_FuelAssembly\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
