.TH "SVBR100_Core" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVBR100_Core
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractCore\fP, \fBTMXAbstractCore\fP, \fBTMXAbstractCore\fP, \fBTMXAbstractCore\fP, and \fBTMXAbstractCore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVBR100_Core\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *motherVolume, bool isMultipleExternalTarget, int nbTarget, G4double distanceTargetCenter, G4double offsetAngle)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildActiveCore\fP ()"
.br
.ti -1c
.RI "void \fBbuildFuelAssemblyLattice\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShield\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShieldForMultipleTarget\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBbuildInternalStructures\fP ()"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetInnerRadiusActiveCore\fP (G4double innerRadius)"
.br
.ti -1c
.RI "void \fBsetBurnupDivision\fP (bool isRoundAssemblyDivision, int nbAxialFuelPinDivision)"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusNeutronShield\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_Core\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *motherVolume, bool isMultipleExternalTarget, int nbTarget, G4double distanceTargetCenter, G4double offsetAngle)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildActiveCore\fP ()"
.br
.ti -1c
.RI "void \fBbuildFuelAssemblyLattice\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShield\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShieldForMultipleTarget\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBbuildInternalStructures\fP ()"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetInnerRadiusActiveCore\fP (G4double innerRadius)"
.br
.ti -1c
.RI "void \fBsetBurnupDivision\fP (bool isRoundAssemblyDivision, int nbAxialFuelPinDivision)"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusNeutronShield\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_Core\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *motherVolume, bool isMultipleExternalTarget, int nbTarget, G4double distanceTargetCenter, G4double offsetAngle)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildActiveCore\fP ()"
.br
.ti -1c
.RI "void \fBbuildFuelAssemblyLattice\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShield\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShieldForMultipleTarget\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBbuildInternalStructures\fP ()"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetInnerRadiusActiveCore\fP (G4double innerRadius)"
.br
.ti -1c
.RI "void \fBsetBurnupDivision\fP (bool isRoundAssemblyDivision, int nbAxialFuelPinDivision)"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusNeutronShield\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_Core\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *motherVolume, bool isMultipleExternalTarget, int nbTarget, G4double distanceTargetCenter, G4double offsetAngle)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildActiveCore\fP ()"
.br
.ti -1c
.RI "void \fBbuildFuelAssemblyLattice\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShield\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShieldForMultipleTarget\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBbuildInternalStructures\fP ()"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetInnerRadiusActiveCore\fP (G4double innerRadius)"
.br
.ti -1c
.RI "void \fBsetBurnupDivision\fP (bool isRoundAssemblyDivision, int nbAxialFuelPinDivision)"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusNeutronShield\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_Core\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *motherVolume, bool isMultipleExternalTarget, int nbTarget, G4double distanceTargetCenter, G4double offsetAngle)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBbuildActiveCore\fP ()"
.br
.ti -1c
.RI "void \fBbuildFuelAssemblyLattice\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShield\fP ()"
.br
.ti -1c
.RI "void \fBbuildNeutronShieldForMultipleTarget\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBbuildInternalStructures\fP ()"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "void \fBsetInnerRadiusActiveCore\fP (G4double innerRadius)"
.br
.ti -1c
.RI "void \fBsetBurnupDivision\fP (bool isRoundAssemblyDivision, int nbAxialFuelPinDivision)"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusNeutronShield\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBSVBR100_Core\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SVBR100_Core::SVBR100_Core (\fBTMXInputParameters\fP * p, G4LogicalVolume * motherVolume, bool isMultipleExternalTarget, int nbTarget, G4double distanceTargetCenter, G4double offsetAngle)"

.PP
Definition at line \fB32\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SVBR100_Core::buildActiveCore ()"

.PP
Definition at line \fB77\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::buildFuelAssemblyLattice ()"

.PP
Definition at line \fB83\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::buildInternalStructures ()"

.PP
Definition at line \fB216\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::buildNeutronShield ()"

.PP
Definition at line \fB161\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::buildNeutronShieldForMultipleTarget (G4ThreeVector translation, G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB170\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::createGeometry ()"

.PP
Definition at line \fB69\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::createMaterial ()"

.PP
Definition at line \fB236\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "G4double SVBR100_Core::getOuterRadiusNeutronShield ()"

.PP
Definition at line \fB350\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::placeGeometry ()"

.PP
Definition at line \fB315\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::placeGeometry (G4ThreeVector translation)"

.PP
Definition at line \fB311\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::placeGeometry (G4ThreeVector translation, G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB271\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::setBurnupDivision (bool isRoundAssemblyDivision, int nbAxialFuelPinDivision)"

.PP
Definition at line \fB342\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::setInnerRadiusActiveCore (G4double innerRadius)"

.PP
Definition at line \fB338\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::setMetalicStructureMaterial (\fBTMXMaterial\fP * metalicStructureMaterial)"

.PP
Definition at line \fB334\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::setMotherVolume (G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB322\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::setPrimaryCoolantMaterial (\fBTMXMaterial\fP * primaryCoolantMaterial)"

.PP
Definition at line \fB330\fP of file \fBSVBR100_Core\&.cc\fP\&.
.SS "void SVBR100_Core::setTranslation (G4ThreeVector translation)"

.PP
Definition at line \fB326\fP of file \fBSVBR100_Core\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
