.TH "SVBR100_HeatExchanger" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVBR100_HeatExchanger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVBR100_HeatExchanger\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double halfLength_insideReactor)"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_HeatExchanger\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double halfLength_insideReactor)"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_HeatExchanger\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double halfLength_insideReactor)"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_HeatExchanger\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double halfLength_insideReactor)"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_HeatExchanger\fP (\fBTMXInputParameters\fP *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double halfLength_insideReactor)"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetPrimaryCoolantMaterial\fP (\fBTMXMaterial\fP *primaryCoolantMaterial)"
.br
.ti -1c
.RI "void \fBsetMetalicStructureMaterial\fP (\fBTMXMaterial\fP *metalicStructureMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBSVBR100_HeatExchanger\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SVBR100_HeatExchanger::SVBR100_HeatExchanger (\fBTMXInputParameters\fP * p, G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB24\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SVBR100_HeatExchanger::createGeometry (G4double halfLength_insideReactor)"

.PP
Definition at line \fB42\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::createMaterials ()"

.PP
Definition at line \fB68\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "G4LogicalVolume * SVBR100_HeatExchanger::getMasterVolume ()"

.PP
Definition at line \fB149\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::placeGeometry (G4ThreeVector translation)"

.PP
Definition at line \fB123\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::placeGeometry (G4ThreeVector translation, G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB115\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::setMetalicStructureMaterial (\fBTMXMaterial\fP * metalicStructureMaterial)"

.PP
Definition at line \fB142\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::setMotherVolume (G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB130\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::setPrimaryCoolantMaterial (\fBTMXMaterial\fP * primaryCoolantMaterial)"

.PP
Definition at line \fB138\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.
.SS "void SVBR100_HeatExchanger::setTranslation (G4ThreeVector translation)"

.PP
Definition at line \fB134\fP of file \fBSVBR100_HeatExchanger\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
