.TH "SVBR100_FuelPin" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVBR100_FuelPin
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVBR100_FuelPin\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBsetHalfHeight\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbSections\fP (int nbSections)"
.br
.ti -1c
.RI "void \fBsetFuelAssemblyIndex\fP (std::string index)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelPin\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBsetHalfHeight\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbSections\fP (int nbSections)"
.br
.ti -1c
.RI "void \fBsetFuelAssemblyIndex\fP (std::string index)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelPin\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBsetHalfHeight\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbSections\fP (int nbSections)"
.br
.ti -1c
.RI "void \fBsetFuelAssemblyIndex\fP (std::string index)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelPin\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBsetHalfHeight\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbSections\fP (int nbSections)"
.br
.ti -1c
.RI "void \fBsetFuelAssemblyIndex\fP (std::string index)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBSVBR100_FuelPin\fP (std::string name, \fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterials\fP ()"
.br
.ti -1c
.RI "void \fBsetHalfHeight\fP (G4double halfHeight)"
.br
.ti -1c
.RI "void \fBsetNbSections\fP (int nbSections)"
.br
.ti -1c
.RI "void \fBsetFuelAssemblyIndex\fP (std::string index)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBSVBR100_FuelPin\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SVBR100_FuelPin::SVBR100_FuelPin (std::string name, \fBTMXInputParameters\fP * p)"

.PP
Definition at line \fB25\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SVBR100_FuelPin::createGeometry ()"

.PP
Definition at line \fB40\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.
.SS "void SVBR100_FuelPin::createMaterials ()"

.PP
Definition at line \fB116\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.
.SS "G4LogicalVolume * SVBR100_FuelPin::getMasterVolume ()"

.PP
Definition at line \fB321\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.
.SS "void SVBR100_FuelPin::setFuelAssemblyIndex (std::string index)"

.PP
Definition at line \fB314\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.
.SS "void SVBR100_FuelPin::setHalfHeight (G4double halfHeight)"

.PP
Definition at line \fB305\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.
.SS "void SVBR100_FuelPin::setNbSections (int nbSections)"

.PP
Definition at line \fB309\fP of file \fBSVBR100_FuelPin\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
