.TH "testBateman" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testBateman \- Definition of the \fBtestBateman\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testBateman\&.hh>\fP
.SH "Detailed Description"
.PP 
Definition of the \fBtestBateman\fP class\&. 
.PP
Definition at line \fB16\fP of file \fBtestBateman\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testBateman::testBateman ()"

.PP
Definition at line \fB16\fP of file \fBtestBateman\&.cc\fP\&.
.SS "testBateman::~testBateman ()"

.PP
Definition at line \fB225\fP of file \fBtestBateman\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
