.TH "TMXAbstractScoringAccumulable" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractScoringAccumulable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractScoring\fP\&.
.PP
Inherited by \fBCriticalThermalPower\fP, \fBTMXScoringDPA\fP, \fBTMXScoringDetectionChamber\fP, and \fBTMXScoringEnergyDeposited\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractScoringAccumulable\fP (\fBTMXInputParameters\fP *parameter, std::string name)"
.br
.ti -1c
.RI "void \fBRegisterAccumulable\fP (G4AccumulableManager *accumulableManager)"
.br
.ti -1c
.RI "unsigned long \fBGetNCount\fP () const"
.br
.ti -1c
.RI "long double \fBGetAccValue\fP () const"
.br
.ti -1c
.RI "long double \fBGetAccValueSquared\fP () const"
.br
.ti -1c
.RI "long double \fBGetAccValueError\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "G4Accumulable< unsigned long > \fBm_accCounter\fP"
.br
.ti -1c
.RI "G4Accumulable< long double > \fBm_accValue\fP"
.br
.ti -1c
.RI "G4Accumulable< long double > \fBm_accValueSquared\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBTMXAbstractScoringAccumulable\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractScoringAccumulable::TMXAbstractScoringAccumulable (\fBTMXInputParameters\fP * parameter, std::string name)"

.PP
Definition at line \fB20\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SS "TMXAbstractScoringAccumulable::~TMXAbstractScoringAccumulable ()\fC [virtual]\fP"

.PP
Definition at line \fB27\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "long double TMXAbstractScoringAccumulable::GetAccValue () const"

.PP
Definition at line \fB46\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SS "long double TMXAbstractScoringAccumulable::GetAccValueError () const"

.PP
Definition at line \fB54\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SS "long double TMXAbstractScoringAccumulable::GetAccValueSquared () const"

.PP
Definition at line \fB50\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SS "unsigned long TMXAbstractScoringAccumulable::GetNCount () const"

.PP
Definition at line \fB42\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SS "void TMXAbstractScoringAccumulable::RegisterAccumulable (G4AccumulableManager * accumulableManager)"

.PP
Definition at line \fB33\fP of file \fBTMXAbstractScoringAccumulable\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "G4Accumulable<unsigned long> TMXAbstractScoringAccumulable::m_accCounter\fC [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBTMXAbstractScoringAccumulable\&.hh\fP\&.
.SS "G4Accumulable<long double> TMXAbstractScoringAccumulable::m_accValue\fC [protected]\fP"

.PP
Definition at line \fB42\fP of file \fBTMXAbstractScoringAccumulable\&.hh\fP\&.
.SS "G4Accumulable<long double> TMXAbstractScoringAccumulable::m_accValueSquared\fC [protected]\fP"

.PP
Definition at line \fB43\fP of file \fBTMXAbstractScoringAccumulable\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
