.TH "TMXAbstractScoringNtuple" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractScoringNtuple
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTMXScoringEverythingNNtuple\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractScoringNtuple\fP (\fBTMXInputParameters\fP *parameter, std::string name, std::string inputs, bool isScoringActivated)"
.br
.ti -1c
.RI "TNtuple * \fBgetNtuple\fP () const"
.br
.ti -1c
.RI "void \fBWrite\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "TNtuple * \fBm_ntuple\fP"
.br
.ti -1c
.RI "bool \fBm_isScoringActivated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBTMXAbstractScoringNtuple\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractScoringNtuple::TMXAbstractScoringNtuple (\fBTMXInputParameters\fP * parameter, std::string name, std::string inputs, bool isScoringActivated)"

.PP
Definition at line \fB22\fP of file \fBTMXAbstractScoringNtuple\&.cc\fP\&.
.SS "TMXAbstractScoringNtuple::~TMXAbstractScoringNtuple ()\fC [virtual]\fP"

.PP
Definition at line \fB39\fP of file \fBTMXAbstractScoringNtuple\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "TNtuple * TMXAbstractScoringNtuple::getNtuple () const"

.PP
Definition at line \fB45\fP of file \fBTMXAbstractScoringNtuple\&.cc\fP\&.
.SS "void TMXAbstractScoringNtuple::Write ()"

.PP
Definition at line \fB52\fP of file \fBTMXAbstractScoringNtuple\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TMXAbstractScoringNtuple::m_isScoringActivated\fC [protected]\fP"

.PP
Definition at line \fB49\fP of file \fBTMXAbstractScoringNtuple\&.hh\fP\&.
.SS "TNtuple* TMXAbstractScoringNtuple::m_ntuple\fC [protected]\fP"

.PP
Definition at line \fB48\fP of file \fBTMXAbstractScoringNtuple\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
