.TH "TMXAbstractScoring" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractScoring
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserParallelWorld\&.
.PP
Inherited by \fBTMXAbstractScoringAccumulable\fP, \fBTMXAbstractScoringMap\fP, \fBTMXAbstractScoringSurface\fP, \fBTMXAbstractScoringSurface\fP, \fBTMXAbstractScoringSurface\fP, \fBTMXAbstractScoringSurface\fP, \fBTMXAbstractScoringSurface\fP, \fBTMXAbstractScoringVolume\fP, \fBTMXAbstractScoringVolume\fP, \fBTMXAbstractScoringVolume\fP, \fBTMXAbstractScoringVolume\fP, \fBTMXAbstractScoringVolume\fP, \fBTMXScoringPowerDensityMap\fP, \fBTMXScoringPowerDensityMap\fP, \fBTMXScoringPowerDensityMap\fP, and \fBTMXScoringPowerDensityMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractScoring\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH1\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH2\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildPVDaughters\fP (std::unordered_map< std::string, std::string > m_mapPV)"
.br
.ti -1c
.RI "virtual void \fBscore\fP (const G4Step *theStep)=0"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH1\fP (int id)"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH2\fP (int id)"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH1\fP ()"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH2\fP ()"
.br
.ti -1c
.RI "G4double \fBgetKineticEnergy_eV\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetPVUnionNames\fP (std::string PVUnionNames)"
.br
.ti -1c
.RI "std::string \fBgetPVScorer\fP (std::string mapIndex)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetRecursivePV\fP (G4VPhysicalVolume *PV)"
.br
.ti -1c
.RI "bool \fBisRecursivePV\fP (std::string PVScorer)"
.br
.ti -1c
.RI "virtual void \fBprintAverage\fP () const =0"
.br
.ti -1c
.RI "\fBTMXAbstractScoring\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH1\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH2\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildPVDaughters\fP (std::unordered_map< std::string, std::string > m_mapPV)"
.br
.ti -1c
.RI "virtual void \fBscore\fP (const G4Step *theStep)=0"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH1\fP (int id)"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH2\fP (int id)"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH1\fP ()"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH2\fP ()"
.br
.ti -1c
.RI "G4double \fBgetKineticEnergy_eV\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetPVUnionNames\fP (std::string PVUnionNames)"
.br
.ti -1c
.RI "std::string \fBgetPVScorer\fP (std::string mapIndex)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetRecursivePV\fP (G4VPhysicalVolume *PV)"
.br
.ti -1c
.RI "bool \fBisRecursivePV\fP (std::string PVScorer)"
.br
.ti -1c
.RI "virtual void \fBprintAverage\fP () const =0"
.br
.ti -1c
.RI "\fBTMXAbstractScoring\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH1\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH2\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildPVDaughters\fP (std::unordered_map< std::string, std::string > m_mapPV)"
.br
.ti -1c
.RI "virtual void \fBscore\fP (const G4Step *theStep)=0"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH1\fP (int id)"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH2\fP (int id)"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH1\fP ()"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH2\fP ()"
.br
.ti -1c
.RI "G4double \fBgetKineticEnergy_eV\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetPVUnionNames\fP (std::string PVUnionNames)"
.br
.ti -1c
.RI "std::string \fBgetPVScorer\fP (std::string mapIndex)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetRecursivePV\fP (G4VPhysicalVolume *PV)"
.br
.ti -1c
.RI "bool \fBisRecursivePV\fP (std::string PVScorer)"
.br
.ti -1c
.RI "virtual void \fBprintAverage\fP () const =0"
.br
.ti -1c
.RI "\fBTMXAbstractScoring\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH1\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildHistogramsH2\fP (std::string quantity)"
.br
.ti -1c
.RI "void \fBbuildPVDaughters\fP (std::unordered_map< std::string, std::string > m_mapPV)"
.br
.ti -1c
.RI "virtual void \fBscore\fP (const G4Step *theStep)=0"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH1\fP (int id)"
.br
.ti -1c
.RI "void \fBsetFirstIdHistogramH2\fP (int id)"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH1\fP ()"
.br
.ti -1c
.RI "int \fBgetLastIdHistogramH2\fP ()"
.br
.ti -1c
.RI "G4double \fBgetKineticEnergy_eV\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetPVUnionNames\fP (std::string PVUnionNames)"
.br
.ti -1c
.RI "std::string \fBgetPVScorer\fP (std::string mapIndex)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetRecursivePV\fP (G4VPhysicalVolume *PV)"
.br
.ti -1c
.RI "bool \fBisRecursivePV\fP (std::string PVScorer)"
.br
.ti -1c
.RI "virtual void \fBprintAverage\fP () const =0"
.br
.ti -1c
.RI "\fBTMXAbstractScoring\fP (\fBTMXInputParameters\fP *parameter, std::string name)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBConstruct\fP ()"
.br
.ti -1c
.RI "void \fBbuildParallelScoringVolumes\fP ()"
.br
.ti -1c
.RI "void \fBbuildPVDaughters\fP ()"
.br
.ti -1c
.RI "virtual void \fBscore\fP (const G4Step *theStep)=0"
.br
.ti -1c
.RI "G4double \fBgetKineticEnergy_eV\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetRecursivePV\fP (G4VPhysicalVolume *PV)"
.br
.ti -1c
.RI "TH1D * \fBGetTH1D\fP () const"
.br
.ti -1c
.RI "TH2D * \fBGetTH2D\fP () const"
.br
.ti -1c
.RI "std::string \fBGetName\fP () const"
.br
.ti -1c
.RI "void \fBSetParticleToScore\fP (std::string particle)"
.br
.ti -1c
.RI "void \fBSetPVtoScore\fP (std::string PVtoScore)"
.br
.ti -1c
.RI "void \fBSetTH1D\fP (int nbin, double min, double max, bool isSumw2, bool isLogX=false)"
.br
.ti -1c
.RI "void \fBSetTH2D\fP (int nbinX, double minX, double maxX, int nbinY, double minY, double maxY, bool isSumw2)"
.br
.ti -1c
.RI "void \fBSetTH2D\fP (std::vector< double > binning, bool isSumw2)"
.br
.ti -1c
.RI "void \fBAddHistograms\fP (\fBTMXAbstractScoring\fP *AbstractScoring)"
.br
.ti -1c
.RI "void \fBAddToRootArray\fP (TObjArray *histogramRootList) const"
.br
.ti -1c
.RI "bool \fBIsInParticleAndPVconditions\fP (const G4Step *theStep) const"
.br
.ti -1c
.RI "bool \fBIsInPVconditions\fP (const G4Step *theStep) const"
.br
.ti -1c
.RI "void \fBWrite\fP ()"
.br
.ti -1c
.RI "virtual void \fBprintAverage\fP () const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTMXInputParameters\fP * \fBm_p\fP"
.br
.ti -1c
.RI "int \fBm_firstIdHistogramH1\fP"
.br
.ti -1c
.RI "int \fBm_firstIdHistogramH2\fP"
.br
.ti -1c
.RI "int \fBm_lastIdHistogramH1\fP"
.br
.ti -1c
.RI "int \fBm_lastIdHistogramH2\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, int > \fBm_mapPVHisto1DId\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, int > \fBm_mapPVHisto2DId\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::string > \fBm_mapPVParticle\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< double > > \fBm_mapPVHisto2DBinning\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::string > \fBm_mapPVHisto2DBinningUnit\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::vector< std::string > > \fBm_mapPVDaughters\fP"
.br
.ti -1c
.RI "std::string \fBm_name\fP"
.br
.ti -1c
.RI "TH1D * \fBm_TH1D\fP"
.br
.ti -1c
.RI "TH2D * \fBm_TH2D\fP"
.br
.ti -1c
.RI "std::vector< double > \fBm_binning\fP"
.br
.ti -1c
.RI "bool \fBm_isRecursivePV\fP"
.br
.ti -1c
.RI "std::string \fBm_particleToScore\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBm_vectorPVtoScore\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBm_vectorPVDaughtersToScore\fP"
.br
.ti -1c
.RI "G4VSolid * \fBsScoringMesh\fP"
.br
.ti -1c
.RI "G4LogicalVolume * \fBlScoringMesh\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, G4LogicalVolume * > \fBm_mapPVSensitiveLV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractScoring::TMXAbstractScoring (\fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB33\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "TMXAbstractScoring::~TMXAbstractScoring ()\fC [virtual]\fP"

.PP
Definition at line \fB50\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "TMXAbstractScoring::TMXAbstractScoring (\fBTMXInputParameters\fP * parameter, std::string name)"

.PP
Definition at line \fB34\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXAbstractScoring::AddHistograms (\fBTMXAbstractScoring\fP * AbstractScoring)"

.PP
Definition at line \fB252\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::AddToRootArray (TObjArray * histogramRootList) const"

.PP
Definition at line \fB260\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::buildHistogramsH1 (std::string quantity)"

.PP
Definition at line \fB56\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::buildHistogramsH2 (std::string quantity)"

.PP
Definition at line \fB71\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::buildParallelScoringVolumes ()"

.PP
Definition at line \fB71\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::buildPVDaughters ()"

.PP
Definition at line \fB119\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::buildPVDaughters (std::unordered_map< std::string, std::string > m_mapPV)"

.PP
Definition at line \fB96\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::Construct ()"

.PP
Definition at line \fB67\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "G4double TMXAbstractScoring::getKineticEnergy_eV (const G4Step * theStep)"

.PP
Definition at line \fB142\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "int TMXAbstractScoring::getLastIdHistogramH1 ()"

.PP
Definition at line \fB134\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "int TMXAbstractScoring::getLastIdHistogramH2 ()"

.PP
Definition at line \fB138\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "std::string TMXAbstractScoring::GetName () const"

.PP
Definition at line \fB189\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "std::string TMXAbstractScoring::getPVScorer (std::string mapIndex)"

.PP
Definition at line \fB165\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "std::vector< std::string > TMXAbstractScoring::getPVUnionNames (std::string PVUnionNames)"

.PP
Definition at line \fB150\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "std::vector< std::string > TMXAbstractScoring::getRecursivePV (G4VPhysicalVolume * PV)"

.PP
Definition at line \fB170\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "TH1D * TMXAbstractScoring::GetTH1D () const"

.PP
Definition at line \fB181\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "TH2D * TMXAbstractScoring::GetTH2D () const"

.PP
Definition at line \fB185\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::Initialize ()"

.PP
Definition at line \fB60\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "bool TMXAbstractScoring::IsInParticleAndPVconditions (const G4Step * theStep) const"

.PP
Definition at line \fB276\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "bool TMXAbstractScoring::IsInPVconditions (const G4Step * theStep) const"

.PP
Definition at line \fB289\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "bool TMXAbstractScoring::isRecursivePV (std::string PVScorer)"

.PP
Definition at line \fB190\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::setFirstIdHistogramH1 (int id)"

.PP
Definition at line \fB123\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::setFirstIdHistogramH2 (int id)"

.PP
Definition at line \fB127\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::SetParticleToScore (std::string particle)"

.PP
Definition at line \fB201\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::SetPVtoScore (std::string PVtoScore)"

.PP
Definition at line \fB205\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::SetTH1D (int nbin, double min, double max, bool isSumw2, bool isLogX = \fCfalse\fP)"

.PP
Definition at line \fB221\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::SetTH2D (int nbinX, double minX, double maxX, int nbinY, double minY, double maxY, bool isSumw2)"

.PP
Definition at line \fB239\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::SetTH2D (std::vector< double > binning, bool isSumw2)"

.PP
Definition at line \fB245\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SS "void TMXAbstractScoring::Write ()"

.PP
Definition at line \fB371\fP of file \fBTMXAbstractScoring\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "G4LogicalVolume* TMXAbstractScoring::lScoringMesh\fC [protected]\fP"

.PP
Definition at line \fB101\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::vector<double> TMXAbstractScoring::m_binning\fC [protected]\fP"

.PP
Definition at line \fB93\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "int TMXAbstractScoring::m_firstIdHistogramH1\fC [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "int TMXAbstractScoring::m_firstIdHistogramH2\fC [protected]\fP"

.PP
Definition at line \fB69\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "bool TMXAbstractScoring::m_isRecursivePV\fC [protected]\fP"

.PP
Definition at line \fB94\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "int TMXAbstractScoring::m_lastIdHistogramH1\fC [protected]\fP"

.PP
Definition at line \fB70\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "int TMXAbstractScoring::m_lastIdHistogramH2\fC [protected]\fP"

.PP
Definition at line \fB71\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map< std::string, std::vector< std::string > > TMXAbstractScoring::m_mapPVDaughters\fC [protected]\fP"

.PP
Definition at line \fB79\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map< std::string, int > TMXAbstractScoring::m_mapPVHisto1DId\fC [protected]\fP"

.PP
Definition at line \fB74\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map< std::string, std::vector< double > > TMXAbstractScoring::m_mapPVHisto2DBinning\fC [protected]\fP"

.PP
Definition at line \fB77\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map< std::string, std::string > TMXAbstractScoring::m_mapPVHisto2DBinningUnit\fC [protected]\fP"

.PP
Definition at line \fB78\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map< std::string, int > TMXAbstractScoring::m_mapPVHisto2DId\fC [protected]\fP"

.PP
Definition at line \fB75\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map< std::string, std::string > TMXAbstractScoring::m_mapPVParticle\fC [protected]\fP"

.PP
Definition at line \fB76\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::unordered_map<std::string, G4LogicalVolume*> TMXAbstractScoring::m_mapPVSensitiveLV\fC [protected]\fP"

.PP
Definition at line \fB102\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::string TMXAbstractScoring::m_name\fC [protected]\fP"

.PP
Definition at line \fB90\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "\fBTMXInputParameters\fP * TMXAbstractScoring::m_p\fC [protected]\fP"

.PP
Definition at line \fB67\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::string TMXAbstractScoring::m_particleToScore\fC [protected]\fP"

.PP
Definition at line \fB95\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "TH1D* TMXAbstractScoring::m_TH1D\fC [protected]\fP"

.PP
Definition at line \fB91\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "TH2D* TMXAbstractScoring::m_TH2D\fC [protected]\fP"

.PP
Definition at line \fB92\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::vector<std::string> TMXAbstractScoring::m_vectorPVDaughtersToScore\fC [protected]\fP"

.PP
Definition at line \fB97\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "std::vector<std::string> TMXAbstractScoring::m_vectorPVtoScore\fC [protected]\fP"

.PP
Definition at line \fB96\fP of file \fBTMXAbstractScoring\&.hh\fP\&.
.SS "G4VSolid* TMXAbstractScoring::sScoringMesh\fC [protected]\fP"

.PP
Definition at line \fB100\fP of file \fBTMXAbstractScoring\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
