.TH "TMXAbstractFuelAssembly" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractFuelAssembly
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSVBR100_FuelAssembly\fP, \fBSVBR100_FuelAssembly\fP, \fBSVBR100_FuelAssembly\fP, \fBSVBR100_FuelAssembly\fP, \fBSVBR100_FuelAssembly\fP, \fBTMXFuelAssemblyVVRM2\fP, \fBTMXFuelAssemblyVVRM2\fP, \fBTMXFuelAssemblyVVRM2\fP, \fBTMXFuelAssemblyVVRM2\fP, \fBTMXFuelAssemblyVVRM2\fP, \fBTMXFuelIRT4M8T\fP, \fBTMXFuelIRT4M8T\fP, \fBTMXFuelIRT4M8T\fP, \fBTMXFuelIRT4M8T\fP, \fBTMXFuelIRT4M8T\fP, \fBTMXReflectorKIPT\fP, \fBTMXReflectorKIPT\fP, \fBTMXReflectorKIPT\fP, \fBTMXReflectorKIPT\fP, and \fBTMXReflectorKIPT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractFuelAssembly\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBgetSolids\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetFuelLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCladLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetWaterLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAbsorLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCladMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetAbsorMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractFuelAssembly\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBgetSolids\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetFuelLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCladLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetWaterLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAbsorLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCladMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetAbsorMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractFuelAssembly\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBgetSolids\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetFuelLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCladLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetWaterLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAbsorLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCladMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetAbsorMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractFuelAssembly\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBgetSolids\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetFuelLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCladLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetWaterLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAbsorLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCladMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetAbsorMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractFuelAssembly\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBgetSolids\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetFuelLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCladLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetWaterLogicalVolumes\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAbsorLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCladMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetFuelMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetWaterMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetAbsorMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateGeometry\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_assemblyName\fP"
.br
.ti -1c
.RI "\fBTMXInputParameters\fP * \fBm_p\fP"
.br
.ti -1c
.RI "G4double \fBm_rodInsertion\fP"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBm_Solids\fP"
.br
.ti -1c
.RI "G4LogicalVolume * \fBm_masterVolume\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_fuelLogicalVolumes\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_cladLogicalVolumes\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_waterLogicalVolumes\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_absorLogicalVolumes\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_CladMaterial\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_FuelMaterial\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_WaterMaterial\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_AbsorMaterial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractFuelAssembly::TMXAbstractFuelAssembly (const std::string & FuelAssemblyName, \fBTMXInputParameters\fP * parameters, G4double rodInsertion = \fC0\fP)"

.PP
Definition at line \fB42\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "TMXAbstractFuelAssembly::~TMXAbstractFuelAssembly ()\fC [virtual]\fP"

.PP
Definition at line \fB51\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXAbstractFuelAssembly::createGeometry ()\fC [virtual]\fP"

.PP
Definition at line \fB83\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "void TMXAbstractFuelAssembly::createMaterial ()\fC [virtual]\fP"

.PP
Definition at line \fB79\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::getAbsorLogicalVolumes ()"

.PP
Definition at line \fB106\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::getAbsorMaterial ()"

.PP
Definition at line \fB136\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::getCladLogicalVolumes ()"

.PP
Definition at line \fB96\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::getCladMaterial ()"

.PP
Definition at line \fB121\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::getFuelLogicalVolumes ()"

.PP
Definition at line \fB91\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::getFuelMaterial ()"

.PP
Definition at line \fB126\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "G4LogicalVolume * TMXAbstractFuelAssembly::getMasterVolume ()"

.PP
Definition at line \fB116\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "std::vector< G4VSolid * > TMXAbstractFuelAssembly::getSolids ()"

.PP
Definition at line \fB111\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::getWaterLogicalVolumes ()"

.PP
Definition at line \fB101\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::getWaterMaterial ()"

.PP
Definition at line \fB131\fP of file \fBTMXAbstractFuelAssembly\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::m_absorLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB85\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::m_AbsorMaterial\fC [protected]\fP"

.PP
Definition at line \fB93\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "std::string TMXAbstractFuelAssembly::m_assemblyName\fC [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::m_cladLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB83\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::m_CladMaterial\fC [protected]\fP"

.PP
Definition at line \fB90\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::m_fuelLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB82\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::m_FuelMaterial\fC [protected]\fP"

.PP
Definition at line \fB91\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "G4LogicalVolume * TMXAbstractFuelAssembly::m_masterVolume\fC [protected]\fP"

.PP
Definition at line \fB80\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "\fBTMXInputParameters\fP * TMXAbstractFuelAssembly::m_p\fC [protected]\fP"

.PP
Definition at line \fB69\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "G4double TMXAbstractFuelAssembly::m_rodInsertion\fC [protected]\fP"

.PP
Definition at line \fB70\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "std::vector< G4VSolid * > TMXAbstractFuelAssembly::m_Solids\fC [protected]\fP"

.PP
Definition at line \fB75\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractFuelAssembly::m_waterLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB84\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractFuelAssembly::m_WaterMaterial\fC [protected]\fP"

.PP
Definition at line \fB92\fP of file \fBTMXAbstractFuelAssembly\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
