.TH "TMXAbstractCore" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractCore
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSVBR100_Core\fP, \fBSVBR100_Core\fP, \fBSVBR100_Core\fP, \fBSVBR100_Core\fP, \fBSVBR100_Core\fP, \fBTMXCoreKIPT\fP, \fBTMXCoreKIPT\fP, \fBTMXCoreKIPT\fP, \fBTMXCoreKIPT\fP, and \fBTMXCoreKIPT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractCore\fP (const std::string &, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "G4double \fBgetPitch\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAssemblyList\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double)"
.br
.ti -1c
.RI "void \fBsetAssemblyList\fP (std::vector< G4LogicalVolume * >)"
.br
.ti -1c
.RI "void \fBaddAssemblyToList\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXAbstractCore\fP (const std::string &, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "G4double \fBgetPitch\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAssemblyList\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double)"
.br
.ti -1c
.RI "void \fBsetAssemblyList\fP (std::vector< G4LogicalVolume * >)"
.br
.ti -1c
.RI "void \fBaddAssemblyToList\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXAbstractCore\fP (const std::string &, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "G4double \fBgetPitch\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAssemblyList\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double)"
.br
.ti -1c
.RI "void \fBsetAssemblyList\fP (std::vector< G4LogicalVolume * >)"
.br
.ti -1c
.RI "void \fBaddAssemblyToList\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXAbstractCore\fP (const std::string &, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "G4double \fBgetPitch\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAssemblyList\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double)"
.br
.ti -1c
.RI "void \fBsetAssemblyList\fP (std::vector< G4LogicalVolume * >)"
.br
.ti -1c
.RI "void \fBaddAssemblyToList\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXAbstractCore\fP (const std::string &, \fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "G4double \fBgetPitch\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetAssemblyList\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double)"
.br
.ti -1c
.RI "void \fBsetAssemblyList\fP (std::vector< G4LogicalVolume * >)"
.br
.ti -1c
.RI "void \fBaddAssemblyToList\fP (G4LogicalVolume *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_coreName\fP"
.br
.ti -1c
.RI "\fBTMXInputParameters\fP * \fBm_p\fP"
.br
.ti -1c
.RI "G4LogicalVolume * \fBm_masterVolume\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_reflectMaterial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBTMXAbstractCore\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractCore::TMXAbstractCore ()"

.PP
Definition at line \fB53\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SS "TMXAbstractCore::TMXAbstractCore (const std::string & coreName, \fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB58\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXAbstractCore::AddAssembliesInCore ()"

.PP
Definition at line \fB70\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SS "void TMXAbstractCore::addAssemblyToList (G4LogicalVolume * assembly)"

.PP
Definition at line \fB143\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXAbstractCore::getAssemblyList ()"

.PP
Definition at line \fB124\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SS "G4double TMXAbstractCore::getPitch ()"

.PP
Definition at line \fB119\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SS "void TMXAbstractCore::setAssemblyList (std::vector< G4LogicalVolume * > list)"

.PP
Definition at line \fB138\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SS "void TMXAbstractCore::setPitch (G4double pitch)"

.PP
Definition at line \fB133\fP of file \fBTMXAbstractCore\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string TMXAbstractCore::m_coreName\fC [protected]\fP"

.PP
Definition at line \fB46\fP of file \fBTMXAbstractCore\&.hh\fP\&.
.SS "G4LogicalVolume * TMXAbstractCore::m_masterVolume\fC [protected]\fP"

.PP
Definition at line \fB49\fP of file \fBTMXAbstractCore\&.hh\fP\&.
.SS "\fBTMXInputParameters\fP * TMXAbstractCore::m_p\fC [protected]\fP"

.PP
Definition at line \fB47\fP of file \fBTMXAbstractCore\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXAbstractCore::m_reflectMaterial\fC [protected]\fP"

.PP
Definition at line \fB51\fP of file \fBTMXAbstractCore\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
