.TH "TMXAbstractScoringSurface" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractScoringSurface
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractScoring\fP, \fBTMXAbstractScoring\fP, \fBTMXAbstractScoring\fP, \fBTMXAbstractScoring\fP, and \fBTMXAbstractScoring\fP\&.
.PP
Inherited by \fBTMXScoringSurfaceCurrentSpectrum\fP, \fBTMXScoringSurfaceCurrentSpectrum\fP, \fBTMXScoringSurfaceCurrentSpectrum\fP, \fBTMXScoringSurfaceCurrentSpectrum\fP, \fBTMXScoringSurfaceCurrentSpectrum\fP, \fBTMXScoringSurfaceFluenceSpectrum\fP, \fBTMXScoringSurfaceFluenceSpectrum\fP, \fBTMXScoringSurfaceFluenceSpectrum\fP, \fBTMXScoringSurfaceFluenceSpectrum\fP, and \fBTMXScoringSurfaceFluenceSpectrum\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractScoringSurface\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVSurface\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractScoringSurface\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVSurface\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractScoringSurface\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVSurface\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractScoringSurface\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVSurface\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractScoringSurface\fP (\fBTMXInputParameters\fP *parameter, std::string name)"
.br
.ti -1c
.RI "void \fBbuildMapPVSurface\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::unordered_map< std::string, std::string > \fBm_mapPVOrientation\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, G4double > \fBm_mapPVSurface\fP"
.br
.ti -1c
.RI "std::string \fBm_orientation\fP"
.br
.ti -1c
.RI "G4double \fBm_surface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBTMXAbstractScoringSurface\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractScoringSurface::TMXAbstractScoringSurface (\fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB27\fP of file \fBTMXAbstractScoringSurface\&.cc\fP\&.
.SS "TMXAbstractScoringSurface::~TMXAbstractScoringSurface ()\fC [virtual]\fP"

.PP
Definition at line \fB34\fP of file \fBTMXAbstractScoringSurface\&.cc\fP\&.
.SS "TMXAbstractScoringSurface::TMXAbstractScoringSurface (\fBTMXInputParameters\fP * parameter, std::string name)"

.PP
Definition at line \fB28\fP of file \fBTMXAbstractScoringSurface\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXAbstractScoringSurface::buildMapPVSurface ()"

.PP
Definition at line \fB40\fP of file \fBTMXAbstractScoringSurface\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::unordered_map< std::string, std::string > TMXAbstractScoringSurface::m_mapPVOrientation\fC [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBTMXAbstractScoringSurface\&.hh\fP\&.
.SS "std::unordered_map< std::string, G4double > TMXAbstractScoringSurface::m_mapPVSurface\fC [protected]\fP"

.PP
Definition at line \fB29\fP of file \fBTMXAbstractScoringSurface\&.hh\fP\&.
.SS "std::string TMXAbstractScoringSurface::m_orientation\fC [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBTMXAbstractScoringSurface\&.hh\fP\&.
.SS "G4double TMXAbstractScoringSurface::m_surface\fC [protected]\fP"

.PP
Definition at line \fB29\fP of file \fBTMXAbstractScoringSurface\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
