.TH "TMXAbstractScoringMap" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXAbstractScoringMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractScoring\fP\&.
.PP
Inherited by \fBTMXScoringFluenceMap\fP, and \fBTMXScoringPowerDensityMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXAbstractScoringMap\fP (\fBTMXInputParameters\fP *parameter, std::string name)"
.br
.ti -1c
.RI "void \fBscoreMap\fP (const G4Step *theStep, G4double value, bool isPerCubicVolume)"
.br
.ti -1c
.RI "void \fBscorePerMesh\fP (const G4Step *theStep, G4double value, bool isPerCubicVolume)"
.br
.ti -1c
.RI "void \fBSetMeshType\fP (std::string meshType)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetRingVolume\fP (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)"
.br
.ti -1c
.RI "double \fBgetCubicVolume\fP (double xBin, double xMin, double xMax, double yBin, double yMin, double yMax, double zBin, double zMin, double zMax)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBTMXAbstractScoringMap\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXAbstractScoringMap::TMXAbstractScoringMap (\fBTMXInputParameters\fP * parameter, std::string name)"

.PP
Definition at line \fB23\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.
.SS "TMXAbstractScoringMap::~TMXAbstractScoringMap ()\fC [virtual]\fP"

.PP
Definition at line \fB33\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double TMXAbstractScoringMap::getCubicVolume (double xBin, double xMin, double xMax, double yBin, double yMin, double yMax, double zBin, double zMin, double zMax)\fC [protected]\fP"

.PP
Definition at line \fB134\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.
.SS "double TMXAbstractScoringMap::getRingVolume (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)\fC [protected]\fP"

.PP
Definition at line \fB127\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.
.SS "void TMXAbstractScoringMap::scoreMap (const G4Step * theStep, G4double value, bool isPerCubicVolume)"

.PP
Definition at line \fB39\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.
.SS "void TMXAbstractScoringMap::scorePerMesh (const G4Step * theStep, G4double value, bool isPerCubicVolume)"

.PP
Definition at line \fB45\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.
.SS "void TMXAbstractScoringMap::SetMeshType (std::string meshType)"

.PP
Definition at line \fB120\fP of file \fBTMXAbstractScoringMap\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
