.TH "TMXBatemanDecay" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXBatemanDecay \- Definition of the \fBTMXBatemanDecay\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXBatemanDecay\&.hh>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTransmutedElement\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXBatemanDecay\fP ()"
.br
.RI "Implementation of the \fBTMXBatemanDecay\fP class\&. "
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBAddTransmutedElement\fP (std::vector< \fBTMXBatemanDecay::TransmutedElement\fP > &vectorTransmutedElement)"
.br
.ti -1c
.RI "void \fBAddTransmutedSrcElem\fP (std::vector< \fBTMXBatemanDecay::TransmutedElement\fP > &vectorSourceElement)"
.br
.ti -1c
.RI "void \fBClearMapTransmutedElement\fP ()"
.br
.ti -1c
.RI "void \fBClearMapTransmutedSrcElem\fP ()"
.br
.ti -1c
.RI "void \fBDumpTransmutedElements\fP ()"
.br
.ti -1c
.RI "void \fBConstructMapN_0\fP (int IZA, long double N_0)"
.br
.ti -1c
.RI "void \fBConsiderTransmutedElements\fP (std::string LogicVolumeName)"
.br
.ti -1c
.RI "void \fBSumTransmutedElements\fP (std::string LogicVolumeName)"
.br
.ti -1c
.RI "void \fBClearMapN_0\fP ()"
.br
.ti -1c
.RI "void \fBClearMapS_0\fP ()"
.br
.ti -1c
.RI "void \fBConstructMapNt\fP (int IZA, long double Nt)"
.br
.ti -1c
.RI "void \fBClearMapNt\fP ()"
.br
.ti -1c
.RI "std::unordered_map< int, long double > \fBGetMapNt\fP ()"
.br
.ti -1c
.RI "void \fBConstructChain\fP (int IZA, std::string LogicVolumeName)"
.br
.ti -1c
.RI "void \fBConstructChainNoTransmutation\fP (int IZA)"
.br
.ti -1c
.RI "void \fBDumpStoredChains\fP ()"
.br
.ti -1c
.RI "void \fBCalculateDecayNt\fP (double t)"
.br
.ti -1c
.RI "void \fBCalculateDecayNtNoTransmutation\fP (double t, std::string LogicVolumeName)"
.br
.ti -1c
.RI "void \fBCalculateSourceNt\fP (double t, std::string LogicVolumeName)"
.br
.ti -1c
.RI "void \fBCalculateSourceNtNoTransmutation\fP (double t)"
.br
.ti -1c
.RI "void \fBMultiplyTransmutedElem\fP (long double factor)"
.br
.ti -1c
.RI "void \fBMultiplyTransmutedElem\fP (long double factor, std::string LVName)"
.br
.ti -1c
.RI "void \fBNormalizeTransmutedElem\fP (int IZA, std::string LogicVolumeName)"
.br
.ti -1c
.RI "long double \fBGetN_0\fP (int IZA)"
.br
.ti -1c
.RI "void \fBClearMapChains\fP ()"
.br
.ti -1c
.RI "void \fBdecayNuclideVector\fP (std::map< int, double > &, std::map< int, int >, double, double)"
.br
.ti -1c
.RI "void \fBCalculateSourceNtNoTransmutation2\fP (std::map< int, int >, double, double, std::map< int, double > &, bool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXBatemanDecay\fP class\&. 
.PP
Definition at line \fB31\fP of file \fBTMXBatemanDecay\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXBatemanDecay::TMXBatemanDecay ()"

.PP
Implementation of the \fBTMXBatemanDecay\fP class\&. 
.PP
Definition at line \fB20\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "TMXBatemanDecay::~TMXBatemanDecay ()"

.PP
Definition at line \fB30\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXBatemanDecay::AddTransmutedElement (std::vector< \fBTMXBatemanDecay::TransmutedElement\fP > & vectorTransmutedElement)"

.PP
Definition at line \fB46\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::AddTransmutedSrcElem (std::vector< \fBTMXBatemanDecay::TransmutedElement\fP > & vectorSourceElement)"

.PP
Definition at line \fB50\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::CalculateDecayNt (double t)"

.PP
Definition at line \fB420\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::CalculateDecayNtNoTransmutation (double t, std::string LogicVolumeName)"

.PP
Definition at line \fB668\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::CalculateSourceNt (double t, std::string LogicVolumeName)"

.PP
Definition at line \fB798\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::CalculateSourceNtNoTransmutation (double t)"

.PP
Definition at line \fB745\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::CalculateSourceNtNoTransmutation2 (std::map< int, int > sourceTerm, double irradiationPeriod, double scalingFactor, std::map< int, double > & nuclideVectorUpdated, bool avoidDecay)"

.PP
Definition at line \fB559\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ClearMapChains ()"

.PP
Definition at line \fB42\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ClearMapN_0 ()"

.PP
Definition at line \fB173\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ClearMapNt ()"

.PP
Definition at line \fB188\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ClearMapS_0 ()"

.PP
Definition at line \fB178\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ClearMapTransmutedElement ()"

.PP
Definition at line \fB85\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ClearMapTransmutedSrcElem ()"

.PP
Definition at line \fB90\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ConsiderTransmutedElements (std::string LogicVolumeName)"

.PP
Definition at line \fB1031\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ConstructChain (int IZA, std::string LogicVolumeName = \fC''\fP)"

.PP
Definition at line \fB196\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ConstructChainNoTransmutation (int IZA)"

.PP
Definition at line \fB317\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ConstructMapN_0 (int IZA, long double N_0)"

.PP
Definition at line \fB111\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::ConstructMapNt (int IZA, long double Nt)"

.PP
Definition at line \fB183\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::decayNuclideVector (std::map< int, double > & nuclideVector, std::map< int, int > sourceTerm, double irradiationPeriod, double scalingFactor)"

.PP
Definition at line \fB484\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::DumpStoredChains ()"

.PP
Definition at line \fB402\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::DumpTransmutedElements ()"

.PP
Definition at line \fB95\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "std::unordered_map< int, long double > TMXBatemanDecay::GetMapNt ()"

.PP
Definition at line \fB121\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "long double TMXBatemanDecay::GetN_0 (int IZA)"

.PP
Definition at line \fB117\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::Initialize ()"

.PP
Definition at line \fB33\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::MultiplyTransmutedElem (long double factor)"

.PP
Definition at line \fB834\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::MultiplyTransmutedElem (long double factor, std::string LVName)"

.PP
Definition at line \fB854\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::NormalizeTransmutedElem (int IZA, std::string LogicVolumeName)"

.PP
Definition at line \fB955\fP of file \fBTMXBatemanDecay\&.cc\fP\&.
.SS "void TMXBatemanDecay::SumTransmutedElements (std::string LogicVolumeName)"

.PP
Definition at line \fB1006\fP of file \fBTMXBatemanDecay\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
