.TH "TMXBurnup" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXBurnup \- Definition of the \fBTMXBurnup\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXBurnup\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXBurnup\fP ()"
.br
.RI "Implementation of the \fBTMXBurnup\fP class\&. "
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBChangeMaterial\fP (\fBTMXInputParameters\fP &p, G4LogicalVolumeStore *LVStore, \fBTMXBatemanDecay\fP &batemanDecay, int i_step)"
.br
.ti -1c
.RI "void \fBConstructMapN0AndDecayChain\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBConstructMapN0WithTransmutedElem\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBCalculateNbElementsAndMass\fP (std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double &newMaterialMass)"
.br
.ti -1c
.RI "G4Material * \fBDefineNewMaterial\fP (std::string LVName, int i_step, G4Material *LVMaterial, std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double newMaterialMass)"
.br
.ti -1c
.RI "void \fBWriteResults\fP (std::string str_ROOTFileName)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step, \fBTMXMergeThreadsResults\fP ResultsFile)"
.br
.ti -1c
.RI "void \fBWriteDecayedResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBChangeMaterial\fP (\fBTMXInputParameters\fP &p, G4LogicalVolumeStore *LVStore, \fBTMXBatemanDecay\fP &batemanDecay, int i_step)"
.br
.ti -1c
.RI "void \fBConstructMapN0AndDecayChain\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBConstructMapN0WithTransmutedElem\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBCalculateNbElementsAndMass\fP (std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double &newMaterialMass)"
.br
.ti -1c
.RI "G4Material * \fBDefineNewMaterial\fP (std::string LVName, int i_step, G4Material *LVMaterial, std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double newMaterialMass)"
.br
.ti -1c
.RI "void \fBWriteResults\fP (std::string str_ROOTFileName)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step, \fBTMXMergeThreadsResults\fP ResultsFile)"
.br
.ti -1c
.RI "void \fBWriteDecayedResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBChangeMaterial\fP (\fBTMXInputParameters\fP &p, G4LogicalVolumeStore *LVStore, \fBTMXBatemanDecay\fP &batemanDecay, int i_step)"
.br
.ti -1c
.RI "void \fBConstructMapN0AndDecayChain\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBConstructMapN0WithTransmutedElem\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBCalculateNbElementsAndMass\fP (std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double &newMaterialMass)"
.br
.ti -1c
.RI "G4Material * \fBDefineNewMaterial\fP (std::string LVName, int i_step, G4Material *LVMaterial, std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double newMaterialMass)"
.br
.ti -1c
.RI "void \fBWriteResults\fP (std::string str_ROOTFileName)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step, \fBTMXMergeThreadsResults\fP ResultsFile)"
.br
.ti -1c
.RI "void \fBWriteDecayedResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBChangeMaterial\fP (\fBTMXInputParameters\fP &p, G4LogicalVolumeStore *LVStore, \fBTMXBatemanDecay\fP &batemanDecay, int i_step)"
.br
.ti -1c
.RI "void \fBConstructMapN0AndDecayChain\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBConstructMapN0WithTransmutedElem\fP (G4LogicalVolume *LV, int i_step, \fBTMXBatemanDecay\fP &batemanDecay)"
.br
.ti -1c
.RI "void \fBCalculateNbElementsAndMass\fP (std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double &newMaterialMass)"
.br
.ti -1c
.RI "G4Material * \fBDefineNewMaterial\fP (std::string LVName, int i_step, G4Material *LVMaterial, std::unordered_map< int, std::pair< int, long double > > &MassElement, std::map< int, long double > &MapNt, long double newMaterialMass)"
.br
.ti -1c
.RI "void \fBWriteResults\fP (std::string str_ROOTFileName)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.ti -1c
.RI "void \fBWriteResultsPerRun\fP (std::string str_ROOTFileName, int i_step, \fBTMXMergeThreadsResults\fP ResultsFile)"
.br
.ti -1c
.RI "void \fBWriteDecayedResultsPerRun\fP (std::string str_ROOTFileName, int i_step)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBFillvectorBurnupElement\fP (const G4Step *theStep, \fBEventAction\fP *eventAction, const G4Track *secondary)"
.br
.ti -1c
.RI "static void \fBFillvectorBurnupElement\fP (const G4Step *theStep, \fBEventAction\fP *eventAction, const G4Track *secondary)"
.br
.ti -1c
.RI "static void \fBFillvectorBurnupElement\fP (const G4Step *theStep, \fBEventAction\fP *eventAction, const G4Track *secondary)"
.br
.ti -1c
.RI "static void \fBFillvectorBurnupElement\fP (const G4Step *theStep, \fBEventAction\fP *eventAction, const G4Track *secondary)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXBurnup\fP class\&. 
.PP
Definition at line \fB34\fP of file \fBTMXBurnup\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXBurnup::TMXBurnup ()"

.PP
Implementation of the \fBTMXBurnup\fP class\&. 
.PP
Definition at line \fB26\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "TMXBurnup::~TMXBurnup ()"

.PP
Definition at line \fB30\fP of file \fBTMXBurnup\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXBurnup::CalculateNbElementsAndMass (std::unordered_map< int, std::pair< int, long double > > & MassElement, std::map< int, long double > & MapNt, long double & newMaterialMass)"

.PP
Definition at line \fB250\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::ChangeMaterial (\fBTMXInputParameters\fP & p, G4LogicalVolumeStore * LVStore, \fBTMXBatemanDecay\fP & batemanDecay, int i_step)"

.PP
Definition at line \fB39\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::ConstructMapN0AndDecayChain (G4LogicalVolume * LV, int i_step, \fBTMXBatemanDecay\fP & batemanDecay)"

.PP
Definition at line \fB192\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::ConstructMapN0WithTransmutedElem (G4LogicalVolume * LV, int i_step, \fBTMXBatemanDecay\fP & batemanDecay)"

.PP
Definition at line \fB223\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "G4Material * TMXBurnup::DefineNewMaterial (std::string LVName, int i_step, G4Material * LVMaterial, std::unordered_map< int, std::pair< int, long double > > & MassElement, std::map< int, long double > & MapNt, long double newMaterialMass)"

.PP
Definition at line \fB262\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::FillvectorBurnupElement (const G4Step * theStep, \fBEventAction\fP * eventAction, const G4Track * secondary)\fC [static]\fP"

.PP
Definition at line \fB413\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::Initialize ()"

.PP
Definition at line \fB33\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::WriteDecayedResultsPerRun (std::string str_ROOTFileName, int i_step)"

.PP
Definition at line \fB377\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::WriteResults (std::string str_ROOTFileName)"

.PP
Definition at line \fB310\fP of file \fBTMXBurnup\&.cc\fP\&.
.SS "void TMXBurnup::WriteResultsPerRun (std::string str_ROOTFileName, int i_step)"

.PP
Definition at line \fB335\fP of file \fBTMXBurnup\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
