.TH "TMXBeamPipeKIPT" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXBeamPipeKIPT
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, and \fBTMXAbstractBeamPipe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXBeamPipeKIPT\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBTMXBeamPipeKIPT\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXBeamPipeKIPT::TMXBeamPipeKIPT (\fBTMXInputParameters\fP * parameters, const std::string & BeamPipeAssemblyName)"

.PP
Definition at line \fB39\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SS "TMXBeamPipeKIPT::~TMXBeamPipeKIPT ()"

.PP
Definition at line \fB46\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXBeamPipeKIPT::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB48\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeBeamPipe (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB78\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeGeometry (bool overlap, G4ThreeVector * centerTarget, G4ThreeVector * beamDirection, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB70\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeVacuum (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB96\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeWindow (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB106\fP of file \fBTMXBeamPipeKIPT\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
