.TH "TMXBeamPipeRez3" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXBeamPipeRez3
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, and \fBTMXAbstractBeamPipe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXBeamPipeRez3\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (G4double)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeRez3\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (G4double)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeRez3\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (G4double)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeRez3\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (G4double)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeRez3\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (G4double)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBTMXBeamPipeRez3\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXBeamPipeRez3::TMXBeamPipeRez3 (\fBTMXInputParameters\fP * parameters, const std::string & BeamPipeAssemblyName)"

.PP
Definition at line \fB42\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "TMXBeamPipeRez3::~TMXBeamPipeRez3 ()"

.PP
Definition at line \fB49\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXBeamPipeRez3::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB81\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "void TMXBeamPipeRez3::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::createMaterial (G4double Kelvin_temperature)"

.PP
Definition at line \fB51\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "void TMXBeamPipeRez3::placeBeamPipe (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB112\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "void TMXBeamPipeRez3::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeGeometry (bool overlap, G4ThreeVector * centerTarget, G4ThreeVector * beamDirection, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB104\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "void TMXBeamPipeRez3::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeVacuum (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB135\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "void TMXBeamPipeRez3::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeWindow (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB145\fP of file \fBTMXBeamPipeRez3\&.cc\fP\&.
.SS "void TMXBeamPipeRez3::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeRez3::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
