.TH "TMXBeamPipeKIPT2" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXBeamPipeKIPT2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, \fBTMXAbstractBeamPipe\fP, and \fBTMXAbstractBeamPipe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXBeamPipeKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXBeamPipeKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceBeamPipe\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceVacuum\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceWindow\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "G4LogicalVolume * \fBm_masterVolume\fP"
.br
.ti -1c
.RI "G4LogicalVolume * \fBm_window\fP"
.br
.ti -1c
.RI "G4LogicalVolume * \fBm_pipeVoid\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_vacuumMaterial\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_tubeMaterial\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_windowMat\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXBeamPipeKIPT2::TMXBeamPipeKIPT2 (\fBTMXInputParameters\fP * parameters, const std::string & BeamPipeAssemblyName)"

.PP
Definition at line \fB41\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "TMXBeamPipeKIPT2::~TMXBeamPipeKIPT2 ()"

.PP
Definition at line \fB49\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXBeamPipeKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB51\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB71\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractBeamPipe\fP\&.
.SS "G4LogicalVolume * TMXBeamPipeKIPT2::getMasterVolume ()"

.PP
Definition at line \fB92\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB101\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeBeamPipe (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB97\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB105\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeVacuum (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.PP
Definition at line \fB109\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SS "void TMXBeamPipeKIPT2::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::placeWindow (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractBeamPipe\fP\&.
.SS "void TMXBeamPipeKIPT2::VisualisationConfig ()\fC [protected]\fP"

.PP
Definition at line \fB113\fP of file \fBTMXBeamPipeKIPT2\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "G4LogicalVolume * TMXBeamPipeKIPT2::m_masterVolume\fC [protected]\fP"

.PP
Definition at line \fB71\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.
.SS "G4LogicalVolume * TMXBeamPipeKIPT2::m_pipeVoid\fC [protected]\fP"

.PP
Definition at line \fB73\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXBeamPipeKIPT2::m_tubeMaterial\fC [protected]\fP"

.PP
Definition at line \fB80\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXBeamPipeKIPT2::m_vacuumMaterial\fC [protected]\fP"

.PP
Definition at line \fB79\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.
.SS "G4LogicalVolume * TMXBeamPipeKIPT2::m_window\fC [protected]\fP"

.PP
Definition at line \fB72\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXBeamPipeKIPT2::m_windowMat\fC [protected]\fP"

.PP
Definition at line \fB81\fP of file \fBTMXBeamPipeKIPT2\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
