.TH "TMXBatemanDecay::TransmutedElement" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXBatemanDecay::TransmutedElement
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBIZAmother\fP"
.br
.ti -1c
.RI "int \fBIZAdaughter\fP"
.br
.ti -1c
.RI "std::string \fBLogicVolumeName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBTMXBatemanDecay\&.hh\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int TMXBatemanDecay::TransmutedElement::IZAdaughter"

.PP
Definition at line \fB39\fP of file \fBTMXBatemanDecay\&.hh\fP\&.
.SS "int TMXBatemanDecay::TransmutedElement::IZAmother"

.PP
Definition at line \fB38\fP of file \fBTMXBatemanDecay\&.hh\fP\&.
.SS "std::string TMXBatemanDecay::TransmutedElement::LogicVolumeName"

.PP
Definition at line \fB40\fP of file \fBTMXBatemanDecay\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
