.TH "TMXCoreKIPT" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXCoreKIPT
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractCore\fP, \fBTMXAbstractCore\fP, \fBTMXAbstractCore\fP, \fBTMXAbstractCore\fP, and \fBTMXAbstractCore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXCoreKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, std::string latticeMapFile, \fBTMXNeutronSource\fP *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector, G4RotationMatrix *, G4LogicalVolume *, std::string latticeType)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4VSolid *subtracterSolid)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXCoreKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, std::string latticeMapFile, \fBTMXNeutronSource\fP *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector, G4RotationMatrix *, G4LogicalVolume *, std::string latticeType)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4VSolid *subtracterSolid)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXCoreKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, std::string latticeMapFile, \fBTMXNeutronSource\fP *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector, G4RotationMatrix *, G4LogicalVolume *, std::string latticeType)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4VSolid *subtracterSolid)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXCoreKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, std::string latticeMapFile, \fBTMXNeutronSource\fP *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector, G4RotationMatrix *, G4LogicalVolume *, std::string latticeType)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4VSolid *subtracterSolid)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXCoreKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, std::string latticeMapFile, \fBTMXNeutronSource\fP *)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector, G4RotationMatrix *, G4LogicalVolume *, std::string latticeType)"
.br
.ti -1c
.RI "void \fBAddAssembliesInCore\fP ()"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4VSolid *subtracterSolid)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBTMXCoreKIPT\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXCoreKIPT::TMXCoreKIPT (const std::string & coreName, \fBTMXInputParameters\fP * parameter, std::string latticeMapFile, \fBTMXNeutronSource\fP * sourceKipt)"

.PP
Definition at line \fB37\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXCoreKIPT::AddAssembliesInCore ()"

.PP
Definition at line \fB101\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "void TMXCoreKIPT::createGeometry ()"

.PP
Definition at line \fB63\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "void TMXCoreKIPT::createMaterial ()"

.PP
Definition at line \fB51\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "G4LogicalVolume * TMXCoreKIPT::getMasterVolume ()"

.PP
Definition at line \fB276\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "void TMXCoreKIPT::placeGeometry (bool overlap, G4ThreeVector position, G4RotationMatrix * rotation, G4LogicalVolume * masterVolume, std::string latticeType)"

.PP
Definition at line \fB153\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "void TMXCoreKIPT::subtract (G4LogicalVolume * subtracterLV)"

.PP
Definition at line \fB134\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "void TMXCoreKIPT::subtract (G4VSolid * subtracterSolid)"

.PP
Definition at line \fB144\fP of file \fBTMXCoreKIPT\&.cc\fP\&.
.SS "void TMXCoreKIPT::VisualisationConfig ()"

.PP
Definition at line \fB234\fP of file \fBTMXCoreKIPT\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
