.TH "TMXDecayChannel" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXDecayChannel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXDecayChannel\fP (int IZAd, string decay, float brat, float qdec, vector< int > *products)"
.br
.ti -1c
.RI "float \fBBranchingRatio\fP () const"
.br
.ti -1c
.RI "void \fBSetBranchingRatio\fP (double brat)"
.br
.ti -1c
.RI "int \fBIZA\fP () const"
.br
.ti -1c
.RI "string \fBDecay\fP () const"
.br
.ti -1c
.RI "float \fBQdec\fP () const"
.br
.ti -1c
.RI "vector< int > * \fBProducts\fP ()"
.br
.ti -1c
.RI "\fBTMXDecayChannel\fP (int IZAd, string decay, float brat, float qdec, vector< int > *products)"
.br
.ti -1c
.RI "float \fBBranchingRatio\fP () const"
.br
.ti -1c
.RI "void \fBSetBranchingRatio\fP (double brat)"
.br
.ti -1c
.RI "int \fBIZA\fP () const"
.br
.ti -1c
.RI "string \fBDecay\fP () const"
.br
.ti -1c
.RI "float \fBQdec\fP () const"
.br
.ti -1c
.RI "vector< int > * \fBProducts\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXDecayChannel::TMXDecayChannel (int IZAd, string decay, float brat, float qdec, vector< int > * products)\fC [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBTMXElements\&.hh\fP\&.
.SS "TMXDecayChannel::TMXDecayChannel (int IZAd, string decay, float brat, float qdec, vector< int > * products)\fC [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "float TMXDecayChannel::BranchingRatio () const\fC [inline]\fP"

.PP
Definition at line \fB27\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXDecayChannel::BranchingRatio () const\fC [inline]\fP"

.PP
Definition at line \fB27\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXDecayChannel::Decay () const\fC [inline]\fP"

.PP
Definition at line \fB30\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXDecayChannel::Decay () const\fC [inline]\fP"

.PP
Definition at line \fB30\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXDecayChannel::IZA () const\fC [inline]\fP"

.PP
Definition at line \fB29\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXDecayChannel::IZA () const\fC [inline]\fP"

.PP
Definition at line \fB29\fP of file \fBTMXElements\&.hh\fP\&.
.SS "vector< int > * TMXDecayChannel::Products ()\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBTMXElements\&.hh\fP\&.
.SS "vector< int > * TMXDecayChannel::Products ()\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXDecayChannel::Qdec () const\fC [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXDecayChannel::Qdec () const\fC [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXDecayChannel::SetBranchingRatio (double brat)\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXDecayChannel::SetBranchingRatio (double brat)\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBTMXElements\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
