.TH "TMXDetectionChamber" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXDetectionChamber
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXDetectionChamber\fP (std::string, \fBTMXMaterial\fP *=nullptr)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBbuildGeometry\fP (double Kelvin_Temperature=273\&.15)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "G4LogicalVolume * \fBm_motherVolume\fP"
.br
.ti -1c
.RI "std::string \fBm_detName\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_DetectionVolume_mat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBTMXDetectionChamber\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXDetectionChamber::TMXDetectionChamber (std::string name, \fBTMXMaterial\fP * surrounding = \fCnullptr\fP)"

.PP
Definition at line \fB24\fP of file \fBTMXDetectionChamber\&.cc\fP\&.
.SS "TMXDetectionChamber::TMXDetectionChamber ()"

.PP
Definition at line \fB18\fP of file \fBTMXDetectionChamber\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXDetectionChamber::buildGeometry (double Kelvin_Temperature = \fC273\&.15\fP)\fC [protected]\fP"
Enveloppe of the detector
.PP
Uranium coating of the detector
.PP
Detection volume of the detector
.PP
Enveloppe of the detector
.PP
Detection volume of the detector
.PP
Mother volume
.PP
Enveloppe of the detector
.PP
Gaz volume
.PP
Uranium coating of the detector
.PP
Insulators
.PP
Top
.PP
Bottom
.PP
Cable
.PP
Definition at line \fB54\fP of file \fBTMXDetectionChamber\&.cc\fP\&.
.SS "G4LogicalVolume * TMXDetectionChamber::getMasterVolume ()"

.PP
Definition at line \fB30\fP of file \fBTMXDetectionChamber\&.cc\fP\&.
.SS "void TMXDetectionChamber::VisualisationConfig ()"

.PP
Definition at line \fB36\fP of file \fBTMXDetectionChamber\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTMXMaterial\fP* TMXDetectionChamber::m_DetectionVolume_mat\fC [protected]\fP"

.PP
Definition at line \fB38\fP of file \fBTMXDetectionChamber\&.hh\fP\&.
.SS "std::string TMXDetectionChamber::m_detName\fC [protected]\fP"

.PP
Definition at line \fB37\fP of file \fBTMXDetectionChamber\&.hh\fP\&.
.SS "G4LogicalVolume* TMXDetectionChamber::m_motherVolume\fC [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBTMXDetectionChamber\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
