.TH "TMXElement" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXElement
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXElement\fP (int ia, int iz, string ele, int iso, float eex, float mex, float tave, string spin, float abund, float ingToxicity=\-1\&., float inhToxicity=\-1\&.)"
.br
.ti -1c
.RI "int \fBIZA\fP () const"
.br
.ti -1c
.RI "int \fBA\fP () const"
.br
.ti -1c
.RI "int \fBZ\fP () const"
.br
.ti -1c
.RI "int \fBISO\fP () const"
.br
.ti -1c
.RI "float \fBMweight\fP () const"
.br
.ti -1c
.RI "float \fBTave\fP () const"
.br
.ti -1c
.RI "float \fBEex\fP () const"
.br
.ti -1c
.RI "float \fBMex\fP () const"
.br
.ti -1c
.RI "string \fBSpin\fP () const"
.br
.ti -1c
.RI "float \fBAbund\fP () const"
.br
.ti -1c
.RI "string \fBSym\fP () const"
.br
.ti -1c
.RI "float \fBIngToxicity\fP () const"
.br
.ti -1c
.RI "float \fBInhToxicity\fP () const"
.br
.ti -1c
.RI "string \fBName\fP () const"
.br
.ti -1c
.RI "void \fBAddDecayChannel\fP (int IZAd, string decay, float brat, float qdec, vector< int > *IZAp)"
.br
.ti -1c
.RI "void \fBSetIngToxicity\fP (float ingt)"
.br
.ti -1c
.RI "void \fBSetInhToxicity\fP (float inht)"
.br
.ti -1c
.RI "vector< \fBTMXDecayChannel\fP * > & \fBDecayChannels\fP ()"
.br
.ti -1c
.RI "bool \fBStable\fP () const"
.br
.ti -1c
.RI "\fBTMXElement\fP (int ia, int iz, string ele, int iso, float eex, float mex, float tave, string spin, float abund, float ingToxicity=\-1\&., float inhToxicity=\-1\&.)"
.br
.ti -1c
.RI "int \fBIZA\fP () const"
.br
.ti -1c
.RI "int \fBA\fP () const"
.br
.ti -1c
.RI "int \fBZ\fP () const"
.br
.ti -1c
.RI "int \fBISO\fP () const"
.br
.ti -1c
.RI "float \fBMweight\fP () const"
.br
.ti -1c
.RI "float \fBTave\fP () const"
.br
.ti -1c
.RI "float \fBEex\fP () const"
.br
.ti -1c
.RI "float \fBMex\fP () const"
.br
.ti -1c
.RI "string \fBSpin\fP () const"
.br
.ti -1c
.RI "float \fBAbund\fP () const"
.br
.ti -1c
.RI "string \fBSym\fP () const"
.br
.ti -1c
.RI "float \fBIngToxicity\fP () const"
.br
.ti -1c
.RI "float \fBInhToxicity\fP () const"
.br
.ti -1c
.RI "string \fBName\fP () const"
.br
.ti -1c
.RI "void \fBAddDecayChannel\fP (int IZAd, string decay, float brat, float qdec, vector< int > *IZAp)"
.br
.ti -1c
.RI "void \fBSetIngToxicity\fP (float ingt)"
.br
.ti -1c
.RI "void \fBSetInhToxicity\fP (float inht)"
.br
.ti -1c
.RI "vector< \fBTMXDecayChannel\fP * > & \fBDecayChannels\fP ()"
.br
.ti -1c
.RI "bool \fBStable\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBfA\fP"
.br
.ti -1c
.RI "int \fBfZ\fP"
.br
.ti -1c
.RI "string \fBfEle\fP"
.br
.ti -1c
.RI "int \fBfIso\fP"
.br
.ti -1c
.RI "int \fBfDis\fP"
.br
.ti -1c
.RI "float \fBfEex\fP"
.br
.ti -1c
.RI "float \fBfMex\fP"
.br
.ti -1c
.RI "float \fBfTave\fP"
.br
.ti -1c
.RI "string \fBfSpin\fP"
.br
.ti -1c
.RI "float \fBfAbund\fP"
.br
.ti -1c
.RI "float \fBfIngToxicity\fP"
.br
.ti -1c
.RI "float \fBfInhToxicity\fP"
.br
.ti -1c
.RI "vector< \fBTMXDecayChannel\fP * > \fBfDecayChannels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB41\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXElement::TMXElement (int ia, int iz, string ele, int iso, float eex, float mex, float tave, string spin, float abund, float ingToxicity = \fC\-1\&.\fP, float inhToxicity = \fC\-1\&.\fP)\fC [inline]\fP"

.PP
Definition at line \fB43\fP of file \fBTMXElements\&.hh\fP\&.
.SS "TMXElement::TMXElement (int ia, int iz, string ele, int iso, float eex, float mex, float tave, string spin, float abund, float ingToxicity = \fC\-1\&.\fP, float inhToxicity = \fC\-1\&.\fP)\fC [inline]\fP"

.PP
Definition at line \fB43\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int TMXElement::A () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::A () const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Abund () const\fC [inline]\fP"

.PP
Definition at line \fB67\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Abund () const\fC [inline]\fP"

.PP
Definition at line \fB67\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElement::AddDecayChannel (int IZAd, string decay, float brat, float qdec, vector< int > * IZAp)\fC [inline]\fP"

.PP
Definition at line \fB85\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElement::AddDecayChannel (int IZAd, string decay, float brat, float qdec, vector< int > * IZAp)\fC [inline]\fP"

.PP
Definition at line \fB85\fP of file \fBTMXElements\&.hh\fP\&.
.SS "vector< \fBTMXDecayChannel\fP * > & TMXElement::DecayChannels ()\fC [inline]\fP"

.PP
Definition at line \fB90\fP of file \fBTMXElements\&.hh\fP\&.
.SS "vector< \fBTMXDecayChannel\fP * > & TMXElement::DecayChannels ()\fC [inline]\fP"

.PP
Definition at line \fB90\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Eex () const\fC [inline]\fP"

.PP
Definition at line \fB64\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Eex () const\fC [inline]\fP"

.PP
Definition at line \fB64\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::IngToxicity () const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::IngToxicity () const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::InhToxicity () const\fC [inline]\fP"

.PP
Definition at line \fB70\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::InhToxicity () const\fC [inline]\fP"

.PP
Definition at line \fB70\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::ISO () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::ISO () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::IZA () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::IZA () const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Mex () const\fC [inline]\fP"

.PP
Definition at line \fB65\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Mex () const\fC [inline]\fP"

.PP
Definition at line \fB65\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Mweight () const\fC [inline]\fP"

.PP
Definition at line \fB62\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Mweight () const\fC [inline]\fP"

.PP
Definition at line \fB62\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::Name () const\fC [inline]\fP"

.PP
Definition at line \fB71\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::Name () const\fC [inline]\fP"

.PP
Definition at line \fB71\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElement::SetIngToxicity (float ingt)\fC [inline]\fP"

.PP
Definition at line \fB88\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElement::SetIngToxicity (float ingt)\fC [inline]\fP"

.PP
Definition at line \fB88\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElement::SetInhToxicity (float inht)\fC [inline]\fP"

.PP
Definition at line \fB89\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElement::SetInhToxicity (float inht)\fC [inline]\fP"

.PP
Definition at line \fB89\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::Spin () const\fC [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::Spin () const\fC [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBTMXElements\&.hh\fP\&.
.SS "bool TMXElement::Stable () const\fC [inline]\fP"

.PP
Definition at line \fB91\fP of file \fBTMXElements\&.hh\fP\&.
.SS "bool TMXElement::Stable () const\fC [inline]\fP"

.PP
Definition at line \fB91\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::Sym () const\fC [inline]\fP"

.PP
Definition at line \fB68\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::Sym () const\fC [inline]\fP"

.PP
Definition at line \fB68\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Tave () const\fC [inline]\fP"

.PP
Definition at line \fB63\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::Tave () const\fC [inline]\fP"

.PP
Definition at line \fB63\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::Z () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::Z () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int TMXElement::fA\fC [protected]\fP"

.PP
Definition at line \fB93\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::fAbund\fC [protected]\fP"

.PP
Definition at line \fB102\fP of file \fBTMXElements\&.hh\fP\&.
.SS "vector< \fBTMXDecayChannel\fP * > TMXElement::fDecayChannels\fC [protected]\fP"

.PP
Definition at line \fB105\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::fDis\fC [protected]\fP"

.PP
Definition at line \fB97\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::fEex\fC [protected]\fP"

.PP
Definition at line \fB98\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::fEle\fC [protected]\fP"

.PP
Definition at line \fB95\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::fIngToxicity\fC [protected]\fP"

.PP
Definition at line \fB103\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::fInhToxicity\fC [protected]\fP"

.PP
Definition at line \fB104\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::fIso\fC [protected]\fP"

.PP
Definition at line \fB96\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::fMex\fC [protected]\fP"

.PP
Definition at line \fB99\fP of file \fBTMXElements\&.hh\fP\&.
.SS "string TMXElement::fSpin\fC [protected]\fP"

.PP
Definition at line \fB101\fP of file \fBTMXElements\&.hh\fP\&.
.SS "float TMXElement::fTave\fC [protected]\fP"

.PP
Definition at line \fB100\fP of file \fBTMXElements\&.hh\fP\&.
.SS "int TMXElement::fZ\fC [protected]\fP"

.PP
Definition at line \fB94\fP of file \fBTMXElements\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
