.TH "TMXExternalSource" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXExternalSource
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXExternalSource\fP ()"
.br
.RI "\fBTMXExternalSource::TMXExternalSource\fP\&. "
.ti -1c
.RI "\fB~TMXExternalSource\fP ()"
.br
.RI "\fBTMXExternalSource::~TMXExternalSource\fP\&. "
.ti -1c
.RI "void \fBnext\fP ()"
.br
.RI "\fBTMXExternalSource::next\fP\&. "
.ti -1c
.RI "void \fBinitialize\fP (std::string, int)"
.br
.RI "\fBTMXExternalSource::initialize\fP\&. "
.ti -1c
.RI "void \fBendOfCalculation\fP ()"
.br
.RI "\fBTMXExternalSource::endOfCalculation\fP\&. "
.ti -1c
.RI "G4ThreeVector \fBgetPosition\fP ()"
.br
.RI "\fBTMXExternalSource::getPosition\fP\&. "
.ti -1c
.RI "G4ThreeVector \fBgetDirection\fP ()"
.br
.RI "\fBTMXExternalSource::getDirection\fP\&. "
.ti -1c
.RI "double \fBgetEnergy\fP ()"
.br
.RI "\fBTMXExternalSource::getEnergy\fP\&. "
.ti -1c
.RI "int \fBgetNumberOfEvents\fP ()"
.br
.RI "\fBTMXExternalSource::setFilePath\fP\&. "
.ti -1c
.RI "std::string \fBgetParticleID\fP ()"
.br
.RI "TMXExternalSource::getPrimary\&. "
.ti -1c
.RI "void \fBsetFilePath\fP (std::string)"
.br
.RI "\fBTMXExternalSource::setFilePath\fP\&. "
.ti -1c
.RI "void \fBsetTargetTranslation\fP (G4ThreeVector)"
.br
.RI "\fBTMXExternalSource::setTargetTranslation\fP\&. "
.ti -1c
.RI "void \fBsetNumberOfParticleToSample\fP (int)"
.br
.RI "\fBTMXExternalSource::setNumberOfParticleToSample\fP\&. "
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (std::string, int)"
.br
.ti -1c
.RI "void \fBendOfCalculation\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetPosition\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetDirection\fP ()"
.br
.ti -1c
.RI "double \fBgetEnergy\fP ()"
.br
.ti -1c
.RI "int \fBgetNumberOfEvents\fP ()"
.br
.ti -1c
.RI "std::string \fBgetParticleID\fP ()"
.br
.ti -1c
.RI "void \fBsetFilePath\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetTargetTranslation\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBsetNumberOfParticleToSample\fP (int)"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (std::string, int)"
.br
.ti -1c
.RI "void \fBendOfCalculation\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetPosition\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetDirection\fP ()"
.br
.ti -1c
.RI "double \fBgetEnergy\fP ()"
.br
.ti -1c
.RI "int \fBgetNumberOfEvents\fP ()"
.br
.ti -1c
.RI "std::string \fBgetParticleID\fP ()"
.br
.ti -1c
.RI "void \fBsetFilePath\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetTargetTranslation\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBsetNumberOfParticleToSample\fP (int)"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (std::string, int)"
.br
.ti -1c
.RI "void \fBendOfCalculation\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetPosition\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetDirection\fP ()"
.br
.ti -1c
.RI "double \fBgetEnergy\fP ()"
.br
.ti -1c
.RI "int \fBgetNumberOfEvents\fP ()"
.br
.ti -1c
.RI "std::string \fBgetParticleID\fP ()"
.br
.ti -1c
.RI "void \fBsetFilePath\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetTargetTranslation\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBsetNumberOfParticleToSample\fP (int)"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (std::string, int)"
.br
.ti -1c
.RI "void \fBendOfCalculation\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetPosition\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBgetDirection\fP ()"
.br
.ti -1c
.RI "double \fBgetEnergy\fP ()"
.br
.ti -1c
.RI "int \fBgetNumberOfEvents\fP ()"
.br
.ti -1c
.RI "std::string \fBgetParticleID\fP ()"
.br
.ti -1c
.RI "void \fBsetFilePath\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetTargetTranslation\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBsetNumberOfParticleToSample\fP (int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBTMXExternalSource\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXExternalSource::TMXExternalSource ()"

.PP
\fBTMXExternalSource::TMXExternalSource\fP\&. 
.PP
Definition at line \fB50\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "TMXExternalSource::~TMXExternalSource ()"

.PP
\fBTMXExternalSource::~TMXExternalSource\fP\&. 
.PP
Definition at line \fB60\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXExternalSource::endOfCalculation ()"

.PP
\fBTMXExternalSource::endOfCalculation\fP\&. 
.PP
Definition at line \fB192\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "G4ThreeVector TMXExternalSource::getDirection ()"

.PP
\fBTMXExternalSource::getDirection\fP\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB229\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "double TMXExternalSource::getEnergy ()"

.PP
\fBTMXExternalSource::getEnergy\fP\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB238\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "int TMXExternalSource::getNumberOfEvents ()"

.PP
\fBTMXExternalSource::setFilePath\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.PP
Definition at line \fB247\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "std::string TMXExternalSource::getParticleID ()"

.PP
TMXExternalSource::getPrimary\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB211\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "G4ThreeVector TMXExternalSource::getPosition ()"

.PP
\fBTMXExternalSource::getPosition\fP\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB220\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "void TMXExternalSource::initialize (std::string path, int n)"

.PP
\fBTMXExternalSource::initialize\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.br
\fIn\fP 
.RE
.PP

.PP
Definition at line \fB262\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "void TMXExternalSource::next ()"

.PP
\fBTMXExternalSource::next\fP\&. 
.PP
Definition at line \fB128\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "void TMXExternalSource::setFilePath (std::string path)"

.PP
\fBTMXExternalSource::setFilePath\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.PP
Definition at line \fB276\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "void TMXExternalSource::setNumberOfParticleToSample (int n)"

.PP
\fBTMXExternalSource::setNumberOfParticleToSample\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP 
.RE
.PP

.PP
Definition at line \fB297\fP of file \fBTMXExternalSource\&.cc\fP\&.
.SS "void TMXExternalSource::setTargetTranslation (G4ThreeVector v)"

.PP
\fBTMXExternalSource::setTargetTranslation\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP 
.RE
.PP

.PP
Definition at line \fB288\fP of file \fBTMXExternalSource\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
