.TH "TMXElementStore" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXElementStore
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBTMXElement\fP * \fBGetElement\fP (int IZA)"
.br
.ti -1c
.RI "static void \fBBuildElementDB\fP ()"
.br
.ti -1c
.RI "static map< int, \fBTMXElement\fP * > & \fBStore\fP ()"
.br
.ti -1c
.RI "static bool \fBAddElement\fP (\fBTMXElement\fP *ele)"
.br
.ti -1c
.RI "static const \fBTMXElement\fP * \fBGetElement\fP (int IZA)"
.br
.ti -1c
.RI "static void \fBBuildElementDB\fP ()"
.br
.ti -1c
.RI "static map< int, \fBTMXElement\fP * > & \fBStore\fP ()"
.br
.ti -1c
.RI "static bool \fBAddElement\fP (\fBTMXElement\fP *ele)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static map< int, \fBTMXElement\fP * > \fBfElementStore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB108\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool TMXElementStore::AddElement (\fBTMXElement\fP * ele)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB119\fP of file \fBTMXElements\&.hh\fP\&.
.SS "static bool TMXElementStore::AddElement (\fBTMXElement\fP * ele)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB119\fP of file \fBTMXElements\&.hh\fP\&.
.SS "void TMXElementStore::BuildElementDB ()\fC [static]\fP"

.PP
Definition at line \fB3\fP of file \fBTMXElementsDB\&.cc\fP\&.
.SS "static const \fBTMXElement\fP * TMXElementStore::GetElement (int IZA)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBTMXElements\&.hh\fP\&.
.SS "static const \fBTMXElement\fP * TMXElementStore::GetElement (int IZA)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBTMXElements\&.hh\fP\&.
.SS "static map< int, \fBTMXElement\fP * > & TMXElementStore::Store ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB117\fP of file \fBTMXElements\&.hh\fP\&.
.SS "static map< int, \fBTMXElement\fP * > & TMXElementStore::Store ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB117\fP of file \fBTMXElements\&.hh\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "map< int, \fBTMXElement\fP * > TMXElementStore::fElementStore\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB129\fP of file \fBTMXElements\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
