.TH "TMXFuelIRT4M8T" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXFuelIRT4M8T
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, and \fBTMXAbstractFuelAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXFuelIRT4M8T\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelIRT4M8T\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelIRT4M8T\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelIRT4M8T\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelIRT4M8T\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBTMXFuelIRT4M8T\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXFuelIRT4M8T::TMXFuelIRT4M8T (const std::string & FuelAssemblyName, \fBTMXInputParameters\fP * parameter, G4double rodInsertion = \fC0\fP)"

.PP
Definition at line \fB34\fP of file \fBTMXFuelIRT4M8T\&.cc\fP\&.
.SS "TMXFuelIRT4M8T::~TMXFuelIRT4M8T ()\fC [inline]\fP"

.PP
Definition at line \fB44\fP of file \fBTMXFuelIRT4M8T\&.hh\fP\&.
.SS "TMXFuelIRT4M8T::~TMXFuelIRT4M8T ()\fC [inline]\fP"

.PP
Definition at line \fB44\fP of file \fBTMXFuelIRT4M8T\&.hh\fP\&.
.SS "TMXFuelIRT4M8T::~TMXFuelIRT4M8T ()\fC [inline]\fP"

.PP
Definition at line \fB44\fP of file \fBTMXFuelIRT4M8T\&.hh\fP\&.
.SS "TMXFuelIRT4M8T::~TMXFuelIRT4M8T ()\fC [inline]\fP"

.PP
Definition at line \fB44\fP of file \fBTMXFuelIRT4M8T\&.hh\fP\&.
.SS "TMXFuelIRT4M8T::~TMXFuelIRT4M8T ()\fC [inline]\fP"

.PP
Definition at line \fB44\fP of file \fBTMXFuelIRT4M8T\&.hh\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXFuelIRT4M8T::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB118\fP of file \fBTMXFuelIRT4M8T\&.cc\fP\&.
.SS "void TMXFuelIRT4M8T::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB45\fP of file \fBTMXFuelIRT4M8T\&.cc\fP\&.
.SS "void TMXFuelIRT4M8T::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelIRT4M8T::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
