.TH "TMXFissionSourceBank" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXFissionSourceBank
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXFissionSourceBank\fP ()"
.br
.RI "\fBTMXFissionSourceBank::TMXFissionSourceBank\fP\&. "
.ti -1c
.RI "void \fBaddFissionSite\fP (G4ThreeVector, G4ThreeVector, double, G4ThreeVector)"
.br
.RI "TMXFissionSourceBank::addFissionSource\&. "
.ti -1c
.RI "void \fBaddLocationSite\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddEnergySite\fP (G4double)"
.br
.ti -1c
.RI "\fBFissionSite\fP \fBgetFissionSite\fP (int)"
.br
.RI "TMXFissionSourceBank::getFissionSource\&. "
.ti -1c
.RI "G4ThreeVector \fBgetFissionSiteLoc\fP (double)"
.br
.ti -1c
.RI "G4double \fBgetFissionSiteE\fP (double)"
.br
.ti -1c
.RI "int \fBgetNumberOfFissionSites\fP ()"
.br
.RI "TMXFissionSourceBank::getNumberOfFissionSources\&. "
.ti -1c
.RI "void \fBnextCycle\fP ()"
.br
.RI "\fBTMXFissionSourceBank::nextCycle\fP\&. "
.ti -1c
.RI "void \fBaddFissionSite\fP (G4ThreeVector, G4ThreeVector, double, G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddLocationSite\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddEnergySite\fP (G4double)"
.br
.ti -1c
.RI "\fBFissionSite\fP \fBgetFissionSite\fP (int)"
.br
.ti -1c
.RI "G4ThreeVector \fBgetFissionSiteLoc\fP (double)"
.br
.ti -1c
.RI "G4double \fBgetFissionSiteE\fP (double)"
.br
.ti -1c
.RI "int \fBgetNumberOfFissionSites\fP ()"
.br
.ti -1c
.RI "void \fBnextCycle\fP ()"
.br
.ti -1c
.RI "void \fBaddFissionSite\fP (G4ThreeVector, G4ThreeVector, double, G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddLocationSite\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddEnergySite\fP (G4double)"
.br
.ti -1c
.RI "\fBFissionSite\fP \fBgetFissionSite\fP (int)"
.br
.ti -1c
.RI "G4ThreeVector \fBgetFissionSiteLoc\fP (double)"
.br
.ti -1c
.RI "G4double \fBgetFissionSiteE\fP (double)"
.br
.ti -1c
.RI "int \fBgetNumberOfFissionSites\fP ()"
.br
.ti -1c
.RI "void \fBnextCycle\fP ()"
.br
.ti -1c
.RI "void \fBaddFissionSite\fP (G4ThreeVector, G4ThreeVector, double, G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddLocationSite\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddEnergySite\fP (G4double)"
.br
.ti -1c
.RI "\fBFissionSite\fP \fBgetFissionSite\fP (int)"
.br
.ti -1c
.RI "G4ThreeVector \fBgetFissionSiteLoc\fP (double)"
.br
.ti -1c
.RI "G4double \fBgetFissionSiteE\fP (double)"
.br
.ti -1c
.RI "int \fBgetNumberOfFissionSites\fP ()"
.br
.ti -1c
.RI "void \fBnextCycle\fP ()"
.br
.ti -1c
.RI "void \fBaddFissionSite\fP (G4ThreeVector, G4ThreeVector, double, G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddLocationSite\fP (G4ThreeVector)"
.br
.ti -1c
.RI "void \fBaddEnergySite\fP (G4double)"
.br
.ti -1c
.RI "\fBFissionSite\fP \fBgetFissionSite\fP (int)"
.br
.ti -1c
.RI "G4ThreeVector \fBgetFissionSiteLoc\fP (double)"
.br
.ti -1c
.RI "G4double \fBgetFissionSiteE\fP (double)"
.br
.ti -1c
.RI "int \fBgetNumberOfFissionSites\fP ()"
.br
.ti -1c
.RI "void \fBnextCycle\fP ()"
.br
.ti -1c
.RI "void \fBaddFissionSite\fP (G4ThreeVector, G4ThreeVector, double, G4ThreeVector)"
.br
.ti -1c
.RI "\fBFissionSite\fP \fBgetFissionSite\fP (int)"
.br
.ti -1c
.RI "int \fBgetNumberOfFissionSites\fP ()"
.br
.ti -1c
.RI "void \fBnextCycle\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB57\fP of file \fBTMXFissionSourceBank\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXFissionSourceBank::TMXFissionSourceBank ()"

.PP
\fBTMXFissionSourceBank::TMXFissionSourceBank\fP\&. 
.PP
Definition at line \fB43\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXFissionSourceBank::addEnergySite (G4double ener)"

.PP
Definition at line \fB106\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "void TMXFissionSourceBank::addFissionSite (G4ThreeVector position, G4ThreeVector direction, double energy, G4ThreeVector momentum)"

.PP
TMXFissionSourceBank::addFissionSource\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP 
.br
\fImomentum\fP 
.br
\fIenergy\fP 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "void TMXFissionSourceBank::addLocationSite (G4ThreeVector loc)"

.PP
Definition at line \fB102\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "\fBFissionSite\fP TMXFissionSourceBank::getFissionSite (int num)"

.PP
TMXFissionSourceBank::getFissionSource\&. 
.PP
\fBParameters\fP
.RS 4
\fInum\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB87\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "G4double TMXFissionSourceBank::getFissionSiteE (double num)"

.PP
Definition at line \fB114\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "G4ThreeVector TMXFissionSourceBank::getFissionSiteLoc (double num)"

.PP
Definition at line \fB110\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "int TMXFissionSourceBank::getNumberOfFissionSites ()"

.PP
TMXFissionSourceBank::getNumberOfFissionSources\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB97\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.
.SS "void TMXFissionSourceBank::nextCycle ()"

.PP
\fBTMXFissionSourceBank::nextCycle\fP\&. 
.PP
Definition at line \fB52\fP of file \fBTMXFissionSourceBank\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
