.TH "TMXFuel" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXFuel \- Definition of the \fBTMXFuel\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXFuel\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBBuild_WWR_M5\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *fLogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *fLogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *fLogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &fLogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_WWR_M2\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_IBR2M\fP (\fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBBuild_WWR_M5\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *fLogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *fLogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *fLogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &fLogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_WWR_M2\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_IBR2M\fP (\fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBBuild_WWR_M5\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *fLogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *fLogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *fLogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &fLogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_WWR_M2\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_IBR2M\fP (\fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBBuild_WWR_M5\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *fLogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *fLogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *fLogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &fLogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_WWR_M2\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_IBR2M\fP (\fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBBuild_WWR_M5\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *fLogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *fLogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *fLogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &fLogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_WWR_M2\fP (G4double RotAnglePolygon, \fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.ti -1c
.RI "void \fBBuild_IBR2M\fP (\fBTMXInputParameters\fP *p, G4LogicalVolume *G4LogicCladdingUnion, G4Material *G4CladdingMaterial, G4LogicalVolume *G4LogicWaterFuelCladding, G4Material *G4WaterFuelMaterial, G4LogicalVolume *G4LogicFuelUnion, G4Material *G4FuelMaterial, std::vector< G4LogicalVolume * > &G4LogicFuel, std::vector< std::string > &vec_LVname)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXFuel\fP class\&. 
.PP
Definition at line \fB27\fP of file \fBTMXFuel\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXFuel::TMXFuel ()"

.PP
Definition at line \fB27\fP of file \fBTMXFuel\&.cc\fP\&.
.SS "TMXFuel::~TMXFuel ()"

.PP
Definition at line \fB31\fP of file \fBTMXFuel\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXFuel::Build_IBR2M (\fBTMXInputParameters\fP * p, G4LogicalVolume * G4LogicCladdingUnion, G4Material * G4CladdingMaterial, G4LogicalVolume * G4LogicWaterFuelCladding, G4Material * G4WaterFuelMaterial, G4LogicalVolume * G4LogicFuelUnion, G4Material * G4FuelMaterial, std::vector< G4LogicalVolume * > & G4LogicFuel, std::vector< std::string > & vec_LVname)"

.PP
Definition at line \fB239\fP of file \fBTMXFuel\&.cc\fP\&.
.SS "void TMXFuel::Build_WWR_M2 (G4double RotAnglePolygon, \fBTMXInputParameters\fP * p, G4LogicalVolume * G4LogicCladdingUnion, G4Material * G4CladdingMaterial, G4LogicalVolume * G4LogicWaterFuelCladding, G4Material * G4WaterFuelMaterial, G4LogicalVolume * G4LogicFuelUnion, G4Material * G4FuelMaterial, std::vector< G4LogicalVolume * > & G4LogicFuel, std::vector< std::string > & vec_LVname)"

.PP
Definition at line \fB139\fP of file \fBTMXFuel\&.cc\fP\&.
.SS "void TMXFuel::Build_WWR_M5 (G4double RotAnglePolygon, \fBTMXInputParameters\fP * p, G4LogicalVolume * fLogicCladdingUnion, G4Material * G4CladdingMaterial, G4LogicalVolume * fLogicWaterFuelCladding, G4Material * G4WaterFuelMaterial, G4LogicalVolume * fLogicFuelUnion, G4Material * G4FuelMaterial, std::vector< G4LogicalVolume * > & fLogicFuel, std::vector< std::string > & vec_LVname)"

.PP
Definition at line \fB41\fP of file \fBTMXFuel\&.cc\fP\&.
.SS "void TMXFuel::Initialize ()"

.PP
Definition at line \fB34\fP of file \fBTMXFuel\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
