.TH "TMXFuelAssemblyVVRM2" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXFuelAssemblyVVRM2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, and \fBTMXAbstractFuelAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXFuelAssemblyVVRM2\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector centerTarget, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelAssemblyVVRM2\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector centerTarget, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelAssemblyVVRM2\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector centerTarget, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelAssemblyVVRM2\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector centerTarget, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXFuelAssemblyVVRM2\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector centerTarget, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB41\fP of file \fBTMXFuelAssemblyVVRM2\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXFuelAssemblyVVRM2::TMXFuelAssemblyVVRM2 (const std::string & FuelAssemblyName, \fBTMXInputParameters\fP * parameter, G4double rodInsertion = \fC0\fP)"

.PP
Definition at line \fB48\fP of file \fBTMXFuelAssemblyVVRM2\&.cc\fP\&.
.SS "TMXFuelAssemblyVVRM2::~TMXFuelAssemblyVVRM2 ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXFuelAssemblyVVRM2\&.hh\fP\&.
.SS "TMXFuelAssemblyVVRM2::~TMXFuelAssemblyVVRM2 ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXFuelAssemblyVVRM2\&.hh\fP\&.
.SS "TMXFuelAssemblyVVRM2::~TMXFuelAssemblyVVRM2 ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXFuelAssemblyVVRM2\&.hh\fP\&.
.SS "TMXFuelAssemblyVVRM2::~TMXFuelAssemblyVVRM2 ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXFuelAssemblyVVRM2\&.hh\fP\&.
.SS "TMXFuelAssemblyVVRM2::~TMXFuelAssemblyVVRM2 ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXFuelAssemblyVVRM2\&.hh\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXFuelAssemblyVVRM2::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB106\fP of file \fBTMXFuelAssemblyVVRM2\&.cc\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createGeometry ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB61\fP of file \fBTMXFuelAssemblyVVRM2\&.cc\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXFuelAssemblyVVRM2::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "G4double TMXFuelAssemblyVVRM2::GetOuterRadius ()"

.PP
Definition at line \fB453\fP of file \fBTMXFuelAssemblyVVRM2\&.cc\fP\&.
.SS "void TMXFuelAssemblyVVRM2::placeGeometry (bool overlap, G4ThreeVector centerTarget, G4RotationMatrix * rotation, G4LogicalVolume * masterVolume)"

.PP
Definition at line \fB361\fP of file \fBTMXFuelAssemblyVVRM2\&.cc\fP\&.
.SS "void TMXFuelAssemblyVVRM2::visualisationConfig ()"

.PP
Definition at line \fB365\fP of file \fBTMXFuelAssemblyVVRM2\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
