.TH "TMXInputParameters" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXInputParameters \- Declaration of the \fBTMXInputParameters\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXInputParameters\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXInputParameters\fP ()"
.br
.RI "Implementation of the \fBTMXInputParameters\fP class\&. "
.ti -1c
.RI "void \fBread\fP (const std::string &strFileName)"
.br
.ti -1c
.RI "void \fBverbose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBboolVisualization\fP"
.br
.ti -1c
.RI "int \fBnThreads\fP"
.br
.ti -1c
.RI "bool \fBisThreadMerging\fP"
.br
.ti -1c
.RI "int \fBVerbose\fP"
.br
.ti -1c
.RI "double \fBBeamEnergy\fP"
.br
.ti -1c
.RI "int \fBNparticles\fP"
.br
.ti -1c
.RI "int \fBNrun\fP"
.br
.ti -1c
.RI "int \fBNcycle\fP"
.br
.ti -1c
.RI "double \fBTimeOfRun\fP"
.br
.ti -1c
.RI "double \fBCoolingTime\fP"
.br
.ti -1c
.RI "double \fBP_beam\fP"
.br
.ti -1c
.RI "double \fBP_core\fP"
.br
.ti -1c
.RI "int \fBGeometry\fP"
.br
.ti -1c
.RI "std::string \fBstr_ROOTFileName\fP"
.br
.ti -1c
.RI "int \fBint_Option\fP"
.br
.ti -1c
.RI "std::string \fBphysName\fP"
.br
.ti -1c
.RI "bool \fBisAbla\fP"
.br
.ti -1c
.RI "bool \fBisRandomSeed\fP"
.br
.ti -1c
.RI "bool \fBisLEND\fP"
.br
.ti -1c
.RI "int \fBPrintModulo\fP"
.br
.ti -1c
.RI "double \fBTemperatureWorld\fP"
.br
.ti -1c
.RI "double \fBTemperatureFuel\fP"
.br
.ti -1c
.RI "int \fBNbDiscardCycle\fP"
.br
.ti -1c
.RI "double \fBErrorLimitMCCubicVolume\fP"
.br
.ti -1c
.RI "std::string \fBMCCubicVolumeLVname\fP"
.br
.ti -1c
.RI "std::string \fBExtSourcePath\fP"
.br
.ti -1c
.RI "std::vector< double > \fBoriginKeff\fP"
.br
.ti -1c
.RI "double \fBworldR\fP"
.br
.ti -1c
.RI "double \fBworldZ\fP"
.br
.ti -1c
.RI "double \fBh0\fP"
.br
.ti -1c
.RI "double \fBXtargetPosition\fP"
.br
.ti -1c
.RI "double \fBCheckGap\fP"
.br
.ti -1c
.RI "double \fBcheck1r\fP"
.br
.ti -1c
.RI "double \fBxTarget\fP"
.br
.ti -1c
.RI "double \fByTarget\fP"
.br
.ti -1c
.RI "double \fBzTargetHeight\fP"
.br
.ti -1c
.RI "int \fBnT\fP"
.br
.ti -1c
.RI "double \fBtargetgap\fP"
.br
.ti -1c
.RI "double \fBxVariable\fP"
.br
.ti -1c
.RI "double \fBTarget_Al_Xgap\fP"
.br
.ti -1c
.RI "double \fBTarget_Al_Ygap\fP"
.br
.ti -1c
.RI "double \fBAl_thickness\fP"
.br
.ti -1c
.RI "double \fBAl_Tube_gap\fP"
.br
.ti -1c
.RI "double \fBairtopR\fP"
.br
.ti -1c
.RI "double \fBAirTopZdistanceFromBottomtoTop\fP"
.br
.ti -1c
.RI "double \fBreflectorZdistanceFromBottomtoTop\fP"
.br
.ti -1c
.RI "double \fBfetopZ\fP"
.br
.ti -1c
.RI "double \fBCool10ZdistanceFromBottomtoBottom\fP"
.br
.ti -1c
.RI "double \fBcool10R\fP"
.br
.ti -1c
.RI "double \fBcool10BottomGap\fP"
.br
.ti -1c
.RI "std::string \fBCoreShape\fP"
.br
.ti -1c
.RI "std::string \fBFuelPlacement\fP"
.br
.ti -1c
.RI "double \fBRpos_fuel\fP"
.br
.ti -1c
.RI "double \fBCladdingZ\fP"
.br
.ti -1c
.RI "double \fBFuelZ\fP"
.br
.ti -1c
.RI "double \fBdbl_PolygoneWidth\fP"
.br
.ti -1c
.RI "std::string \fBFuelName\fP"
.br
.ti -1c
.RI "int \fBint_Nreplicate\fP"
.br
.ti -1c
.RI "double \fBint_Nlayer\fP"
.br
.ti -1c
.RI "double \fBdbl_rRodsGap\fP"
.br
.ti -1c
.RI "double \fBGraphiteThickness\fP"
.br
.ti -1c
.RI "double \fBAbsorberThickness\fP"
.br
.ti -1c
.RI "std::string \fBPathToCoreLatticeFile\fP"
.br
.ti -1c
.RI "std::string \fBPathToAssemblyLatticeFile\fP"
.br
.ti -1c
.RI "std::string \fBTypeOfMesh\fP"
.br
.ti -1c
.RI "std::string \fBpolarAxis\fP"
.br
.ti -1c
.RI "std::vector< double > \fBorigin_PolarMesh\fP"
.br
.ti -1c
.RI "int \fBnbinsR\fP"
.br
.ti -1c
.RI "double \fBminR\fP"
.br
.ti -1c
.RI "double \fBmaxR\fP"
.br
.ti -1c
.RI "double \fBminTheta\fP"
.br
.ti -1c
.RI "int \fBnbinsTheta\fP"
.br
.ti -1c
.RI "double \fBmaxTheta\fP"
.br
.ti -1c
.RI "int \fBnbinsX\fP"
.br
.ti -1c
.RI "double \fBminX\fP"
.br
.ti -1c
.RI "double \fBmaxX\fP"
.br
.ti -1c
.RI "int \fBnbinsY\fP"
.br
.ti -1c
.RI "double \fBminY\fP"
.br
.ti -1c
.RI "double \fBmaxY\fP"
.br
.ti -1c
.RI "int \fBnbinsZ\fP"
.br
.ti -1c
.RI "double \fBminZ\fP"
.br
.ti -1c
.RI "double \fBmaxZ\fP"
.br
.ti -1c
.RI "double \fBhexPitch\fP"
.br
.ti -1c
.RI "int \fBnbinsHexMinX\fP"
.br
.ti -1c
.RI "int \fBnbinsHexMaxX\fP"
.br
.ti -1c
.RI "int \fBnbinsHexMinY\fP"
.br
.ti -1c
.RI "int \fBnbinsHexMaxY\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBDPA\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBEnergyDeposited\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBDetectionChamber\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBSurfaceCurrentSpectrum\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBSurfaceFluenceSpectrum\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBVolumeFluenceSpectrum\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBFluenceMap\fP"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBFluenceMapBinning\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBPowerDensityMap\fP"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBPowerDensityMapBinning\fP"
.br
.ti -1c
.RI "bool \fBisEverythingNtuple\fP"
.br
.ti -1c
.RI "int \fBkeff_nbinsR2\fP"
.br
.ti -1c
.RI "int \fBkeff_nbinsTheta\fP"
.br
.ti -1c
.RI "int \fBkeff_nbinsZ\fP"
.br
.ti -1c
.RI "double \fBEcutp_target\fP"
.br
.ti -1c
.RI "double \fBEcutg_target\fP"
.br
.ti -1c
.RI "double \fBEcute_target\fP"
.br
.ti -1c
.RI "double \fBEcutp_lead\fP"
.br
.ti -1c
.RI "double \fBEcutg_lead\fP"
.br
.ti -1c
.RI "double \fBEcute_lead\fP"
.br
.ti -1c
.RI "double \fBEcutp_fuel\fP"
.br
.ti -1c
.RI "double \fBEcutg_fuel\fP"
.br
.ti -1c
.RI "double \fBEcute_fuel\fP"
.br
.ti -1c
.RI "double \fBEcutp_world\fP"
.br
.ti -1c
.RI "double \fBEcutg_world\fP"
.br
.ti -1c
.RI "double \fBEcute_world\fP"
.br
.ti -1c
.RI "std::string \fBSourceType\fP"
.br
.ti -1c
.RI "int \fBSourceNumber\fP"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBsrc_XYZdirection\fP"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBsrc_XYZposition\fP"
.br
.ti -1c
.RI "std::vector< double > \fBsrc_slabThicknesses\fP"
.br
.ti -1c
.RI "std::string \fBPathToBurnupFile\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBCoreConfig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBTMXInputParameters\fP class\&. 
.PP
Definition at line \fB23\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXInputParameters::TMXInputParameters ()"

.PP
Implementation of the \fBTMXInputParameters\fP class\&. 
.PP
Definition at line \fB26\fP of file \fBTMXInputParameters\&.cc\fP\&.
.SS "TMXInputParameters::~TMXInputParameters ()"

.PP
Definition at line \fB31\fP of file \fBTMXInputParameters\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXInputParameters::read (const std::string & strFileName)"

.PP
Definition at line \fB35\fP of file \fBTMXInputParameters\&.cc\fP\&.
.SS "void TMXInputParameters::verbose ()"

.PP
Definition at line \fB301\fP of file \fBTMXInputParameters\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double TMXInputParameters::AbsorberThickness"

.PP
Definition at line \fB116\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::airtopR"

.PP
Definition at line \fB88\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::AirTopZdistanceFromBottomtoTop"

.PP
Definition at line \fB89\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Al_thickness"

.PP
Definition at line \fB84\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Al_Tube_gap"

.PP
Definition at line \fB85\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::BeamEnergy"

.PP
Definition at line \fB38\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "bool TMXInputParameters::boolVisualization"

.PP
Definition at line \fB34\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::check1r"

.PP
Definition at line \fB71\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::CheckGap"

.PP
Definition at line \fB70\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::CladdingZ"

.PP
Definition at line \fB107\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::cool10BottomGap"

.PP
Definition at line \fB100\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::cool10R"

.PP
Definition at line \fB99\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Cool10ZdistanceFromBottomtoBottom"

.PP
Definition at line \fB98\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::CoolingTime"

.PP
Definition at line \fB43\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector< std::vector < std::string > > TMXInputParameters::CoreConfig"

.PP
Definition at line \fB189\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::CoreShape"

.PP
Definition at line \fB103\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::dbl_PolygoneWidth"

.PP
Definition at line \fB109\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::dbl_rRodsGap"

.PP
Definition at line \fB113\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::DetectionChamber"

.PP
Definition at line \fB149\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::DPA"

.PP
Definition at line \fB147\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecute_fuel"

.PP
Definition at line \fB175\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecute_lead"

.PP
Definition at line \fB172\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecute_target"

.PP
Definition at line \fB169\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecute_world"

.PP
Definition at line \fB178\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutg_fuel"

.PP
Definition at line \fB174\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutg_lead"

.PP
Definition at line \fB171\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutg_target"

.PP
Definition at line \fB168\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutg_world"

.PP
Definition at line \fB177\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutp_fuel"

.PP
Definition at line \fB173\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutp_lead"

.PP
Definition at line \fB170\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutp_target"

.PP
Definition at line \fB167\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Ecutp_world"

.PP
Definition at line \fB176\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::EnergyDeposited"

.PP
Definition at line \fB148\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::ErrorLimitMCCubicVolume"

.PP
Definition at line \fB57\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::ExtSourcePath"

.PP
Definition at line \fB59\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::fetopZ"

.PP
Definition at line \fB95\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::FluenceMap"

.PP
Definition at line \fB153\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<double> > TMXInputParameters::FluenceMapBinning"

.PP
Definition at line \fB154\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::FuelName"

.PP
Definition at line \fB110\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::FuelPlacement"

.PP
Definition at line \fB104\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::FuelZ"

.PP
Definition at line \fB108\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::Geometry"

.PP
Definition at line \fB46\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::GraphiteThickness"

.PP
Definition at line \fB115\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::h0"

.PP
Definition at line \fB66\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::hexPitch"

.PP
Definition at line \fB140\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::int_Nlayer"

.PP
Definition at line \fB112\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::int_Nreplicate"

.PP
Definition at line \fB111\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::int_Option"

.PP
Definition at line \fB48\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "bool TMXInputParameters::isAbla"

.PP
Definition at line \fB50\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "bool TMXInputParameters::isEverythingNtuple"

.PP
Definition at line \fB159\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "bool TMXInputParameters::isLEND"

.PP
Definition at line \fB52\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "bool TMXInputParameters::isRandomSeed"

.PP
Definition at line \fB51\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "bool TMXInputParameters::isThreadMerging"

.PP
Definition at line \fB36\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::keff_nbinsR2"

.PP
Definition at line \fB162\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::keff_nbinsTheta"

.PP
Definition at line \fB163\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::keff_nbinsZ"

.PP
Definition at line \fB164\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::maxR"

.PP
Definition at line \fB127\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::maxTheta"

.PP
Definition at line \fB130\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::maxX"

.PP
Definition at line \fB133\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::maxY"

.PP
Definition at line \fB136\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::maxZ"

.PP
Definition at line \fB139\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::MCCubicVolumeLVname"

.PP
Definition at line \fB58\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::minR"

.PP
Definition at line \fB126\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::minTheta"

.PP
Definition at line \fB128\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::minX"

.PP
Definition at line \fB132\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::minY"

.PP
Definition at line \fB135\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::minZ"

.PP
Definition at line \fB138\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::NbDiscardCycle"

.PP
Definition at line \fB56\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsHexMaxX"

.PP
Definition at line \fB142\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsHexMaxY"

.PP
Definition at line \fB144\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsHexMinX"

.PP
Definition at line \fB141\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsHexMinY"

.PP
Definition at line \fB143\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsR"

.PP
Definition at line \fB125\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsTheta"

.PP
Definition at line \fB129\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsX"

.PP
Definition at line \fB131\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsY"

.PP
Definition at line \fB134\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nbinsZ"

.PP
Definition at line \fB137\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::Ncycle"

.PP
Definition at line \fB41\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::Nparticles"

.PP
Definition at line \fB39\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::Nrun"

.PP
Definition at line \fB40\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nT"

.PP
Definition at line \fB77\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::nThreads"

.PP
Definition at line \fB35\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<double> TMXInputParameters::origin_PolarMesh"

.PP
Definition at line \fB124\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<double> TMXInputParameters::originKeff"

.PP
Definition at line \fB60\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::P_beam"

.PP
Definition at line \fB44\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::P_core"

.PP
Definition at line \fB45\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::PathToAssemblyLatticeFile"

.PP
Definition at line \fB119\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::PathToBurnupFile"

.PP
Definition at line \fB188\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::PathToCoreLatticeFile"

.PP
Definition at line \fB118\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::physName"

.PP
Definition at line \fB49\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::polarAxis"

.PP
Definition at line \fB123\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::PowerDensityMap"

.PP
Definition at line \fB155\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<double> > TMXInputParameters::PowerDensityMapBinning"

.PP
Definition at line \fB156\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::PrintModulo"

.PP
Definition at line \fB53\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::reflectorZdistanceFromBottomtoTop"

.PP
Definition at line \fB92\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Rpos_fuel"

.PP
Definition at line \fB105\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::SourceNumber"

.PP
Definition at line \fB182\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::SourceType"

.PP
Definition at line \fB181\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<double> TMXInputParameters::src_slabThicknesses"

.PP
Definition at line \fB185\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector< std::vector<double> > TMXInputParameters::src_XYZdirection"

.PP
Definition at line \fB183\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector< std::vector<double> > TMXInputParameters::src_XYZposition"

.PP
Definition at line \fB184\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::str_ROOTFileName"

.PP
Definition at line \fB47\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::SurfaceCurrentSpectrum"

.PP
Definition at line \fB150\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::SurfaceFluenceSpectrum"

.PP
Definition at line \fB151\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Target_Al_Xgap"

.PP
Definition at line \fB82\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::Target_Al_Ygap"

.PP
Definition at line \fB83\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::targetgap"

.PP
Definition at line \fB78\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::TemperatureFuel"

.PP
Definition at line \fB55\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::TemperatureWorld"

.PP
Definition at line \fB54\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::TimeOfRun"

.PP
Definition at line \fB42\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::string TMXInputParameters::TypeOfMesh"

.PP
Definition at line \fB122\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "int TMXInputParameters::Verbose"

.PP
Definition at line \fB37\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "std::vector<std::vector<std::string> > TMXInputParameters::VolumeFluenceSpectrum"

.PP
Definition at line \fB152\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::worldR"

.PP
Definition at line \fB64\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::worldZ"

.PP
Definition at line \fB65\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::xTarget"

.PP
Definition at line \fB74\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::XtargetPosition"

.PP
Definition at line \fB69\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::xVariable"

.PP
Definition at line \fB79\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::yTarget"

.PP
Definition at line \fB75\fP of file \fBTMXInputParameters\&.hh\fP\&.
.SS "double TMXInputParameters::zTargetHeight"

.PP
Definition at line \fB76\fP of file \fBTMXInputParameters\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
