.TH "TMXLattice" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXLattice
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetLatticeMap\fP (std::string latticeMapFile)"
.br
.ti -1c
.RI "void \fBsetHexagonalLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetSquareLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double pitch)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterVolume\fP (std::string elementId, G4LogicalVolume *daughterVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterAction\fP (std::string elementId, std::function< void(double)> action)"
.br
.ti -1c
.RI "void \fBsetElementRotation\fP (G4RotationMatrix *elementRotation)"
.br
.ti -1c
.RI "void \fBsetElementTranslation\fP (G4ThreeVector elementTranslation)"
.br
.ti -1c
.RI "std::string \fBgetLatticeType\fP ()"
.br
.ti -1c
.RI "void \fBplaceLattice\fP (bool overlap)"
.br
.ti -1c
.RI "void \fBsetLatticeMap\fP (std::string latticeMapFile)"
.br
.ti -1c
.RI "void \fBsetHexagonalLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetSquareLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double pitch)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterVolume\fP (std::string elementId, G4LogicalVolume *daughterVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterAction\fP (std::string elementId, std::function< void(double)> action)"
.br
.ti -1c
.RI "void \fBsetElementRotation\fP (G4RotationMatrix *elementRotation)"
.br
.ti -1c
.RI "void \fBsetElementTranslation\fP (G4ThreeVector elementTranslation)"
.br
.ti -1c
.RI "std::string \fBgetLatticeType\fP ()"
.br
.ti -1c
.RI "void \fBplaceLattice\fP (bool overlap)"
.br
.ti -1c
.RI "void \fBsetLatticeMap\fP (std::string latticeMapFile)"
.br
.ti -1c
.RI "void \fBsetHexagonalLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetSquareLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double pitch)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterVolume\fP (std::string elementId, G4LogicalVolume *daughterVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterAction\fP (std::string elementId, std::function< void(double)> action)"
.br
.ti -1c
.RI "void \fBsetElementRotation\fP (G4RotationMatrix *elementRotation)"
.br
.ti -1c
.RI "void \fBsetElementTranslation\fP (G4ThreeVector elementTranslation)"
.br
.ti -1c
.RI "std::string \fBgetLatticeType\fP ()"
.br
.ti -1c
.RI "void \fBplaceLattice\fP (bool overlap)"
.br
.ti -1c
.RI "void \fBsetLatticeMap\fP (std::string latticeMapFile)"
.br
.ti -1c
.RI "void \fBsetHexagonalLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetSquareLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double pitch)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterVolume\fP (std::string elementId, G4LogicalVolume *daughterVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterAction\fP (std::string elementId, std::function< void(double)> action)"
.br
.ti -1c
.RI "void \fBsetElementRotation\fP (G4RotationMatrix *elementRotation)"
.br
.ti -1c
.RI "void \fBsetElementTranslation\fP (G4ThreeVector elementTranslation)"
.br
.ti -1c
.RI "std::string \fBgetLatticeType\fP ()"
.br
.ti -1c
.RI "void \fBplaceLattice\fP (bool overlap)"
.br
.ti -1c
.RI "void \fBsetLatticeMap\fP (std::string latticeMapFile)"
.br
.ti -1c
.RI "void \fBsetHexagonalLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetSquareLattice\fP ()"
.br
.ti -1c
.RI "void \fBsetPitch\fP (G4double pitch)"
.br
.ti -1c
.RI "void \fBsetMotherVolume\fP (G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterVolume\fP (std::string elementId, G4LogicalVolume *daughterVolume)"
.br
.ti -1c
.RI "void \fBaddDaughterAction\fP (std::string elementId, std::function< void(double)> action)"
.br
.ti -1c
.RI "void \fBsetElementRotation\fP (G4RotationMatrix *elementRotation)"
.br
.ti -1c
.RI "void \fBsetElementTranslation\fP (G4ThreeVector elementTranslation)"
.br
.ti -1c
.RI "std::string \fBgetLatticeType\fP ()"
.br
.ti -1c
.RI "void \fBplaceLattice\fP (bool overlap)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB29\fP of file \fBTMXLattice\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXLattice::TMXLattice ()"

.PP
Definition at line \fB28\fP of file \fBTMXLattice\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXLattice::addDaughterAction (std::string elementId, std::function< void(double)> action)"

.PP
Definition at line \fB70\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::addDaughterVolume (std::string elementId, G4LogicalVolume * daughterVolume)"

.PP
Definition at line \fB66\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "std::string TMXLattice::getLatticeType ()"

.PP
Definition at line \fB85\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::placeLattice (bool overlap)"

.PP
Definition at line \fB110\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setElementRotation (G4RotationMatrix * elementRotation)"

.PP
Definition at line \fB74\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setElementTranslation (G4ThreeVector elementTranslation)"

.PP
Definition at line \fB78\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setHexagonalLattice ()"

.PP
Definition at line \fB48\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setLatticeMap (std::string latticeMapFile)"

.PP
Definition at line \fB44\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setMotherVolume (G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB62\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setPitch (G4double pitch)"

.PP
Definition at line \fB58\fP of file \fBTMXLattice\&.cc\fP\&.
.SS "void TMXLattice::setSquareLattice ()"

.PP
Definition at line \fB53\fP of file \fBTMXLattice\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
