.TH "TMXMergeThreadsResults" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXMergeThreadsResults \- Description of the \fBTMXMergeThreadsResults\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXMergeThreadsResults\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXMergeThreadsResults\fP (int Nb_Threads)"
.br
.RI "Implementation of the \fBTMXMergeThreadsResults\fP class\&. "
.ti -1c
.RI "void \fBAddNewValues\fP (int Thread_Numb, double N0, double Ntot, double FissionByN0, double sigma_FissionByN0, double NeutronFromFission, double NeutronFromInelastic, double AbsorptionInU235, double sigma_AbsorptionInU235, double CaptureInU238, double sigma_CaptureInU238, double k_src, double sigma_ksrc, double k_eff, double sigma_keff, double nu, double eta, double sigma_eta, double epsilon, double sigma_eps, double Cap_abs, double sigma_Cap_Abs, double EtotEbeam_perFission, double sigma_EtotEbeam_perFission, double Edep_perFission, double sigma_Edep_perFission, double G0, double sigma_G0, double G_G0k, double sigma_G_G0k, double G_Pth, double sigma_G_Pth, double Chi2, double sigma_Chi2)"
.br
.ti -1c
.RI "void \fBAddNew_k_values\fP (int Thread_Numb, std::vector< double > k, std::vector< double > sigma_k)"
.br
.ti -1c
.RI "void \fBWriteResults\fP (std::string str_ROOTFileName, int int_Option, int RunNumber)"
.br
.ti -1c
.RI "std::vector< double > \fBGetKeffMerged\fP () const"
.br
.ti -1c
.RI "void \fBInitialize\fP (int Nb_Threads)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of the \fBTMXMergeThreadsResults\fP class\&. 
.PP
Definition at line \fB30\fP of file \fBTMXMergeThreadsResults\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXMergeThreadsResults::TMXMergeThreadsResults (int Nb_Threads)"

.PP
Implementation of the \fBTMXMergeThreadsResults\fP class\&. 
.PP
Definition at line \fB32\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.
.SS "TMXMergeThreadsResults::~TMXMergeThreadsResults ()"

.PP
Definition at line \fB43\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXMergeThreadsResults::AddNew_k_values (int Thread_Numb, std::vector< double > k, std::vector< double > sigma_k)"

.PP
Definition at line \fB92\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.
.SS "void TMXMergeThreadsResults::AddNewValues (int Thread_Numb, double N0, double Ntot, double FissionByN0, double sigma_FissionByN0, double NeutronFromFission, double NeutronFromInelastic, double AbsorptionInU235, double sigma_AbsorptionInU235, double CaptureInU238, double sigma_CaptureInU238, double k_src, double sigma_ksrc, double k_eff, double sigma_keff, double nu, double eta, double sigma_eta, double epsilon, double sigma_eps, double Cap_abs, double sigma_Cap_Abs, double EtotEbeam_perFission, double sigma_EtotEbeam_perFission, double Edep_perFission, double sigma_Edep_perFission, double G0, double sigma_G0, double G_G0k, double sigma_G_G0k, double G_Pth, double sigma_G_Pth, double Chi2, double sigma_Chi2)"

.PP
Definition at line \fB47\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.
.SS "std::vector< double > TMXMergeThreadsResults::GetKeffMerged () const"

.PP
Definition at line \fB224\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.
.SS "void TMXMergeThreadsResults::Initialize (int Nb_Threads)"

.PP
Definition at line \fB264\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.
.SS "void TMXMergeThreadsResults::WriteResults (std::string str_ROOTFileName, int int_Option, int RunNumber)"

.PP
Definition at line \fB97\fP of file \fBTMXMergeThreadsResults\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
