.TH "TMXMCCubicVolume" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXMCCubicVolume
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXMCCubicVolume\fP (\fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBsetErrorLimit\fP (const double errorLimit)"
.br
.ti -1c
.RI "void \fBsetNavigator\fP (G4Navigator *navigator)"
.br
.ti -1c
.RI "void \fBsetNumberOfPoints\fP (const long nbPoints)"
.br
.ti -1c
.RI "void \fBsetSlicedLogicalVolume\fP (std::string logicalVolumeName)"
.br
.ti -1c
.RI "void \fBsetSliceBoundariesZ\fP (G4double minZ, G4double maxZ, int nbinsZ)"
.br
.ti -1c
.RI "void \fBbuildMapLogicalVolume\fP ()"
.br
.ti -1c
.RI "void \fBbuildMapMaterial\fP ()"
.br
.ti -1c
.RI "double \fBgetError\fP (const long nbPointsInsideVolume) const"
.br
.ti -1c
.RI "double \fBgetMaximumError\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorLV\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorMat\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorSlicedLV\fP () const"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunMCVolumeEstimator\fP ()"
.br
.ti -1c
.RI "void \fBrunSlicedLogicalVolumeMC\fP ()"
.br
.ti -1c
.RI "void \fBcalculationMC\fP (const long nbPoints, const G4double halfX, const G4double halfY, const G4double halfZ)"
.br
.ti -1c
.RI "void \fBcalculationMCSlicedLV\fP (const long nbPoints, const G4double halfX, const G4double halfY, G4String LVname)"
.br
.ti -1c
.RI "void \fBprintLogicalVolumeMap\fP () const"
.br
.ti -1c
.RI "void \fBprintMaterialMap\fP () const"
.br
.ti -1c
.RI "void \fBprintSlicedVolume\fP () const"
.br
.ti -1c
.RI "\fBTMXMCCubicVolume\fP (\fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBsetErrorLimit\fP (const double errorLimit)"
.br
.ti -1c
.RI "void \fBsetNavigator\fP (G4Navigator *navigator)"
.br
.ti -1c
.RI "void \fBsetNumberOfPoints\fP (const long nbPoints)"
.br
.ti -1c
.RI "void \fBsetSlicedLogicalVolume\fP (std::string logicalVolumeName)"
.br
.ti -1c
.RI "void \fBsetSliceBoundariesZ\fP (G4double minZ, G4double maxZ, int nbinsZ)"
.br
.ti -1c
.RI "void \fBbuildMapLogicalVolume\fP ()"
.br
.ti -1c
.RI "void \fBbuildMapMaterial\fP ()"
.br
.ti -1c
.RI "double \fBgetError\fP (const long nbPointsInsideVolume) const"
.br
.ti -1c
.RI "double \fBgetMaximumError\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorLV\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorMat\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorSlicedLV\fP () const"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunMCVolumeEstimator\fP ()"
.br
.ti -1c
.RI "void \fBrunSlicedLogicalVolumeMC\fP ()"
.br
.ti -1c
.RI "void \fBcalculationMC\fP (const long nbPoints, const G4double halfX, const G4double halfY, const G4double halfZ)"
.br
.ti -1c
.RI "void \fBcalculationMCSlicedLV\fP (const long nbPoints, const G4double halfX, const G4double halfY, G4String LVname)"
.br
.ti -1c
.RI "void \fBprintLogicalVolumeMap\fP () const"
.br
.ti -1c
.RI "void \fBprintMaterialMap\fP () const"
.br
.ti -1c
.RI "void \fBprintSlicedVolume\fP () const"
.br
.ti -1c
.RI "\fBTMXMCCubicVolume\fP (\fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBsetErrorLimit\fP (const double errorLimit)"
.br
.ti -1c
.RI "void \fBsetNavigator\fP (G4Navigator *navigator)"
.br
.ti -1c
.RI "void \fBsetNumberOfPoints\fP (const long nbPoints)"
.br
.ti -1c
.RI "void \fBsetSlicedLogicalVolume\fP (std::string logicalVolumeName)"
.br
.ti -1c
.RI "void \fBsetSliceBoundariesZ\fP (G4double minZ, G4double maxZ, int nbinsZ)"
.br
.ti -1c
.RI "void \fBbuildMapLogicalVolume\fP ()"
.br
.ti -1c
.RI "void \fBbuildMapMaterial\fP ()"
.br
.ti -1c
.RI "double \fBgetError\fP (const long nbPointsInsideVolume) const"
.br
.ti -1c
.RI "double \fBgetMaximumError\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorLV\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorMat\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorSlicedLV\fP () const"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunMCVolumeEstimator\fP ()"
.br
.ti -1c
.RI "void \fBrunSlicedLogicalVolumeMC\fP ()"
.br
.ti -1c
.RI "void \fBcalculationMC\fP (const long nbPoints, const G4double halfX, const G4double halfY, const G4double halfZ)"
.br
.ti -1c
.RI "void \fBcalculationMCSlicedLV\fP (const long nbPoints, const G4double halfX, const G4double halfY, G4String LVname)"
.br
.ti -1c
.RI "void \fBprintLogicalVolumeMap\fP () const"
.br
.ti -1c
.RI "void \fBprintMaterialMap\fP () const"
.br
.ti -1c
.RI "void \fBprintSlicedVolume\fP () const"
.br
.ti -1c
.RI "\fBTMXMCCubicVolume\fP (\fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBsetErrorLimit\fP (const double errorLimit)"
.br
.ti -1c
.RI "void \fBsetNavigator\fP (G4Navigator *navigator)"
.br
.ti -1c
.RI "void \fBsetNumberOfPoints\fP (const long nbPoints)"
.br
.ti -1c
.RI "void \fBsetSlicedLogicalVolume\fP (std::string logicalVolumeName)"
.br
.ti -1c
.RI "void \fBsetSliceBoundariesZ\fP (G4double minZ, G4double maxZ, int nbinsZ)"
.br
.ti -1c
.RI "void \fBbuildMapLogicalVolume\fP ()"
.br
.ti -1c
.RI "void \fBbuildMapMaterial\fP ()"
.br
.ti -1c
.RI "double \fBgetError\fP (const long nbPointsInsideVolume) const"
.br
.ti -1c
.RI "double \fBgetMaximumError\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorLV\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorMat\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorSlicedLV\fP () const"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunMCVolumeEstimator\fP ()"
.br
.ti -1c
.RI "void \fBrunSlicedLogicalVolumeMC\fP ()"
.br
.ti -1c
.RI "void \fBcalculationMC\fP (const long nbPoints, const G4double halfX, const G4double halfY, const G4double halfZ)"
.br
.ti -1c
.RI "void \fBcalculationMCSlicedLV\fP (const long nbPoints, const G4double halfX, const G4double halfY, G4String LVname)"
.br
.ti -1c
.RI "void \fBprintLogicalVolumeMap\fP () const"
.br
.ti -1c
.RI "void \fBprintMaterialMap\fP () const"
.br
.ti -1c
.RI "void \fBprintSlicedVolume\fP () const"
.br
.ti -1c
.RI "\fBTMXMCCubicVolume\fP (\fBTMXInputParameters\fP *p)"
.br
.ti -1c
.RI "void \fBsetErrorLimit\fP (const double errorLimit)"
.br
.ti -1c
.RI "void \fBsetNavigator\fP (G4Navigator *navigator)"
.br
.ti -1c
.RI "void \fBsetNumberOfPoints\fP (const long nbPoints)"
.br
.ti -1c
.RI "void \fBsetSlicedLogicalVolume\fP (std::string logicalVolumeName)"
.br
.ti -1c
.RI "void \fBsetSliceBoundariesZ\fP (G4double minZ, G4double maxZ, int nbinsZ)"
.br
.ti -1c
.RI "void \fBbuildMapLogicalVolume\fP ()"
.br
.ti -1c
.RI "void \fBbuildMapMaterial\fP ()"
.br
.ti -1c
.RI "double \fBgetError\fP (const long nbPointsInsideVolume) const"
.br
.ti -1c
.RI "double \fBgetMaximumError\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorLV\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorMat\fP () const"
.br
.ti -1c
.RI "double \fBgetMaximumErrorSlicedLV\fP () const"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunMCVolumeEstimator\fP ()"
.br
.ti -1c
.RI "void \fBrunSlicedLogicalVolumeMC\fP ()"
.br
.ti -1c
.RI "void \fBcalculationMC\fP (const long nbPoints, const G4double halfX, const G4double halfY, const G4double halfZ)"
.br
.ti -1c
.RI "void \fBcalculationMCSlicedLV\fP (const long nbPoints, const G4double halfX, const G4double halfY, G4String LVname)"
.br
.ti -1c
.RI "void \fBprintLogicalVolumeMap\fP () const"
.br
.ti -1c
.RI "void \fBprintMaterialMap\fP () const"
.br
.ti -1c
.RI "void \fBprintSlicedVolume\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBTMXMCCubicVolume\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXMCCubicVolume::TMXMCCubicVolume (\fBTMXInputParameters\fP * p)"

.PP
Definition at line \fB26\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "TMXMCCubicVolume::~TMXMCCubicVolume ()"

.PP
Definition at line \fB39\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXMCCubicVolume::buildMapLogicalVolume ()"

.PP
Definition at line \fB45\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::buildMapMaterial ()"

.PP
Definition at line \fB58\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::calculationMC (const long nbPoints, const G4double halfX, const G4double halfY, const G4double halfZ)"

.PP
Definition at line \fB346\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::calculationMCSlicedLV (const long nbPoints, const G4double halfX, const G4double halfY, G4String LVname)"

.PP
Definition at line \fB364\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "double TMXMCCubicVolume::getError (const long nbPointsInsideVolume) const"

.PP
Definition at line \fB108\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "double TMXMCCubicVolume::getMaximumError () const"

.PP
Definition at line \fB112\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "double TMXMCCubicVolume::getMaximumErrorLV () const"

.PP
Definition at line \fB121\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "double TMXMCCubicVolume::getMaximumErrorMat () const"

.PP
Definition at line \fB132\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "double TMXMCCubicVolume::getMaximumErrorSlicedLV () const"

.PP
Definition at line \fB143\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::printLogicalVolumeMap () const"

.PP
Definition at line \fB386\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::printMaterialMap () const"

.PP
Definition at line \fB439\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::printSlicedVolume () const"

.PP
Definition at line \fB491\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::run ()"

.PP
Definition at line \fB183\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::runMCVolumeEstimator ()"

.PP
Definition at line \fB193\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::runSlicedLogicalVolumeMC ()"

.PP
Definition at line \fB270\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::setErrorLimit (const double errorLimit)"

.PP
Definition at line \fB76\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::setNavigator (G4Navigator * navigator)"

.PP
Definition at line \fB80\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::setNumberOfPoints (const long nbPoints)"

.PP
Definition at line \fB85\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::setSliceBoundariesZ (G4double minZ, G4double maxZ, int nbinsZ)"

.PP
Definition at line \fB94\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.
.SS "void TMXMCCubicVolume::setSlicedLogicalVolume (std::string logicalVolumeName)"

.PP
Definition at line \fB89\fP of file \fBTMXMCCubicVolume\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
