.TH "TMXMaterial" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXMaterial \- Definition of the \fBTMXMaterial\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXMaterial\&.hh>\fP
.PP
Inherits G4Material, G4Material, G4Material, G4Material, and G4Material\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.RI "Implementation of the \fBTMXMaterial\fP class\&. "
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double ensity, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4int nAtoms, std::string name='')"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4double fraction, std::string name='')"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double ensity, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4int nAtoms, std::string name='')"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4double fraction, std::string name='')"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double ensity, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4int nAtoms, std::string name='')"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4double fraction, std::string name='')"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double ensity, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4int nAtoms, std::string name='')"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4double fraction, std::string name='')"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP (const G4String &name, G4double ensity, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=CLHEP::STP_Temperature, G4double pressure=CLHEP::STP_Pressure)"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4int nAtoms, std::string name='')"
.br
.ti -1c
.RI "void \fBAddElement\fP (int IZA, G4double fraction, std::string name='')"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBExist\fP (G4String)"
.br
.ti -1c
.RI "static \fBTMXMaterial\fP * \fBFind\fP (G4String)"
.br
.ti -1c
.RI "static void \fBPrintMaterialVolumesMasses\fP ()"
.br
.ti -1c
.RI "static void \fBPrintMassLatticeByElement\fP (const G4String elementName)"
.br
.ti -1c
.RI "static bool \fBExist\fP (G4String)"
.br
.ti -1c
.RI "static \fBTMXMaterial\fP * \fBFind\fP (G4String)"
.br
.ti -1c
.RI "static void \fBPrintMaterialVolumesMasses\fP ()"
.br
.ti -1c
.RI "static void \fBPrintMassLatticeByElement\fP (const G4String elementName)"
.br
.ti -1c
.RI "static bool \fBExist\fP (G4String)"
.br
.ti -1c
.RI "static \fBTMXMaterial\fP * \fBFind\fP (G4String)"
.br
.ti -1c
.RI "static void \fBPrintMaterialVolumesMasses\fP ()"
.br
.ti -1c
.RI "static void \fBPrintMassLatticeByElement\fP (const G4String elementName)"
.br
.ti -1c
.RI "static bool \fBExist\fP (G4String)"
.br
.ti -1c
.RI "static \fBTMXMaterial\fP * \fBFind\fP (G4String)"
.br
.ti -1c
.RI "static void \fBPrintMaterialVolumesMasses\fP ()"
.br
.ti -1c
.RI "static void \fBPrintMassLatticeByElement\fP (const G4String elementName)"
.br
.ti -1c
.RI "static bool \fBExist\fP (G4String)"
.br
.ti -1c
.RI "static \fBTMXMaterial\fP * \fBFind\fP (G4String)"
.br
.ti -1c
.RI "static void \fBPrintMaterialVolumesMasses\fP ()"
.br
.ti -1c
.RI "static void \fBPrintTotalMaterialVolumesMasses\fP ()"
.br
.ti -1c
.RI "static void \fBPrintMassLatticeByElement\fP (const G4String elementName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXMaterial\fP class\&. 
.PP
Definition at line \fB23\fP of file \fBTMXMaterial\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXMaterial::TMXMaterial (const G4String & name, G4double density, G4int nComponents, G4State state = \fCkStateUndefined\fP, G4double temp = \fCCLHEP::STP_Temperature\fP, G4double pressure = \fCCLHEP::STP_Pressure\fP)"

.PP
Implementation of the \fBTMXMaterial\fP class\&. 
.PP
Definition at line \fB23\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "TMXMaterial::TMXMaterial (const G4String & name, G4double ensity, const G4Material * baseMaterial, G4State state = \fCkStateUndefined\fP, G4double temp = \fCCLHEP::STP_Temperature\fP, G4double pressure = \fCCLHEP::STP_Pressure\fP)"

.PP
Definition at line \fB27\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "TMXMaterial::~TMXMaterial ()"

.PP
Definition at line \fB31\fP of file \fBTMXMaterial\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXMaterial::AddElement (int IZA, G4double fraction, std::string name = \fC''\fP)"

.PP
Definition at line \fB70\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "void TMXMaterial::AddElement (int IZA, G4int nAtoms, std::string name = \fC''\fP)"

.PP
Definition at line \fB66\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "bool TMXMaterial::Exist (G4String name)\fC [static]\fP"

.PP
Definition at line \fB36\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXMaterial::Find (G4String name)\fC [static]\fP"

.PP
Definition at line \fB53\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "void TMXMaterial::PrintMassLatticeByElement (const G4String elementName)\fC [static]\fP"
((double)nbPins)
.PP
Definition at line \fB131\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "void TMXMaterial::PrintMaterialVolumesMasses ()\fC [static]\fP"

.PP
Definition at line \fB106\fP of file \fBTMXMaterial\&.cc\fP\&.
.SS "void TMXMaterial::PrintTotalMaterialVolumesMasses ()\fC [static]\fP"

.PP
Definition at line \fB130\fP of file \fBTMXMaterial\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
