.TH "TMXNeutronSource" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXNeutronSource
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXNeutronSource\fP (\fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "\fBTMXAbstractTargetAssembly\fP * \fBgetNeutronEmmiter\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractBeamPipe\fP * \fBgetBeamPipe\fP ()"
.br
.ti -1c
.RI "void \fBbuildGeometry\fP ()"
.br
.RI "\fBTMXNeutronSource::buildGeometry\fP\&. "
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.RI "\fBTMXNeutronSource::placeGeometry\fP\&. "
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.RI "\fBTMXNeutronSource::VisualisationConfig\fP\&. "
.ti -1c
.RI "G4VSolid * \fBSubstractTarget\fP (G4VSolid *, G4ThreeVector, G4RotationMatrix *rot=nullptr)"
.br
.RI "\fBTMXNeutronSource::SubstractTarget\fP\&. "
.ti -1c
.RI "\fBTMXNeutronSource\fP (\fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "\fBTMXAbstractTargetAssembly\fP * \fBgetNeutronEmmiter\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractBeamPipe\fP * \fBgetBeamPipe\fP ()"
.br
.ti -1c
.RI "void \fBbuildGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBSubstractTarget\fP (G4VSolid *, G4ThreeVector, G4RotationMatrix *rot=nullptr)"
.br
.ti -1c
.RI "\fBTMXNeutronSource\fP (\fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "\fBTMXAbstractTargetAssembly\fP * \fBgetNeutronEmmiter\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractBeamPipe\fP * \fBgetBeamPipe\fP ()"
.br
.ti -1c
.RI "void \fBbuildGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBSubstractTarget\fP (G4VSolid *, G4ThreeVector, G4RotationMatrix *rot=nullptr)"
.br
.ti -1c
.RI "\fBTMXNeutronSource\fP (\fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "\fBTMXAbstractTargetAssembly\fP * \fBgetNeutronEmmiter\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractBeamPipe\fP * \fBgetBeamPipe\fP ()"
.br
.ti -1c
.RI "void \fBbuildGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBSubstractTarget\fP (G4VSolid *, G4ThreeVector, G4RotationMatrix *rot=nullptr)"
.br
.ti -1c
.RI "\fBTMXNeutronSource\fP (\fBTMXInputParameters\fP *)"
.br
.ti -1c
.RI "\fBTMXAbstractTargetAssembly\fP * \fBgetNeutronEmmiter\fP ()"
.br
.ti -1c
.RI "\fBTMXAbstractBeamPipe\fP * \fBgetBeamPipe\fP ()"
.br
.ti -1c
.RI "void \fBbuildGeometry\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "G4VSolid * \fBSubstractTarget\fP (G4VSolid *, G4ThreeVector, G4RotationMatrix *rot=nullptr)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static G4RotationMatrix * \fBDefineRotationMatrix\fP (G4ThreeVector *beamDirection)"
.br
.ti -1c
.RI "static G4RotationMatrix * \fBDefineRotationMatrix\fP (G4ThreeVector *beamDirection)"
.br
.ti -1c
.RI "static G4RotationMatrix * \fBDefineRotationMatrix\fP (G4ThreeVector *beamDirection)"
.br
.ti -1c
.RI "static G4RotationMatrix * \fBDefineRotationMatrix\fP (G4ThreeVector *beamDirection)"
.br
.ti -1c
.RI "static G4RotationMatrix * \fBDefineRotationMatrix\fP (G4ThreeVector *beamDirection)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTMXInputParameters\fP * \fBm_p\fP"
.br
.ti -1c
.RI "\fBTMXAbstractTargetAssembly\fP * \fBm_NeutronEmmiter\fP"
.br
.ti -1c
.RI "\fBTMXAbstractBeamPipe\fP * \fBm_BeamPipe\fP"
.br
.ti -1c
.RI "G4LogicalVolume * \fBm_masterVolume\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBTMXNeutronSource\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXNeutronSource::TMXNeutronSource (\fBTMXInputParameters\fP * parameters)"

.PP
Definition at line \fB30\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "TMXNeutronSource::~TMXNeutronSource ()\fC [virtual]\fP"

.PP
Definition at line \fB38\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXNeutronSource::buildGeometry ()"

.PP
\fBTMXNeutronSource::buildGeometry\fP\&. 
.PP
Definition at line \fB83\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "G4RotationMatrix * TMXNeutronSource::DefineRotationMatrix (G4ThreeVector * beamDirection)\fC [static]\fP"

.PP
Definition at line \fB63\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "\fBTMXAbstractBeamPipe\fP * TMXNeutronSource::getBeamPipe ()"

.PP
Definition at line \fB53\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "\fBTMXAbstractTargetAssembly\fP * TMXNeutronSource::getNeutronEmmiter ()"

.PP
Definition at line \fB49\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "void TMXNeutronSource::placeGeometry (bool overlap, G4ThreeVector * centerTarget, G4ThreeVector * beamDirection, G4LogicalVolume * masterVolume)"

.PP
\fBTMXNeutronSource::placeGeometry\fP\&. 
.PP
Definition at line \fB199\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "G4VSolid * TMXNeutronSource::SubstractTarget (G4VSolid * SolidToBeDrilled, G4ThreeVector translation, G4RotationMatrix * rot = \fCnullptr\fP)"

.PP
\fBTMXNeutronSource::SubstractTarget\fP\&. 
.PP
Definition at line \fB225\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SS "void TMXNeutronSource::VisualisationConfig ()"

.PP
\fBTMXNeutronSource::VisualisationConfig\fP\&. 
.PP
Definition at line \fB217\fP of file \fBTMXNeutronSource\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTMXAbstractBeamPipe\fP * TMXNeutronSource::m_BeamPipe\fC [protected]\fP"

.PP
Definition at line \fB57\fP of file \fBTMXNeutronSource\&.hh\fP\&.
.SS "G4LogicalVolume * TMXNeutronSource::m_masterVolume\fC [protected]\fP"

.PP
Definition at line \fB58\fP of file \fBTMXNeutronSource\&.hh\fP\&.
.SS "\fBTMXAbstractTargetAssembly\fP * TMXNeutronSource::m_NeutronEmmiter\fC [protected]\fP"

.PP
Definition at line \fB56\fP of file \fBTMXNeutronSource\&.hh\fP\&.
.SS "\fBTMXInputParameters\fP * TMXNeutronSource::m_p\fC [protected]\fP"

.PP
Definition at line \fB51\fP of file \fBTMXNeutronSource\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
