.TH "TMXNeutronicParam" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXNeutronicParam \- Definition of the \fBTMXNeutronicParam\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXNeutronicParam\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXNeutronicParam\fP (int, \fBTMXMergeThreadsResults\fP &, \fBTMXInputParameters\fP *, int)"
.br
.RI "Implementation of the \fBTMXNeutronicParam\fP class\&. "
.ti -1c
.RI "void \fBInitialize\fP (int, \fBTMXMergeThreadsResults\fP &, \fBTMXInputParameters\fP *, int)"
.br
.ti -1c
.RI "void \fBDoCalculationAndPrintValues\fP (int N0abs, double NeutronFromFission, double NeutronFromInelastic, double &N_AbsU5, double RelativeAbundanceU235, double &N_CapU8, double &N_absTot, double RelativeAbundanceU238, double Edep, double Ebeam, long int NbFission, double EperFission, int Nb_EperFission, double nu, long int &FissionByN0, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight, int nEvt, std::vector< long int > &NbNperGeneration, long int fTotNbNeutrons)"
.br
.ti -1c
.RI "void \fBDoCalculationAndPrintValues\fP (int N0abs, double NeutronFromFission, double NeutronFromInelastic, double &N_AbsU5, double RelativeAbundanceU235, double &N_CapU8, double &N_absTot, double RelativeAbundanceU238, double Edep, double Ebeam, long int NbFission, double EperFission, int Nb_EperFission, double nu, long int &FissionByN0, \fBTMXRandomDistribution3D\fP &RadiusAnglesHeight)"
.br
.ti -1c
.RI "void \fBUpdateValues\fP (int nEvt, std::vector< long int > &NbNperGeneration, long int fTotNbNeutrons)"
.br
.ti -1c
.RI "void \fBUpdateKeffEstimators\fP (double Keff_collision, double Keff_analogAbs, double Keff_implicitAbs, double Keff_trackLength, long NsourceNeutronPerEvent)"
.br
.ti -1c
.RI "double \fBGetEtotDeposit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXNeutronicParam\fP class\&. 
.PP
Definition at line \fB29\fP of file \fBTMXNeutronicParam\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXNeutronicParam::TMXNeutronicParam (int RunNumber, \fBTMXMergeThreadsResults\fP & mergedOutput, \fBTMXInputParameters\fP * parameter, int threadID)"

.PP
Implementation of the \fBTMXNeutronicParam\fP class\&. 
.PP
Definition at line \fB19\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SS "TMXNeutronicParam::~TMXNeutronicParam ()"

.PP
Definition at line \fB23\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXNeutronicParam::DoCalculationAndPrintValues (int N0abs, double NeutronFromFission, double NeutronFromInelastic, double & N_AbsU5, double RelativeAbundanceU235, double & N_CapU8, double & N_absTot, double RelativeAbundanceU238, double Edep, double Ebeam, long int NbFission, double EperFission, int Nb_EperFission, double nu, long int & FissionByN0, \fBTMXRandomDistribution3D\fP & RadiusAnglesHeight)"

.PP
Definition at line \fB86\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SS "void TMXNeutronicParam::DoCalculationAndPrintValues (int N0abs, double NeutronFromFission, double NeutronFromInelastic, double & N_AbsU5, double RelativeAbundanceU235, double & N_CapU8, double & N_absTot, double RelativeAbundanceU238, double Edep, double Ebeam, long int NbFission, double EperFission, int Nb_EperFission, double nu, long int & FissionByN0, \fBTMXRandomDistribution3D\fP & RadiusAnglesHeight, int nEvt, std::vector< long int > & NbNperGeneration, long int fTotNbNeutrons)"

.PP
Definition at line \fB81\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SS "double TMXNeutronicParam::GetEtotDeposit ()"

.PP
Definition at line \fB405\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SS "void TMXNeutronicParam::Initialize (int RunNumber, \fBTMXMergeThreadsResults\fP & mergedOutput, \fBTMXInputParameters\fP * parameter, int threadID)"

.PP
Definition at line \fB26\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SS "void TMXNeutronicParam::UpdateKeffEstimators (double Keff_collision, double Keff_analogAbs, double Keff_implicitAbs, double Keff_trackLength, long NsourceNeutronPerEvent)"

.PP
Definition at line \fB393\fP of file \fBTMXNeutronicParam\&.cc\fP\&.
.SS "void TMXNeutronicParam::UpdateValues (int nEvt, std::vector< long int > & NbNperGeneration, long int fTotNbNeutrons)"

.PP
Definition at line \fB75\fP of file \fBTMXNeutronicParam\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
