.TH "TMXNeutronGenerationCounting" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXNeutronGenerationCounting \- Implementation of the \fBTMXNeutronGenerationCounting\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXNeutronGenerationCounting\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXNeutronGenerationCounting\fP (\fBEventAction\fP *eventAction, \fBTMXInputParameters\fP *parameter)"
.br
.RI "Implementation of the \fBTMXNeutronGenerationCounting\fP class\&. "
.ti -1c
.RI "void \fBNeutronGenerationCounting\fP (const G4Step *theStep, const G4Track *secondary, int nNeutrons, int &Nb_inelastic)"
.br
.ti -1c
.RI "void \fBInitializeGenerationFlag\fP (const G4Step *theStep, bool isStepInTargetRegion)"
.br
.ti -1c
.RI "bool \fBGetStatus_SourceNeutron\fP ()"
.br
.ti -1c
.RI "long \fBGetNeutronGeneration\fP ()"
.br
.ti -1c
.RI "\fBTMXNeutronGenerationCounting\fP (\fBEventAction\fP *eventAction, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBNeutronGenerationCounting\fP (const G4Step *theStep, const G4Track *secondary, int nNeutrons, int &Nb_inelastic)"
.br
.ti -1c
.RI "void \fBInitializeGenerationFlag\fP (const G4Step *theStep, bool isStepInTargetRegion)"
.br
.ti -1c
.RI "bool \fBGetStatus_SourceNeutron\fP ()"
.br
.ti -1c
.RI "long \fBGetNeutronGeneration\fP ()"
.br
.ti -1c
.RI "\fBTMXNeutronGenerationCounting\fP (\fBEventAction\fP *eventAction, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBNeutronGenerationCounting\fP (const G4Step *theStep, const G4Track *secondary, int nNeutrons, int &Nb_inelastic)"
.br
.ti -1c
.RI "void \fBInitializeGenerationFlag\fP (const G4Step *theStep, bool isStepInTargetRegion)"
.br
.ti -1c
.RI "bool \fBGetStatus_SourceNeutron\fP ()"
.br
.ti -1c
.RI "long \fBGetNeutronGeneration\fP ()"
.br
.ti -1c
.RI "\fBTMXNeutronGenerationCounting\fP (\fBEventAction\fP *eventAction, \fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBNeutronGenerationCounting\fP (const G4Step *theStep, const G4Track *secondary, int nNeutrons, int &Nb_inelastic)"
.br
.ti -1c
.RI "void \fBInitializeGenerationFlag\fP (const G4Step *theStep, bool isStepInTargetRegion)"
.br
.ti -1c
.RI "bool \fBGetStatus_SourceNeutron\fP ()"
.br
.ti -1c
.RI "long \fBGetNeutronGeneration\fP ()"
.br
.ti -1c
.RI "\fBTMXNeutronGenerationCounting\fP (\fBRunAction\fP *runAction, \fBEventAction\fP *eventAction, \fBTMXInputParameters\fP *parameter)"
.br
.RI "Implementation of the \fBTMXNeutronGenerationCounting\fP class\&. "
.ti -1c
.RI "void \fBNeutronGenerationCounting\fP (const G4Step *theStep, const G4Track *secondary, int nNeutrons, int &Nb_inelastic)"
.br
.ti -1c
.RI "void \fBInitializeGenerationFlag\fP (const G4Step *theStep, bool isStepInTargetRegion)"
.br
.ti -1c
.RI "bool \fBGetStatus_SourceNeutron\fP ()"
.br
.ti -1c
.RI "long \fBGetNeutronGeneration\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the \fBTMXNeutronGenerationCounting\fP class\&. 
.PP
Definition at line \fB29\fP of file \fBTMXNeutronGenerationCounting\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXNeutronGenerationCounting::TMXNeutronGenerationCounting (\fBEventAction\fP * eventAction, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBTMXNeutronGenerationCounting\fP class\&. 
.PP
Definition at line \fB24\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.
.SS "TMXNeutronGenerationCounting::~TMXNeutronGenerationCounting ()"

.PP
Definition at line \fB28\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.
.SS "TMXNeutronGenerationCounting::TMXNeutronGenerationCounting (\fBRunAction\fP * runAction, \fBEventAction\fP * eventAction, \fBTMXInputParameters\fP * parameter)"

.PP
Implementation of the \fBTMXNeutronGenerationCounting\fP class\&. 
.PP
Definition at line \fB24\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "long TMXNeutronGenerationCounting::GetNeutronGeneration ()"

.PP
Definition at line \fB254\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.
.SS "bool TMXNeutronGenerationCounting::GetStatus_SourceNeutron ()"

.PP
Definition at line \fB250\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.
.SS "void TMXNeutronGenerationCounting::InitializeGenerationFlag (const G4Step * theStep, bool isStepInTargetRegion)"

.PP
Definition at line \fB62\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.
.SS "void TMXNeutronGenerationCounting::NeutronGenerationCounting (const G4Step * theStep, const G4Track * secondary, int nNeutrons, int & Nb_inelastic)"

.PP
Definition at line \fB141\fP of file \fBTMXNeutronGenerationCounting\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
