.TH "TMXOption" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXOption \- Definition of the \fBTMXOption\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXOption\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXOption\fP (int Option)"
.br
.RI "Implementation of the \fBTMXOption\fP class\&. "
.ti -1c
.RI "void \fBInitialize\fP (int Option)"
.br
.ti -1c
.RI "bool \fBIsKeffCalculation\fP ()"
.br
.ti -1c
.RI "bool \fBIsMultiplicationKilled\fP ()"
.br
.ti -1c
.RI "bool \fBIsTransmutationCalculation\fP ()"
.br
.ti -1c
.RI "bool \fBIsSourceNeutronEADefinition\fP ()"
.br
.ti -1c
.RI "bool \fBIsSrcNeutronDefinitionWithNxN\fP ()"
.br
.ti -1c
.RI "bool \fBIsPIMKeffCalculation\fP ()"
.br
.ti -1c
.RI "bool \fBIsMCCubicVolumeCalculation\fP ()"
.br
.ti -1c
.RI "bool \fBIsBurnupCalculation\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsKeffCalculation\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsMultiplicationKilled\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsTransmutationCalculation\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsSourceNeutronEADefinition\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsSrcNeutronDefinitionWithNxN\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsPIMKeffCalculation\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsMCCubicVolumeCalculation\fP (int Option)"
.br
.ti -1c
.RI "static bool \fBIsBurnupCalculation\fP (int Option)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXOption\fP class\&. 
.PP
Definition at line \fB16\fP of file \fBTMXOption\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXOption::TMXOption (int Option)"

.PP
Implementation of the \fBTMXOption\fP class\&. 
.PP
Definition at line \fB15\fP of file \fBTMXOption\&.cc\fP\&.
.SS "TMXOption::~TMXOption ()"

.PP
Definition at line \fB19\fP of file \fBTMXOption\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXOption::Initialize (int Option)"

.PP
Definition at line \fB22\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsBurnupCalculation ()"

.PP
Definition at line \fB33\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsBurnupCalculation (int Option)\fC [static]\fP"

.PP
Definition at line \fB42\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsKeffCalculation ()"

.PP
Definition at line \fB26\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsKeffCalculation (int Option)\fC [static]\fP"

.PP
Definition at line \fB35\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsMCCubicVolumeCalculation ()"

.PP
Definition at line \fB32\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsMCCubicVolumeCalculation (int Option)\fC [static]\fP"

.PP
Definition at line \fB41\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsMultiplicationKilled ()"

.PP
Definition at line \fB27\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsMultiplicationKilled (int Option)\fC [static]\fP"

.PP
Definition at line \fB36\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsPIMKeffCalculation ()"

.PP
Definition at line \fB31\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsPIMKeffCalculation (int Option)\fC [static]\fP"

.PP
Definition at line \fB40\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsSourceNeutronEADefinition ()"

.PP
Definition at line \fB29\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsSourceNeutronEADefinition (int Option)\fC [static]\fP"

.PP
Definition at line \fB38\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsSrcNeutronDefinitionWithNxN ()"

.PP
Definition at line \fB30\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsSrcNeutronDefinitionWithNxN (int Option)\fC [static]\fP"

.PP
Definition at line \fB39\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsTransmutationCalculation ()"

.PP
Definition at line \fB28\fP of file \fBTMXOption\&.cc\fP\&.
.SS "bool TMXOption::IsTransmutationCalculation (int Option)\fC [static]\fP"

.PP
Definition at line \fB37\fP of file \fBTMXOption\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
