.TH "TMXPhysicalVolumeName" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXPhysicalVolumeName \- Definition of the \fBTMXPhysicalVolumeName\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXPhysicalVolumeName\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXPhysicalVolumeName\fP ()"
.br
.RI "Implementation of the \fBTMXPhysicalVolumeName\fP class\&. "
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBSetNewVolumeInTargetRegion\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeInLeadRegion\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeInCoreRegion\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeInVesselRegion\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeInWorldRegion\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsTarget\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsTargetCoolant\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsTargetTub\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsLead\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsFuel\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsWorld\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsBeamPipe\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsBeamWindow\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsModerator\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsVessel\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsSample\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetNewVolumeAsSensor\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "int \fBGetVolumeNumber\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "void \fBSetVolumeNumber\fP (int VolumeNumber, std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "bool \fBIsTarget\fP (std::string PhysicalVolumeName)"
.br
.ti -1c
.RI "bool \fBIsLead\fP (std::string PhysicalVolumeName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXPhysicalVolumeName\fP class\&. 
.PP
Definition at line \fB25\fP of file \fBTMXPhysicalVolumeName\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXPhysicalVolumeName::TMXPhysicalVolumeName ()"

.PP
Implementation of the \fBTMXPhysicalVolumeName\fP class\&. 
.PP
Definition at line \fB15\fP of file \fBTMXPhysicalVolumeName\&.cc\fP\&.
.SS "TMXPhysicalVolumeName::~TMXPhysicalVolumeName ()"

.PP
Definition at line \fB19\fP of file \fBTMXPhysicalVolumeName\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int TMXPhysicalVolumeName::GetVolumeNumber (std::string PhysicalVolumeName)\fC [inline]\fP"

.PP
Definition at line \fB53\fP of file \fBTMXPhysicalVolumeName\&.hh\fP\&.
.SS "void TMXPhysicalVolumeName::Initialize ()"

.PP
Definition at line \fB22\fP of file \fBTMXPhysicalVolumeName\&.cc\fP\&.
.SS "bool TMXPhysicalVolumeName::IsLead (std::string PhysicalVolumeName)\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBTMXPhysicalVolumeName\&.hh\fP\&.
.SS "bool TMXPhysicalVolumeName::IsTarget (std::string PhysicalVolumeName)\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBTMXPhysicalVolumeName\&.hh\fP\&.
.SS "void TMXPhysicalVolumeName::SetVolumeNumber (int VolumeNumber, std::string PhysicalVolumeName)\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBTMXPhysicalVolumeName\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
