.TH "TMXRadiativeTarget" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXRadiativeTarget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, and \fBTMXAbstractTargetAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXRadiativeTarget\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXRadiativeTarget\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXRadiativeTarget\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXRadiativeTarget\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXRadiativeTarget\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBTMXRadiativeTarget\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXRadiativeTarget::TMXRadiativeTarget (\fBTMXInputParameters\fP * parameters, const std::string & TargetAssemblyName)"

.PP
Definition at line \fB18\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXRadiativeTarget::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB53\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SS "void TMXRadiativeTarget::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB26\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SS "void TMXRadiativeTarget::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB99\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SS "void TMXRadiativeTarget::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXRadiativeTarget::placeGeometry (bool overlap, G4ThreeVector * centerTarget, G4ThreeVector * beamDirection, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB64\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SS "G4ThreeVector TMXRadiativeTarget::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXRadiativeTarget::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXRadiativeTarget::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXRadiativeTarget::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeSlabs (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix *, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB74\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SS "void TMXRadiativeTarget::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeTube (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB87\fP of file \fBTMXRadiativeTarget\&.cc\fP\&.
.SS "void TMXRadiativeTarget::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXRadiativeTarget::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
