.TH "TMXReflectorKIPT" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXReflectorKIPT
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, \fBTMXAbstractFuelAssembly\fP, and \fBTMXAbstractFuelAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXReflectorKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0\&., G4bool isAssembly=false)"
.br
.ti -1c
.RI "void \fBcreateGeometryAssembly\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometryBlock\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector position, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXReflectorKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0\&., G4bool isAssembly=false)"
.br
.ti -1c
.RI "void \fBcreateGeometryAssembly\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometryBlock\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector position, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXReflectorKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0\&., G4bool isAssembly=false)"
.br
.ti -1c
.RI "void \fBcreateGeometryAssembly\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometryBlock\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector position, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXReflectorKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0\&., G4bool isAssembly=false)"
.br
.ti -1c
.RI "void \fBcreateGeometryAssembly\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometryBlock\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector position, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.ti -1c
.RI "\fBTMXReflectorKIPT\fP (const std::string &, \fBTMXInputParameters\fP *, G4double rodInsertion=0\&., G4bool isAssembly=false)"
.br
.ti -1c
.RI "void \fBcreateGeometryAssembly\fP ()"
.br
.ti -1c
.RI "void \fBcreateGeometryBlock\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBvisualisationConfig\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (bool overlap, G4ThreeVector position, G4RotationMatrix *rotation, G4LogicalVolume *masterVolume)"
.br
.ti -1c
.RI "void \fBsubtract\fP (G4LogicalVolume *subtracterLV)"
.br
.ti -1c
.RI "G4double \fBGetOuterRadius\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB41\fP of file \fBTMXReflectorKIPT\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXReflectorKIPT::TMXReflectorKIPT (const std::string & FuelAssemblyName, \fBTMXInputParameters\fP * parameter, G4double rodInsertion = \fC0\&.\fP, G4bool isAssembly = \fCfalse\fP)"

.PP
Definition at line \fB37\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "TMXReflectorKIPT::~TMXReflectorKIPT ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXReflectorKIPT\&.hh\fP\&.
.SS "TMXReflectorKIPT::~TMXReflectorKIPT ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXReflectorKIPT\&.hh\fP\&.
.SS "TMXReflectorKIPT::~TMXReflectorKIPT ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXReflectorKIPT\&.hh\fP\&.
.SS "TMXReflectorKIPT::~TMXReflectorKIPT ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXReflectorKIPT\&.hh\fP\&.
.SS "TMXReflectorKIPT::~TMXReflectorKIPT ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTMXReflectorKIPT\&.hh\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXReflectorKIPT::createGeometryAssembly ()"

.PP
Definition at line \fB76\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "void TMXReflectorKIPT::createGeometryBlock ()"

.PP
Definition at line \fB114\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "void TMXReflectorKIPT::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.PP
Definition at line \fB56\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "void TMXReflectorKIPT::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXReflectorKIPT::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXReflectorKIPT::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "void TMXReflectorKIPT::createMaterial ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractFuelAssembly\fP\&.
.SS "G4double TMXReflectorKIPT::GetOuterRadius ()"

.PP
Definition at line \fB235\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "void TMXReflectorKIPT::placeGeometry (bool overlap, G4ThreeVector position, G4RotationMatrix * rotation, G4LogicalVolume * masterVolume)"

.PP
Definition at line \fB172\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "void TMXReflectorKIPT::subtract (G4LogicalVolume * subtracterLV)"

.PP
Definition at line \fB157\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.
.SS "void TMXReflectorKIPT::visualisationConfig ()"

.PP
Definition at line \fB178\fP of file \fBTMXReflectorKIPT\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
