.TH "TMXRandomDistribution3D" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXRandomDistribution3D \- Description of the \fBTMXRandomDistribution3D\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXRandomDistribution3D\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXRandomDistribution3D\fP (int nbinsX, double Xmin, double Xmax, int nbinsY=1, double Ymin=0, double Ymax=0, int nbinsZ=1, double Zmin=0, double Zmax=0)"
.br
.RI "Implementation of the \fBTMXRandomDistribution3D\fP class\&. "
.ti -1c
.RI "void \fBChangeAllWeights\fP (std::vector< double > weight)"
.br
.ti -1c
.RI "void \fBAddBinWeight\fP (double X, double Y=0, double Z=0)"
.br
.ti -1c
.RI "void \fBAddBinWeights\fP (std::vector< std::vector< double > > vec_pos)"
.br
.ti -1c
.RI "double \fBFire\fP (double &Y, double &Z)"
.br
.ti -1c
.RI "std::vector< double > \fBGetWeights\fP ()"
.br
.ti -1c
.RI "std::vector< double > \fBGetUnnormedWeights\fP ()"
.br
.ti -1c
.RI "std::vector< double > \fBGetInitialUnnormedWeights\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of the \fBTMXRandomDistribution3D\fP class\&. 
.PP
Definition at line \fB23\fP of file \fBTMXRandomDistribution3D\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXRandomDistribution3D::TMXRandomDistribution3D (int nbinsX, double Xmin, double Xmax, int nbinsY = \fC1\fP, double Ymin = \fC0\fP, double Ymax = \fC0\fP, int nbinsZ = \fC1\fP, double Zmin = \fC0\fP, double Zmax = \fC0\fP)"

.PP
Implementation of the \fBTMXRandomDistribution3D\fP class\&. 
.PP
Definition at line \fB21\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "TMXRandomDistribution3D::~TMXRandomDistribution3D ()"

.PP
Definition at line \fB46\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXRandomDistribution3D::AddBinWeight (double X, double Y = \fC0\fP, double Z = \fC0\fP)"

.PP
Definition at line \fB57\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "void TMXRandomDistribution3D::AddBinWeights (std::vector< std::vector< double > > vec_pos)"

.PP
Definition at line \fB75\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "void TMXRandomDistribution3D::ChangeAllWeights (std::vector< double > weight)"

.PP
Definition at line \fB50\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "double TMXRandomDistribution3D::Fire (double & Y, double & Z)"

.PP
Definition at line \fB100\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "std::vector< double > TMXRandomDistribution3D::GetInitialUnnormedWeights ()"

.PP
Definition at line \fB126\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "std::vector< double > TMXRandomDistribution3D::GetUnnormedWeights ()"

.PP
Definition at line \fB122\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "std::vector< double > TMXRandomDistribution3D::GetWeights ()"

.PP
Definition at line \fB118\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.
.SS "void TMXRandomDistribution3D::Initialize ()"

.PP
Definition at line \fB130\fP of file \fBTMXRandomDistribution3D\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
