.TH "TMXReactorRez" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXReactorRez
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractReactor\fP, \fBTMXAbstractReactor\fP, \fBTMXAbstractReactor\fP, \fBTMXAbstractReactor\fP, and \fBTMXAbstractReactor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXReactorRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceNeutronSource\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceCore\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXReactorRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceNeutronSource\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceCore\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXReactorRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceNeutronSource\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceCore\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXReactorRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceNeutronSource\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceCore\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "\fBTMXReactorRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceNeutronSource\fP (bool, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBbuildAndPlaceCore\fP (bool, G4LogicalVolume *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "G4Element * \fBElementExists\fP (int, double)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (std::string)"
.br
.ti -1c
.RI "void \fBVisualisationConfigCore\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (int, double)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (std::string)"
.br
.ti -1c
.RI "void \fBVisualisationConfigCore\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (int, double)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (std::string)"
.br
.ti -1c
.RI "void \fBVisualisationConfigCore\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (int, double)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (std::string)"
.br
.ti -1c
.RI "void \fBVisualisationConfigCore\fP (G4LogicalVolume *)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (int, double)"
.br
.ti -1c
.RI "G4Element * \fBElementExists\fP (std::string)"
.br
.ti -1c
.RI "void \fBVisualisationConfigCore\fP (G4LogicalVolume *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB39\fP of file \fBTMXReactorRez\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXReactorRez::TMXReactorRez (\fBTMXInputParameters\fP * parameters, const std::string & ReactorAssemblyName)"

.PP
Definition at line \fB42\fP of file \fBTMXReactorRez\&.cc\fP\&.
.SS "TMXReactorRez::~TMXReactorRez ()"

.PP
Definition at line \fB47\fP of file \fBTMXReactorRez\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXReactorRez::buildAndPlaceCore (bool overlap, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.PP
Definition at line \fB63\fP of file \fBTMXReactorRez\&.cc\fP\&.
.SS "void TMXReactorRez::buildAndPlaceCore (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceCore (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceCore (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceCore (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceNeutronSource (bool overlap, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.PP
Definition at line \fB49\fP of file \fBTMXReactorRez\&.cc\fP\&.
.SS "void TMXReactorRez::buildAndPlaceNeutronSource (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceNeutronSource (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceNeutronSource (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "void TMXReactorRez::buildAndPlaceNeutronSource (bool, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractReactor\fP\&.
.SS "G4Element * TMXReactorRez::ElementExists (int Z, double A)\fC [protected]\fP"

.PP
Definition at line \fB94\fP of file \fBTMXReactorRez\&.cc\fP\&.
.SS "G4Element * TMXReactorRez::ElementExists (std::string name)\fC [protected]\fP"

.PP
Definition at line \fB105\fP of file \fBTMXReactorRez\&.cc\fP\&.
.SS "void TMXReactorRez::VisualisationConfigCore (G4LogicalVolume * LV_pool)\fC [protected]\fP"

.PP
Definition at line \fB116\fP of file \fBTMXReactorRez\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
