.TH "TMXScoringPowerDensityMap" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXScoringPowerDensityMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractScoring\fP, \fBTMXAbstractScoring\fP, \fBTMXAbstractScoring\fP, \fBTMXAbstractScoring\fP, and \fBTMXAbstractScoringMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXScoringPowerDensityMap\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVName\fP ()"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "double \fBgetRingVolume\fP (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.ti -1c
.RI "void \fBprintSummary\fP ()"
.br
.ti -1c
.RI "\fBTMXScoringPowerDensityMap\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVName\fP ()"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "double \fBgetRingVolume\fP (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.ti -1c
.RI "void \fBprintSummary\fP ()"
.br
.ti -1c
.RI "\fBTMXScoringPowerDensityMap\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVName\fP ()"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "double \fBgetRingVolume\fP (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.ti -1c
.RI "void \fBprintSummary\fP ()"
.br
.ti -1c
.RI "\fBTMXScoringPowerDensityMap\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBbuildMapPVName\fP ()"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "double \fBgetRingVolume\fP (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.ti -1c
.RI "void \fBprintSummary\fP ()"
.br
.ti -1c
.RI "\fBTMXScoringPowerDensityMap\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.ti -1c
.RI "void \fBprintSummary\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBTMXScoringPowerDensityMap\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXScoringPowerDensityMap::TMXScoringPowerDensityMap (\fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB21\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SS "TMXScoringPowerDensityMap::~TMXScoringPowerDensityMap ()\fC [virtual]\fP"

.PP
Definition at line \fB27\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXScoringPowerDensityMap::buildMapPVName ()"

.PP
Definition at line \fB33\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SS "double TMXScoringPowerDensityMap::getRingVolume (G4double rPosition, double rBin, double rMin, double rMax, double zBin, double zMin, double zMax)"

.PP
Definition at line \fB104\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SS "void TMXScoringPowerDensityMap::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.PP
Definition at line \fB114\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SS "void TMXScoringPowerDensityMap::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::printSummary ()"

.PP
Definition at line \fB126\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SS "void TMXScoringPowerDensityMap::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.PP
Definition at line \fB59\fP of file \fBTMXScoringPowerDensityMap\&.cc\fP\&.
.SS "void TMXScoringPowerDensityMap::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.SS "void TMXScoringPowerDensityMap::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
