.TH "TMXStopTheRun" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXStopTheRun \- Definition of the \fBTMXStopTheRun\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXStopTheRun\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBTMXInputParameters\fP *InputParameters)"
.br
.ti -1c
.RI "void \fBUserSteppingAction\fP ()"
.br
.ti -1c
.RI "void \fBUserBeginOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBUserEndOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBSetWriteROOTFile\fP (bool ToBeWritten)"
.br
.ti -1c
.RI "void \fBSetWaitFlag\fP (bool waitFlag)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBTMXInputParameters\fP *InputParameters)"
.br
.ti -1c
.RI "void \fBUserSteppingAction\fP ()"
.br
.ti -1c
.RI "void \fBUserBeginOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBUserEndOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBSetWriteROOTFile\fP (bool ToBeWritten)"
.br
.ti -1c
.RI "void \fBSetWaitFlag\fP (bool waitFlag)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBTMXInputParameters\fP *InputParameters)"
.br
.ti -1c
.RI "void \fBUserSteppingAction\fP ()"
.br
.ti -1c
.RI "void \fBUserBeginOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBUserEndOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBSetWriteROOTFile\fP (bool ToBeWritten)"
.br
.ti -1c
.RI "void \fBSetWaitFlag\fP (bool waitFlag)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBTMXInputParameters\fP *InputParameters)"
.br
.ti -1c
.RI "void \fBUserSteppingAction\fP ()"
.br
.ti -1c
.RI "void \fBUserBeginOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBUserEndOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBSetWriteROOTFile\fP (bool ToBeWritten)"
.br
.ti -1c
.RI "void \fBSetWaitFlag\fP (bool waitFlag)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBTMXInputParameters\fP *InputParameters)"
.br
.ti -1c
.RI "void \fBUserSteppingAction\fP ()"
.br
.ti -1c
.RI "void \fBUserBeginOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBUserEndOfEventAction\fP ()"
.br
.ti -1c
.RI "void \fBSetWriteROOTFile\fP (bool ToBeWritten)"
.br
.ti -1c
.RI "void \fBSetWaitFlag\fP (bool waitFlag)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTMXStopTheRun\fP * \fBgetInstance\fP ()"
.br
.ti -1c
.RI "static \fBTMXStopTheRun\fP * \fBgetInstance\fP ()"
.br
.ti -1c
.RI "static \fBTMXStopTheRun\fP * \fBgetInstance\fP ()"
.br
.ti -1c
.RI "static \fBTMXStopTheRun\fP * \fBgetInstance\fP ()"
.br
.ti -1c
.RI "static \fBTMXStopTheRun\fP * \fBgetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXStopTheRun\fP class\&. 
.PP
Definition at line \fB20\fP of file \fBTMXStopTheRun\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXStopTheRun::~TMXStopTheRun ()"

.PP
Definition at line \fB39\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTMXStopTheRun\fP * TMXStopTheRun::getInstance ()\fC [static]\fP"

.PP
Definition at line \fB194\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SS "void TMXStopTheRun::Initialize (\fBTMXInputParameters\fP * InputParameters)"

.PP
Definition at line \fB44\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SS "void TMXStopTheRun::SetWaitFlag (bool waitFlag)"

.PP
Definition at line \fB215\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SS "void TMXStopTheRun::SetWriteROOTFile (bool ToBeWritten)"

.PP
Definition at line \fB211\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SS "void TMXStopTheRun::UserBeginOfEventAction ()"

.PP
Definition at line \fB64\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SS "void TMXStopTheRun::UserEndOfEventAction ()"

.PP
Definition at line \fB70\fP of file \fBTMXStopTheRun\&.cc\fP\&.
.SS "void TMXStopTheRun::UserSteppingAction ()"

.PP
Definition at line \fB58\fP of file \fBTMXStopTheRun\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
