.TH "TMXScoringEverythingNNtuple" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXScoringEverythingNNtuple
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractScoringNtuple\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXScoringEverythingNNtuple\fP (\fBTMXInputParameters\fP *parameter)"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep, G4int reasonID, G4int EveryVol, G4int FissionVol, G4int CaptureVol, G4int InelasticVol, G4int nnPrimeVol, G4int nXnVol, G4int NbNGeneration, G4int OutPhysVol)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBTMXScoringEverythingNNtuple\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXScoringEverythingNNtuple::TMXScoringEverythingNNtuple (\fBTMXInputParameters\fP * parameter)"

.PP
Definition at line \fB21\fP of file \fBTMXScoringEverythingNNtuple\&.cc\fP\&.
.SS "TMXScoringEverythingNNtuple::~TMXScoringEverythingNNtuple ()\fC [virtual]\fP"

.PP
Definition at line \fB30\fP of file \fBTMXScoringEverythingNNtuple\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXScoringEverythingNNtuple::score (const G4Step * theStep, G4int reasonID, G4int EveryVol, G4int FissionVol, G4int CaptureVol, G4int InelasticVol, G4int nnPrimeVol, G4int nXnVol, G4int NbNGeneration, G4int OutPhysVol)"

.PP
Definition at line \fB36\fP of file \fBTMXScoringEverythingNNtuple\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
