.TH "TMXStatErrorCalc" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXStatErrorCalc \- Definition of the \fBTMXStatErrorCalc\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TMXStatErrorCalc\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXStatErrorCalc\fP ()"
.br
.RI "Implementation of the \fBTMXStatErrorCalc\fP class\&. "
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "double \fBGetSum\fP () const"
.br
.ti -1c
.RI "double \fBGetSumSquare\fP () const"
.br
.ti -1c
.RI "long int \fBGetNbValues\fP () const"
.br
.ti -1c
.RI "double \fBGetMeanValue\fP () const"
.br
.ti -1c
.RI "double \fBGetMeanError\fP () const"
.br
.ti -1c
.RI "double \fBGetStandardDeviation\fP () const"
.br
.ti -1c
.RI "double \fBStatErrorCalc\fP (double value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBTMXStatErrorCalc\fP class\&. 
.PP
Definition at line \fB19\fP of file \fBTMXStatErrorCalc\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXStatErrorCalc::TMXStatErrorCalc ()"

.PP
Implementation of the \fBTMXStatErrorCalc\fP class\&. 
.PP
Definition at line \fB17\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.
.SS "TMXStatErrorCalc::~TMXStatErrorCalc ()"

.PP
Definition at line \fB21\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double TMXStatErrorCalc::GetMeanError () const"

.PP
Definition at line \fB43\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.
.SS "double TMXStatErrorCalc::GetMeanValue () const"

.PP
Definition at line \fB37\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.
.SS "long int TMXStatErrorCalc::GetNbValues () const\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBTMXStatErrorCalc\&.hh\fP\&.
.SS "double TMXStatErrorCalc::GetStandardDeviation () const"

.PP
Definition at line \fB49\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.
.SS "double TMXStatErrorCalc::GetSum () const\fC [inline]\fP"

.PP
Definition at line \fB26\fP of file \fBTMXStatErrorCalc\&.hh\fP\&.
.SS "double TMXStatErrorCalc::GetSumSquare () const\fC [inline]\fP"

.PP
Definition at line \fB27\fP of file \fBTMXStatErrorCalc\&.hh\fP\&.
.SS "void TMXStatErrorCalc::Initialize ()"

.PP
Definition at line \fB24\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.
.SS "double TMXStatErrorCalc::StatErrorCalc (double value)"

.PP
Definition at line \fB30\fP of file \fBTMXStatErrorCalc\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
