.TH "TMXScoringEnergyDeposited" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXScoringEnergyDeposited
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractScoringAccumulable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXScoringEnergyDeposited\fP (\fBTMXInputParameters\fP *parameter, std::string name)"
.br
.ti -1c
.RI "void \fBscore\fP (const G4Step *theStep)"
.br
.ti -1c
.RI "void \fBprintAverage\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBTMXScoringEnergyDeposited\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXScoringEnergyDeposited::TMXScoringEnergyDeposited (\fBTMXInputParameters\fP * parameter, std::string name)"

.PP
Definition at line \fB20\fP of file \fBTMXScoringEnergyDeposited\&.cc\fP\&.
.SS "TMXScoringEnergyDeposited::~TMXScoringEnergyDeposited ()\fC [virtual]\fP"

.PP
Definition at line \fB24\fP of file \fBTMXScoringEnergyDeposited\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXScoringEnergyDeposited::printAverage () const\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.PP
Definition at line \fB48\fP of file \fBTMXScoringEnergyDeposited\&.cc\fP\&.
.SS "void TMXScoringEnergyDeposited::score (const G4Step * theStep)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractScoring\fP\&.
.PP
Definition at line \fB30\fP of file \fBTMXScoringEnergyDeposited\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
