.TH "TMXScoringParallelWorld" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXScoringParallelWorld
.SH SYNOPSIS
.br
.PP
.PP
Inherits G4VUserParallelWorld\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXScoringParallelWorld\fP (G4String worldName)"
.br
.ti -1c
.RI "void \fBBuildGeometry\fP ()"
.br
.ti -1c
.RI "void \fBBuildSensitiveDetector\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBTMXScoringParallelWorld\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXScoringParallelWorld::TMXScoringParallelWorld (G4String worldName)"

.PP
Definition at line \fB17\fP of file \fBTMXScoringParallelWorld\&.cc\fP\&.
.SS "TMXScoringParallelWorld::~TMXScoringParallelWorld ()\fC [virtual]\fP"

.PP
Definition at line \fB23\fP of file \fBTMXScoringParallelWorld\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXScoringParallelWorld::BuildGeometry ()"

.PP
Definition at line \fB30\fP of file \fBTMXScoringParallelWorld\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
