.TH "TMXTargetKIPT2" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXTargetKIPT2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, and \fBTMXAbstractTargetAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXTargetKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4Material * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4Material * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4Material * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4Material * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetKIPT2\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "G4Material * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "G4LogicalVolume * \fBm_masterVolume\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_coatingLogicalVolumes\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_platesLogicalVolumes\fP"
.br
.ti -1c
.RI "G4Material * \fBm_CoatingMaterial\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBTMXTargetKIPT2\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXTargetKIPT2::TMXTargetKIPT2 (\fBTMXInputParameters\fP * parameters, const std::string & TargetAssemblyName)"

.PP
Definition at line \fB45\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "TMXTargetKIPT2::~TMXTargetKIPT2 ()"

.PP
Definition at line \fB53\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXTargetKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB67\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB55\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXTargetKIPT2::getCoatingLogicalVolumes ()"

.PP
Definition at line \fB190\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "G4Material * TMXTargetKIPT2::getCoatingMaterial ()"

.PP
Definition at line \fB194\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "G4LogicalVolume * TMXTargetKIPT2::getMasterVolume ()"

.PP
Definition at line \fB198\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB175\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB166\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "G4ThreeVector TMXTargetKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetKIPT2::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB171\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB179\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB105\fP of file \fBTMXTargetKIPT2\&.cc\fP\&.
.SS "void TMXTargetKIPT2::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetKIPT2::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector< G4LogicalVolume * > TMXTargetKIPT2::m_coatingLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB80\fP of file \fBTMXTargetKIPT2\&.hh\fP\&.
.SS "G4Material * TMXTargetKIPT2::m_CoatingMaterial\fC [protected]\fP"

.PP
Definition at line \fB86\fP of file \fBTMXTargetKIPT2\&.hh\fP\&.
.SS "G4LogicalVolume * TMXTargetKIPT2::m_masterVolume\fC [protected]\fP"

.PP
Definition at line \fB75\fP of file \fBTMXTargetKIPT2\&.hh\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXTargetKIPT2::m_platesLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB81\fP of file \fBTMXTargetKIPT2\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
