.TH "TMXTargetRez" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXTargetRez
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, \fBTMXAbstractTargetAssembly\fP, and \fBTMXAbstractTargetAssembly\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXTargetRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetReflectorMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetReflectorMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetReflectorMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetReflectorMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.ti -1c
.RI "\fBTMXTargetRez\fP (\fBTMXInputParameters\fP *, const std::string &)"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBgetCoatingLogicalVolumes\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetCoatingMaterial\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetReflectorMaterial\fP ()"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP (double Kelvin_temperature=273\&.15)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP ()"
.br
.ti -1c
.RI "G4ThreeVector \fBplaceGeometry\fP (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceSlabs\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceCoolant\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBplaceTube\fP (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)"
.br
.ti -1c
.RI "void \fBVisualisationConfig\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "G4double \fBm_coatingThickness\fP"
.br
.ti -1c
.RI "G4double \fBm_targetPipeLength\fP"
.br
.ti -1c
.RI "std::vector< G4VSolid * > \fBm_coatingSolidVolumes\fP"
.br
.ti -1c
.RI "std::vector< G4LogicalVolume * > \fBm_coatingLogicalVolumes\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_CoatingMaterial\fP"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBm_ReflectorMaterial\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB44\fP of file \fBTMXTargetRez\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXTargetRez::TMXTargetRez (\fBTMXInputParameters\fP * parameters, const std::string & TargetAssemblyName)"

.PP
Definition at line \fB49\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "TMXTargetRez::~TMXTargetRez ()"

.PP
Definition at line \fB56\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXTargetRez::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB111\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createGeometry ()\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB58\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::createMaterial (double Kelvin_temperature = \fC273\&.15\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "std::vector< G4LogicalVolume * > TMXTargetRez::getCoatingLogicalVolumes ()"

.PP
Definition at line \fB298\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTargetRez::getCoatingMaterial ()"

.PP
Definition at line \fB309\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTargetRez::getReflectorMaterial ()"

.PP
Definition at line \fB313\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::placeCoolant (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB200\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeCoolant (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetRez::placeGeometry (bool overlap, G4ThreeVector * centerTarget, G4ThreeVector * beamDirection, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB161\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "G4ThreeVector TMXTargetRez::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetRez::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetRez::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "G4ThreeVector TMXTargetRez::placeGeometry (bool, G4ThreeVector *, G4ThreeVector *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeSlabs (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB176\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeSlabs (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeTube (bool overlap, G4ThreeVector * centerTarget, G4RotationMatrix * RotationFromXaxis, G4LogicalVolume * masterVolume)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB217\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::placeTube (bool, G4ThreeVector *, G4RotationMatrix *, G4LogicalVolume *)\fC [virtual]\fP"

.PP
Implements \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.PP
Definition at line \fB250\fP of file \fBTMXTargetRez\&.cc\fP\&.
.SS "void TMXTargetRez::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SS "void TMXTargetRez::VisualisationConfig ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTMXAbstractTargetAssembly\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector< G4LogicalVolume * > TMXTargetRez::m_coatingLogicalVolumes\fC [protected]\fP"

.PP
Definition at line \fB86\fP of file \fBTMXTargetRez\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXTargetRez::m_CoatingMaterial\fC [protected]\fP"

.PP
Definition at line \fB93\fP of file \fBTMXTargetRez\&.hh\fP\&.
.SS "std::vector< G4VSolid * > TMXTargetRez::m_coatingSolidVolumes\fC [protected]\fP"

.PP
Definition at line \fB80\fP of file \fBTMXTargetRez\&.hh\fP\&.
.SS "G4double TMXTargetRez::m_coatingThickness\fC [protected]\fP"

.PP
Definition at line \fB76\fP of file \fBTMXTargetRez\&.hh\fP\&.
.SS "\fBTMXMaterial\fP * TMXTargetRez::m_ReflectorMaterial\fC [protected]\fP"

.PP
Definition at line \fB94\fP of file \fBTMXTargetRez\&.hh\fP\&.
.SS "G4double TMXTargetRez::m_targetPipeLength\fC [protected]\fP"

.PP
Definition at line \fB77\fP of file \fBTMXTargetRez\&.hh\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
