.TH "TMXTarget" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMXTarget
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMXTarget\fP (std::string name, \fBTMXInputParameters\fP *p, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double extraLength_lower=0\&., G4double extraLength_upper=0\&.)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetEnvelopeMaterial\fP (\fBTMXMaterial\fP *envelopeMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetTargetMaterial\fP ()"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusUpperBeamEnvelope\fP ()"
.br
.ti -1c
.RI "\fBTMXTarget\fP (std::string name, \fBTMXInputParameters\fP *p, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double extraLength_lower=0\&., G4double extraLength_upper=0\&.)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetEnvelopeMaterial\fP (\fBTMXMaterial\fP *envelopeMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetTargetMaterial\fP ()"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusUpperBeamEnvelope\fP ()"
.br
.ti -1c
.RI "\fBTMXTarget\fP (std::string name, \fBTMXInputParameters\fP *p, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double extraLength_lower=0\&., G4double extraLength_upper=0\&.)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetEnvelopeMaterial\fP (\fBTMXMaterial\fP *envelopeMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetTargetMaterial\fP ()"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusUpperBeamEnvelope\fP ()"
.br
.ti -1c
.RI "\fBTMXTarget\fP (std::string name, \fBTMXInputParameters\fP *p, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double extraLength_lower=0\&., G4double extraLength_upper=0\&.)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetEnvelopeMaterial\fP (\fBTMXMaterial\fP *envelopeMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetTargetMaterial\fP ()"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusUpperBeamEnvelope\fP ()"
.br
.ti -1c
.RI "\fBTMXTarget\fP (std::string name, \fBTMXInputParameters\fP *p, G4LogicalVolume *motherVolume)"
.br
.ti -1c
.RI "void \fBcreateGeometry\fP (G4double extraLength_lower=0\&., G4double extraLength_upper=0\&.)"
.br
.ti -1c
.RI "void \fBcreateMaterial\fP ()"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBplaceGeometry\fP ()"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (G4ThreeVector translation)"
.br
.ti -1c
.RI "void \fBsetEnvelopeMaterial\fP (\fBTMXMaterial\fP *envelopeMaterial)"
.br
.ti -1c
.RI "G4LogicalVolume * \fBgetMasterVolume\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetTargetMaterial\fP ()"
.br
.ti -1c
.RI "G4double \fBgetOuterRadiusUpperBeamEnvelope\fP ()"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetSS316L\fP (std::string name)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetHT9\fP (std::string name)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetT91\fP (std::string name)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetLBE\fP (std::string name)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetVoid\fP (std::string name)"
.br
.ti -1c
.RI "\fBTMXMaterial\fP * \fBgetNatW\fP (std::string name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBTMXTarget\&.hh\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMXTarget::TMXTarget (std::string name, \fBTMXInputParameters\fP * p, G4LogicalVolume * motherVolume)"

.PP
Definition at line \fB34\fP of file \fBTMXTarget\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMXTarget::createGeometry (G4double extraLength_lower = \fC0\&.\fP, G4double extraLength_upper = \fC0\&.\fP)"
?
.PP
Definition at line \fB51\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "void TMXTarget::createMaterial ()"

.PP
Definition at line \fB540\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getHT9 (std::string name)"

.PP
Definition at line \fB717\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getLBE (std::string name)"

.PP
Definition at line \fB860\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "G4LogicalVolume * TMXTarget::getMasterVolume ()"

.PP
Definition at line \fB780\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getNatW (std::string name)"

.PP
Definition at line \fB892\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "G4double TMXTarget::getOuterRadiusUpperBeamEnvelope ()"

.PP
Definition at line \fB788\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getSS316L (std::string name)"

.PP
Definition at line \fB672\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getT91 (std::string name)"

.PP
Definition at line \fB789\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getTargetMaterial ()"

.PP
Definition at line \fB784\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "\fBTMXMaterial\fP * TMXTarget::getVoid (std::string name)"

.PP
Definition at line \fB877\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "void TMXTarget::placeGeometry ()"

.PP
Definition at line \fB762\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "void TMXTarget::placeGeometry (G4ThreeVector translation)"

.PP
Definition at line \fB757\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "void TMXTarget::setEnvelopeMaterial (\fBTMXMaterial\fP * envelopeMaterial)"

.PP
Definition at line \fB773\fP of file \fBTMXTarget\&.cc\fP\&.
.SS "void TMXTarget::setTranslation (G4ThreeVector translation)"

.PP
Definition at line \fB769\fP of file \fBTMXTarget\&.cc\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
