.TH "XSec" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSec
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXSec\fP (int iza, double awr, double qm, double qi)"
.br
.ti -1c
.RI "const vector< double > & \fBEn\fP () const"
.br
.ti -1c
.RI "const vector< double > & \fBXs\fP () const"
.br
.ti -1c
.RI "vector< double > & \fBEn\fP ()"
.br
.ti -1c
.RI "vector< double > & \fBXs\fP ()"
.br
.ti -1c
.RI "int \fBGetIZA\fP () const"
.br
.ti -1c
.RI "uint \fBNp\fP () const"
.br
.ti -1c
.RI "double \fBGetAWR\fP () const"
.br
.ti -1c
.RI "double \fBGetQM\fP () const"
.br
.ti -1c
.RI "double \fBGetQI\fP () const"
.br
.ti -1c
.RI "void \fBSetIZA\fP (int iza)"
.br
.ti -1c
.RI "void \fBSetAWR\fP (double awr)"
.br
.ti -1c
.RI "void \fBSetQM\fP (double qm)"
.br
.ti -1c
.RI "void \fBSetQI\fP (double qi)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBfIZA\fP"
.br
.ti -1c
.RI "double \fBfAWR\fP"
.br
.ti -1c
.RI "double \fBfQM\fP"
.br
.ti -1c
.RI "double \fBfQI\fP"
.br
.ti -1c
.RI "vector< double > \fBen\fP"
.br
.ti -1c
.RI "vector< double > \fBxs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBxendfb\&.C\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XSec::XSec ()\fC [inline]\fP"

.PP
Definition at line \fB17\fP of file \fBxendfb\&.C\fP\&.
.SS "XSec::XSec (int iza, double awr, double qm, double qi)\fC [inline]\fP"

.PP
Definition at line \fB19\fP of file \fBxendfb\&.C\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< double > & XSec::En ()\fC [inline]\fP"

.PP
Definition at line \fB25\fP of file \fBxendfb\&.C\fP\&.
.SS "const vector< double > & XSec::En () const\fC [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBxendfb\&.C\fP\&.
.SS "double XSec::GetAWR () const\fC [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBxendfb\&.C\fP\&.
.SS "int XSec::GetIZA () const\fC [inline]\fP"

.PP
Definition at line \fB29\fP of file \fBxendfb\&.C\fP\&.
.SS "double XSec::GetQI () const\fC [inline]\fP"

.PP
Definition at line \fB33\fP of file \fBxendfb\&.C\fP\&.
.SS "double XSec::GetQM () const\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBxendfb\&.C\fP\&.
.SS "uint XSec::Np () const\fC [inline]\fP"

.PP
Definition at line \fB30\fP of file \fBxendfb\&.C\fP\&.
.SS "void XSec::SetAWR (double awr)\fC [inline]\fP"

.PP
Definition at line \fB36\fP of file \fBxendfb\&.C\fP\&.
.SS "void XSec::SetIZA (int iza)\fC [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBxendfb\&.C\fP\&.
.SS "void XSec::SetQI (double qi)\fC [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBxendfb\&.C\fP\&.
.SS "void XSec::SetQM (double qm)\fC [inline]\fP"

.PP
Definition at line \fB37\fP of file \fBxendfb\&.C\fP\&.
.SS "vector< double > & XSec::Xs ()\fC [inline]\fP"

.PP
Definition at line \fB26\fP of file \fBxendfb\&.C\fP\&.
.SS "const vector< double > & XSec::Xs () const\fC [inline]\fP"

.PP
Definition at line \fB23\fP of file \fBxendfb\&.C\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<double> XSec::en\fC [protected]\fP"

.PP
Definition at line \fB44\fP of file \fBxendfb\&.C\fP\&.
.SS "double XSec::fAWR\fC [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBxendfb\&.C\fP\&.
.SS "int XSec::fIZA\fC [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBxendfb\&.C\fP\&.
.SS "double XSec::fQI\fC [protected]\fP"

.PP
Definition at line \fB43\fP of file \fBxendfb\&.C\fP\&.
.SS "double XSec::fQM\fC [protected]\fP"

.PP
Definition at line \fB42\fP of file \fBxendfb\&.C\fP\&.
.SS "vector<double> XSec::xs\fC [protected]\fP"

.PP
Definition at line \fB45\fP of file \fBxendfb\&.C\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
