.TH "XSecStore" 3 "Fri Oct 15 2021" "Version Version 1.0" "Transmutex Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSecStore
.SH SYNOPSIS
.br
.PP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "map< int, map< int, \fBXSec\fP > > \fBfXsecStore\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBXSecStore\fP * \fBfInstance\fP =nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB74\fP of file \fBxendfb\&.C\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XSecStore::XSecStore ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line \fB88\fP of file \fBxendfb\&.C\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBXSecStore\fP * XSecStore::fInstance =nullptr\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB90\fP of file \fBxendfb\&.C\fP\&.
.SS "map<int,map<int,\fBXSec\fP> > XSecStore::fXsecStore\fC [protected]\fP"

.PP
Definition at line \fB89\fP of file \fBxendfb\&.C\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Transmutex Documentation from the source code\&.
